= Configuration Management
:toc:
:toclevels: 1
:cm-1_prm_1: organization-defined personnel or roles
:cm-1_prm_2: one-or-more: Organization-level, Mission/business process-level, System-level
:cm-1_prm_3: organization-defined official
:cm-1_prm_4: organization-defined frequency
:cm-1_prm_5: organization-defined events
:cm-1_prm_6: organization-defined frequency
:cm-1_prm_7: organization-defined events
:cm-2_prm_1: organization-defined frequency
:cm-2_prm_2: organization-defined circumstances
:cm-2-2_prm_1: organization-defined automated mechanisms
:cm-2-3_prm_1: organization-defined number
:cm-2-7_prm_1: organization-defined systems or system components
:cm-2-7_prm_2: organization-defined configurations
:cm-2-7_prm_3: organization-defined controls
:cm-3_prm_1: organization-defined time period
:cm-3_prm_2: organization-defined configuration change control element
:cm-3_prm_3: one-or-more: _[Assignment: organization-defined frequency]_, when _[Assignment: organization-defined configuration change conditions]_
:cm-3_prm_4: organization-defined frequency
:cm-3_prm_5: organization-defined configuration change conditions
:cm-3-1_prm_1: organization-defined automated mechanisms
:cm-3-1_prm_2: organization-defined approval authorities
:cm-3-1_prm_3: organization-defined time period
:cm-3-1_prm_4: organization-defined personnel
:cm-3-3_prm_1: organization-defined automated mechanisms
:cm-3-4_prm_1: organization-defined security and privacy representatives
:cm-3-4_prm_2: organization-defined configuration change control element
:cm-3-5_prm_1: organization-defined security responses
:cm-3-6_prm_1: organization-defined controls
:cm-3-7_prm_1: organization-defined frequency
:cm-3-7_prm_2: organization-defined circumstances
:cm-3-8_prm_1: organization-defined circumstances
:cm-5-1_prm_1: organization-defined automated mechanisms
:cm-5-4_prm_1: organization-defined system components and system-level information
:cm-5-5_prm_1: organization-defined frequency
:cm-6_prm_1: organization-defined common secure configurations
:cm-6_prm_2: organization-defined system components
:cm-6_prm_3: organization-defined operational requirements
:cm-6-1_prm_1: organization-defined system components
:cm-6-1_prm_2: organization-defined automated mechanisms
:cm-6-2_prm_1: organization-defined configuration settings
:cm-6-2_prm_2: organization-defined actions
:cm-7_prm_1: organization-defined mission essential capabilities
:cm-7_prm_2: organization-defined prohibited or restricted functions, system ports, protocols, software, and/or services
:cm-7-1_prm_1: organization-defined frequency
:cm-7-1_prm_2: organization-defined functions, ports, protocols, software, and services within the system deemed to be unnecessary and/or nonsecure
:cm-7-2_prm_1: one-or-more: _[Assignment: organization-defined policies, rules of behavior, and/or access agreements regarding software program usage and restrictions]_, rules authorizing the terms and conditions of software program usage
:cm-7-2_prm_2: organization-defined policies, rules of behavior, and/or access agreements regarding software program usage and restrictions
:cm-7-3_prm_1: organization-defined registration requirements for functions, ports, protocols, and services
:cm-7-4_prm_1: organization-defined software programs not authorized to execute on the system
:cm-7-4_prm_2: organization-defined frequency
:cm-7-5_prm_1: organization-defined software programs authorized to execute on the system
:cm-7-5_prm_2: organization-defined frequency
:cm-7-6_prm_1: organization-defined user-installed software
:cm-7-7_prm_1: organization-defined personnel or roles
:cm-7-9_prm_1: organization-defined hardware components authorized for system use
:cm-7-9_prm_2: organization-defined frequency
:cm-8_prm_1: organization-defined information deemed necessary to achieve effective system component accountability
:cm-8_prm_2: organization-defined frequency
:cm-8-2_prm_1: organization-defined automated mechanisms
:cm-8-3_prm_1: organization-defined automated mechanisms
:cm-8-3_prm_2: organization-defined frequency
:cm-8-3_prm_3: one-or-more: disable network access by such components, isolate the components, notify _[Assignment: organization-defined personnel or roles]_
:cm-8-3_prm_4: organization-defined personnel or roles
:cm-8-4_prm_1: one-or-more: name, position, role
:cm-8-8_prm_1: organization-defined automated mechanisms
:cm-8-9_prm_1: organization-defined personnel or roles
:cm-9_prm_1: organization-defined personnel or roles
:cm-10-1_prm_1: organization-defined restrictions
:cm-11_prm_1: organization-defined policies
:cm-11_prm_2: organization-defined methods
:cm-11_prm_3: organization-defined frequency
:cm-11-3_prm_1: organization-defined automated mechanisms
:cm-12_prm_1: organization-defined information
:cm-12-1_prm_1: organization-defined information by information type
:cm-12-1_prm_2: organization-defined system components
:cm-14_prm_1: organization-defined software and firmware components

== CM-1 Policy and Procedures[[cm-1]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Develop, document, and disseminate to _[Assignment: {cm-1_prm_1}]_:
1. _[Assignment: {cm-1_prm_2}]_ configuration management policy that:
(a) Addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance; and
(b) Is consistent with applicable laws, executive orders, directives, regulations, policies, standards, and guidelines; and
2. Procedures to facilitate the implementation of the configuration management policy and the associated configuration management controls;
b. Designate an _[Assignment: {cm-1_prm_3}]_ to manage the development, documentation, and dissemination of the configuration management policy and procedures; and
c. Review and update the current configuration management:
1. Policy _[Assignment: {cm-1_prm_4}]_ and following _[Assignment: {cm-1_prm_5}]_; and
2. Procedures _[Assignment: {cm-1_prm_6}]_ and following _[Assignment: {cm-1_prm_7}]_.

=== Supplemental Guidance
Configuration management policy and procedures address the controls in the CM family that are implemented within systems and organizations. The risk management strategy is an important factor in establishing such policies and procedures. Policies and procedures contribute to security and privacy assurance. Therefore, it is important that security and privacy programs collaborate on the development of configuration management policy and procedures. Security and privacy program policies and procedures at the organization level are preferable, in general, and may obviate the need for mission- or system-specific policies and procedures. The policy can be included as part of the general security and privacy policy or be represented by multiple policies that reflect the complex nature of organizations. Procedures can be established for security and privacy programs, for mission/business processes, and for systems, if needed. Procedures describe how the policies or controls are implemented and can be directed at the individual or role that is the object of the procedure. Procedures can be documented in system security and privacy plans or in one or more separate documents. Events that may precipitate an update to configuration management policy and procedures include, but are not limited to, assessment or audit findings, security incidents or breaches, or changes in applicable laws, executive orders, directives, regulations, policies, standards, and guidelines. Simply restating controls does not constitute an organizational policy or procedure.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-12r1[SP 800-12], https://doi.org/10.6028/NIST.SP.800-30r1[SP 800-30], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-100[SP 800-100]

== CM-2 Baseline Configuration[[cm-2]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Develop, document, and maintain under configuration control, a current baseline configuration of the system; and
b. Review and update the baseline configuration of the system:
1. _[Assignment: {cm-2_prm_1}]_;
2. When required due to _[Assignment: {cm-2_prm_2}]_; and
3. When system components are installed or upgraded.

=== TAMUS Implementation Details
The System member ensures all servers on System-owned or -managed networks conform to a baseline security configuration and are security-hardened based on risk.

=== Supplemental Guidance
Baseline configurations for systems and system components include connectivity, operational, and communications aspects of systems. Baseline configurations are documented, formally reviewed, and agreed-upon specifications for systems or configuration items within those systems. Baseline configurations serve as a basis for future builds, releases, or changes to systems and include security and privacy control implementations, operational procedures, information about system components, network topology, and logical placement of components in the system architecture. Maintaining baseline configurations requires creating new baselines as organizational systems change over time. Baseline configurations of systems reflect the current enterprise architecture.

=== References
https://doi.org/10.6028/NIST.SP.800-124r1[SP 800-124], https://doi.org/10.6028/NIST.SP.800-128[SP 800-128]

=== Control Enhancements
==== CM-2(1) Reviews and Updates[[cm-2-1]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:cm.adoc#cm-2[CM-2]

==== CM-2(2) Automation Support for Accuracy and Currency[[cm-2-2]]

===== Control
Maintain the currency, completeness, accuracy, and availability of the baseline configuration of the system using _[Assignment: {cm-2-2_prm_1}]_.

===== Supplemental Guidance
Automated mechanisms that help organizations maintain consistent baseline configurations for systems include configuration management tools, hardware, software, firmware inventory tools, and network management tools. Automated tools can be used at the organization level, mission and business process level, or system level on workstations, servers, notebook computers, network components, or mobile devices. Tools can be used to track version numbers on operating systems, applications, types of software installed, and current patch levels. Automation support for accuracy and currency can be satisfied by the implementation of 

==== CM-2(3) Retention of Previous Configurations[[cm-2-3]]

===== Control
Retain _[Assignment: {cm-2-3_prm_1}]_ of previous versions of baseline configurations of the system to support rollback.

===== Supplemental Guidance
Retaining previous versions of baseline configurations to support rollback include hardware, software, firmware, configuration files, configuration records, and associated documentation.

==== CM-2(4) Unauthorized Software[[cm-2-4]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:cm.adoc#cm-7-4[CM-7.4]

==== CM-2(5) Authorized Software[[cm-2-5]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:cm.adoc#cm-7-5[CM-7.5]

==== CM-2(6) Development and Test Environments[[cm-2-6]]

===== Control
Maintain a baseline configuration for system development and test environments that is managed separately from the operational baseline configuration.

===== Supplemental Guidance
Establishing separate baseline configurations for development, testing, and operational environments protects systems from unplanned or unexpected events related to development and testing activities. Separate baseline configurations allow organizations to apply the configuration management that is most appropriate for each type of configuration. For example, the management of operational configurations typically emphasizes the need for stability, while the management of development or test configurations requires greater flexibility. Configurations in the test environment mirror configurations in the operational environment to the extent practicable so that the results of the testing are representative of the proposed changes to the operational systems. Separate baseline configurations do not necessarily require separate physical environments.

==== CM-2(7) Configure Systems and Components for High-risk Areas[[cm-2-7]]

===== Control
(a) Issue _[Assignment: {cm-2-7_prm_1}]_ with _[Assignment: {cm-2-7_prm_2}]_ to individuals traveling to locations that the organization deems to be of significant risk; and
(b) Apply the following controls to the systems or components when the individuals return from travel: _[Assignment: {cm-2-7_prm_3}]_.

===== Supplemental Guidance
When it is known that systems or system components will be in high-risk areas external to the organization, additional controls may be implemented to counter the increased threat in such areas. For example, organizations can take actions for notebook computers used by individuals departing on and returning from travel. Actions include determining the locations that are of concern, defining the required configurations for the components, ensuring that components are configured as intended before travel is initiated, and applying controls to the components after travel is completed. Specially configured notebook computers include computers with sanitized hard drives, limited applications, and more stringent configuration settings. Controls applied to mobile devices upon return from travel include examining the mobile device for signs of physical tampering and purging and reimaging disk drives. Protecting information that resides on mobile devices is addressed in the 

== CM-3 Configuration Change Control[[cm-3]]

=== Control
a. Determine and document the types of changes to the system that are configuration-controlled;
b. Review proposed configuration-controlled changes to the system and approve or disapprove such changes with explicit consideration for security and privacy impact analyses;
c. Document configuration change decisions associated with the system;
d. Implement approved configuration-controlled changes to the system;
e. Retain records of configuration-controlled changes to the system for _[Assignment: {cm-3_prm_1}]_;
f. Monitor and review activities associated with configuration-controlled changes to the system; and
g. Coordinate and provide oversight for configuration change control activities through _[Assignment: {cm-3_prm_2}]_ that convenes _[Assignment: {cm-3_prm_3}]_.

=== TAMUS Implementation Details
The System member incorporates change management processes to ensure secure, reliable, and stable operations to which all offices that support information systems adhere. The change management process incorporates guidelines that address:
a. formally identifying, classifying, prioritizing, and requesting changes;
b. identifying and deploying emergency changes;
c. assessing potential impacts from changes;
d. authorizing changes and exceptions;
e. testing changes;
f. implementing changes and planning for back-outs, and
g. documenting and tracking changes.

=== Supplemental Guidance
Configuration change control for organizational systems involves the systematic proposal, justification, implementation, testing, review, and disposition of system changes, including system upgrades and modifications. Configuration change control includes changes to baseline configurations, configuration items of systems, operational procedures, configuration settings for system components, remediate vulnerabilities, and unscheduled or unauthorized changes. Processes for managing configuration changes to systems include Configuration Control Boards or Change Advisory Boards that review and approve proposed changes. For changes that impact privacy risk, the senior agency official for privacy updates privacy impact assessments and system of records notices. For new systems or major upgrades, organizations consider including representatives from the development organizations on the Configuration Control Boards or Change Advisory Boards. Auditing of changes includes activities before and after changes are made to systems and the auditing activities required to implement such changes. See also 

=== References
https://doi.org/10.6028/NIST.SP.800-124r1[SP 800-124], https://doi.org/10.6028/NIST.SP.800-128[SP 800-128], https://doi.org/10.6028/NIST.IR.8062[IR 8062]

=== Control Enhancements
==== CM-3(1) Automated Documentation, Notification, and Prohibition of Changes[[cm-3-1]]

===== Control
Use _[Assignment: {cm-3-1_prm_1}]_ to:
(a) Document proposed changes to the system;
(b) Notify _[Assignment: {cm-3-1_prm_2}]_ of proposed changes to the system and request change approval;
(c) Highlight proposed changes to the system that have not been approved or disapproved within _[Assignment: {cm-3-1_prm_3}]_;
(d) Prohibit changes to the system until designated approvals are received;
(e) Document all changes to the system; and
(f) Notify _[Assignment: {cm-3-1_prm_4}]_ when approved changes to the system are completed.

===== Supplemental Guidance
None.

==== CM-3(2) Testing, Validation, and Documentation of Changes[[cm-3-2]]

===== Control
Test, validate, and document changes to the system before finalizing the implementation of the changes.

===== Supplemental Guidance
Changes to systems include modifications to hardware, software, or firmware components and configuration settings defined in 

==== CM-3(3) Automated Change Implementation[[cm-3-3]]

===== Control
Implement changes to the current system baseline and deploy the updated baseline across the installed base using _[Assignment: {cm-3-3_prm_1}]_.

===== Supplemental Guidance
Automated tools can improve the accuracy, consistency, and availability of configuration baseline information. Automation can also provide data aggregation and data correlation capabilities, alerting mechanisms, and dashboards to support risk-based decision-making within the organization.

==== CM-3(4) Security and Privacy Representatives[[cm-3-4]]

===== Control
Require _[Assignment: {cm-3-4_prm_1}]_ to be members of the _[Assignment: {cm-3-4_prm_2}]_.

===== Supplemental Guidance
Information security and privacy representatives include system security officers, senior agency information security officers, senior agency officials for privacy, or system privacy officers. Representation by personnel with information security and privacy expertise is important because changes to system configurations can have unintended side effects, some of which may be security- or privacy-relevant. Detecting such changes early in the process can help avoid unintended, negative consequences that could ultimately affect the security and privacy posture of systems. The configuration change control element referred to in the second organization-defined parameter reflects the change control elements defined by organizations in 

==== CM-3(5) Automated Security Response[[cm-3-5]]

===== Control
Implement the following security responses automatically if baseline configurations are changed in an unauthorized manner: _[Assignment: {cm-3-5_prm_1}]_.

===== Supplemental Guidance
Automated security responses include halting selected system functions, halting system processing, and issuing alerts or notifications to organizational personnel when there is an unauthorized modification of a configuration item.

==== CM-3(6) Cryptography Management[[cm-3-6]]

===== Control
Ensure that cryptographic mechanisms used to provide the following controls are under configuration management: _[Assignment: {cm-3-6_prm_1}]_.

===== Supplemental Guidance
The controls referenced in the control enhancement refer to security and privacy controls from the control catalog. Regardless of the cryptographic mechanisms employed, processes and procedures are in place to manage those mechanisms. For example, if system components use certificates for identification and authentication, a process is implemented to address the expiration of those certificates.

==== CM-3(7) Review System Changes[[cm-3-7]]

===== Control
Review changes to the system _[Assignment: {cm-3-7_prm_1}]_ or when _[Assignment: {cm-3-7_prm_2}]_ to determine whether unauthorized changes have occurred.

===== Supplemental Guidance
Indications that warrant a review of changes to the system and the specific circumstances justifying such reviews may be obtained from activities carried out by organizations during the configuration change process or continuous monitoring process.

==== CM-3(8) Prevent or Restrict Configuration Changes[[cm-3-8]]

===== Control
Prevent or restrict changes to the configuration of the system under the following circumstances: _[Assignment: {cm-3-8_prm_1}]_.

===== Supplemental Guidance
System configuration changes can adversely affect critical system security and privacy functionality. Change restrictions can be enforced through automated mechanisms.

== CM-4 Impact Analyses[[cm-4]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
Analyze changes to the system to determine potential security and privacy impacts prior to change implementation.

=== State Implementation Details
1. All security-related information resources changes shall be approved by the information owner through a change control process.
2. Approval shall occur prior to implementation by the state organization or independent contractors.

=== Supplemental Guidance
Organizational personnel with security or privacy responsibilities conduct impact analyses. Individuals conducting impact analyses possess the necessary skills and technical expertise to analyze the changes to systems as well as the security or privacy ramifications. Impact analyses include reviewing security and privacy plans, policies, and procedures to understand control requirements; reviewing system design documentation and operational procedures to understand control implementation and how specific system changes might affect the controls; reviewing the impact of changes on organizational supply chain partners with stakeholders; and determining how potential changes to a system create new risks to the privacy of individuals and the ability of implemented controls to mitigate those risks. Impact analyses also include risk assessments to understand the impact of the changes and determine if additional controls are required.

=== References
https://doi.org/10.6028/NIST.SP.800-128[SP 800-128]

=== Control Enhancements
==== CM-4(1) Separate Test Environments[[cm-4-1]]

===== Control
Analyze changes to the system in a separate test environment before implementation in an operational environment, looking for security and privacy impacts due to flaws, weaknesses, incompatibility, or intentional malice.

===== Supplemental Guidance
A separate test environment requires an environment that is physically or logically separate and distinct from the operational environment. The separation is sufficient to ensure that activities in the test environment do not impact activities in the operational environment and that information in the operational environment is not inadvertently transmitted to the test environment. Separate environments can be achieved by physical or logical means. If physically separate test environments are not implemented, organizations determine the strength of mechanism required when implementing logical separation.

==== CM-4(2) Verification of Controls[[cm-4-2]]

===== Control
After system changes, verify that the impacted controls are implemented correctly, operating as intended, and producing the desired outcome with regard to meeting the security and privacy requirements for the system.

===== Supplemental Guidance
Implementation in this context refers to installing changed code in the operational system that may have an impact on security or privacy controls.

== CM-5 Access Restrictions for Change[[cm-5]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
Define, document, approve, and enforce physical and logical access restrictions associated with changes to the system.

=== Supplemental Guidance
Changes to the hardware, software, or firmware components of systems or the operational procedures related to the system can potentially have significant effects on the security of the systems or individuals' privacy. Therefore, organizations permit only qualified and authorized individuals to access systems for purposes of initiating changes. Access restrictions include physical and logical access controls (see 

=== References
https://doi.org/10.6028/NIST.FIPS.140-3[FIPS 140-3], https://doi.org/10.6028/NIST.FIPS.186-4[FIPS 186-4]

=== Control Enhancements
==== CM-5(1) Automated Access Enforcement and Audit Records[[cm-5-1]]

===== Control
(a) Enforce access restrictions using _[Assignment: {cm-5-1_prm_1}]_; and
(b) Automatically generate audit records of the enforcement actions.

===== Supplemental Guidance
Organizations log system accesses associated with applying configuration changes to ensure that configuration change control is implemented and to support after-the-fact actions should organizations discover any unauthorized changes.

==== CM-5(2) Review System Changes[[cm-5-2]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:cm.adoc#cm-3-7[CM-3.7]

==== CM-5(3) Signed Components[[cm-5-3]]

[width=50\%]
|===



|===

Status:: Withdrawn

Moved To:: xref:cm.adoc#cm-14[CM-14]

==== CM-5(4) Dual Authorization[[cm-5-4]]

===== Control
Enforce dual authorization for implementing changes to _[Assignment: {cm-5-4_prm_1}]_.

===== Supplemental Guidance
Organizations employ dual authorization to help ensure that any changes to selected system components and information cannot occur unless two qualified individuals approve and implement such changes. The two individuals possess the skills and expertise to determine if the proposed changes are correct implementations of approved changes. The individuals are also accountable for the changes. Dual authorization may also be known as two-person control. To reduce the risk of collusion, organizations consider rotating dual authorization duties to other individuals. System-level information includes operational procedures.

==== CM-5(5) Privilege Limitation for Production and Operation[[cm-5-5]]

===== Control
(a) Limit privileges to change system components and system-related information within a production or operational environment; and
(b) Review and reevaluate privileges _[Assignment: {cm-5-5_prm_1}]_.

===== Supplemental Guidance
In many organizations, systems support multiple mission and business functions. Limiting privileges to change system components with respect to operational systems is necessary because changes to a system component may have far-reaching effects on mission and business processes supported by the system. The relationships between systems and mission/business processes are, in some cases, unknown to developers. System-related information includes operational procedures.

==== CM-5(6) Limit Library Privileges[[cm-5-6]]

===== Control
Limit privileges to change software resident within software libraries.

===== Supplemental Guidance
Software libraries include privileged programs.

==== CM-5(7) Automatic Implementation of Security Safeguards[[cm-5-7]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:si.adoc#si-7[SI-7]

== CM-6 Configuration Settings[[cm-6]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Establish and document configuration settings for components employed within the system that reflect the most restrictive mode consistent with operational requirements using _[Assignment: {cm-6_prm_1}]_;
b. Implement the configuration settings;
c. Identify, document, and approve any deviations from established configuration settings for _[Assignment: {cm-6_prm_2}]_ based on _[Assignment: {cm-6_prm_3}]_; and
d. Monitor and control changes to the configuration settings in accordance with organizational policies and procedures.

=== TAMUS Implementation Details
The System member adopts baseline security configuration checklists that meet or exceed published industry best practice sources (e.g., Center for Internet Security Benchmarks [CIS Benchmarks](#eedcbb1f-0f8e-4efc-a02b-74c9fb8438cc), NIST National Checklist Program [NCP](#997c9abf-6669-4196-89fd-68fce5f21b74)) when available, or locally develops security configuration checklists otherwise, for all System-owned or -managed major and high-impact information systems, and systems processing confidential information.

=== Supplemental Guidance
Configuration settings are the parameters that can be changed in the hardware, software, or firmware components of the system that affect the security and privacy posture or functionality of the system. Information technology products for which configuration settings can be defined include mainframe computers, servers, workstations, operating systems, mobile devices, input/output devices, protocols, and applications. Parameters that impact the security posture of systems include registry settings; account, file, or directory permission settings; and settings for functions, protocols, ports, services, and remote connections. Privacy parameters are parameters impacting the privacy posture of systems, including the parameters required to satisfy other privacy controls. Privacy parameters include settings for access controls, data processing preferences, and processing and retention permissions. Organizations establish organization-wide configuration settings and subsequently derive specific configuration settings for systems. The established settings become part of the configuration baseline for the system.
Common secure configurations (also known as security configuration checklists, lockdown and hardening guides, and security reference guides) provide recognized, standardized, and established benchmarks that stipulate secure configuration settings for information technology products and platforms as well as instructions for configuring those products or platforms to meet operational requirements. Common secure configurations can be developed by a variety of organizations, including information technology product developers, manufacturers, vendors, federal agencies, consortia, academia, industry, and other organizations in the public and private sectors.
Implementation of a common secure configuration may be mandated at the organization level, mission and business process level, system level, or at a higher level, including by a regulatory agency. Common secure configurations include the United States Government Configuration Baseline 

=== References
https://www.cisecurity.org/cis-benchmarks[CIS Benchmarks], https://nvd.nist.gov/ncp/repository[National Checklist Program Repository], https://doi.org/10.6028/NIST.SP.800-70r4[SP 800-70], https://doi.org/10.6028/NIST.SP.800-126r3[SP 800-126], https://doi.org/10.6028/NIST.SP.800-128[SP 800-128], https://csrc.nist.gov/projects/united-states-government-configuration-baseline[USGCB], https://nvd.nist.gov/ncp/repository[NCPR], https://public.cyber.mil/stigs[DOD STIG]

=== Control Enhancements
==== CM-6(1) Automated Management, Application, and Verification[[cm-6-1]]

===== Control
Manage, apply, and verify configuration settings for _[Assignment: {cm-6-1_prm_1}]_ using _[Assignment: {cm-6-1_prm_2}]_.

===== Supplemental Guidance
Automated tools (e.g., hardening tools, baseline configuration tools) can improve the accuracy, consistency, and availability of configuration settings information. Automation can also provide data aggregation and data correlation capabilities, alerting mechanisms, and dashboards to support risk-based decision-making within the organization.

==== CM-6(2) Respond to Unauthorized Changes[[cm-6-2]]

===== Control
Take the following actions in response to unauthorized changes to _[Assignment: {cm-6-2_prm_1}]_: _[Assignment: {cm-6-2_prm_2}]_.

===== Supplemental Guidance
Responses to unauthorized changes to configuration settings include alerting designated organizational personnel, restoring established configuration settings, or-in extreme cases-halting affected system processing.

==== CM-6(3) Unauthorized Change Detection[[cm-6-3]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:si.adoc#si-7[SI-7]

==== CM-6(4) Conformance Demonstration[[cm-6-4]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:cm.adoc#cm-4[CM-4]

== CM-7 Least Functionality[[cm-7]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Configure the system to provide only _[Assignment: {cm-7_prm_1}]_; and
b. Prohibit or restrict the use of the following functions, ports, protocols, software, and/or services: _[Assignment: {cm-7_prm_2}]_.

=== Supplemental Guidance
Systems provide a wide variety of functions and services. Some of the functions and services routinely provided by default may not be necessary to support essential organizational missions, functions, or operations. Additionally, it is sometimes convenient to provide multiple services from a single system component, but doing so increases risk over limiting the services provided by that single component. Where feasible, organizations limit component functionality to a single function per component. Organizations consider removing unused or unnecessary software and disabling unused or unnecessary physical and logical ports and protocols to prevent unauthorized connection of components, transfer of information, and tunneling. Organizations employ network scanning tools, intrusion detection and prevention systems, and end-point protection technologies, such as firewalls and host-based intrusion detection systems, to identify and prevent the use of prohibited functions, protocols, ports, and services. Least functionality can also be achieved as part of the fundamental design and development of the system (see 

=== References
https://doi.org/10.6028/NIST.FIPS.140-3[FIPS 140-3], https://doi.org/10.6028/NIST.FIPS.180-4[FIPS 180-4], https://doi.org/10.6028/NIST.FIPS.186-4[FIPS 186-4], https://doi.org/10.6028/NIST.FIPS.202[FIPS 202], https://doi.org/10.6028/NIST.SP.800-167[SP 800-167]

=== Control Enhancements
==== CM-7(1) Periodic Review[[cm-7-1]]

===== Control
(a) Review the system _[Assignment: {cm-7-1_prm_1}]_ to identify unnecessary and/or nonsecure functions, ports, protocols, software, and services; and
(b) Disable or remove _[Assignment: {cm-7-1_prm_2}]_.

===== Supplemental Guidance
Organizations review functions, ports, protocols, and services provided by systems or system components to determine the functions and services that are candidates for elimination. Such reviews are especially important during transition periods from older technologies to newer technologies (e.g., transition from IPv4 to IPv6). These technology transitions may require implementing the older and newer technologies simultaneously during the transition period and returning to minimum essential functions, ports, protocols, and services at the earliest opportunity. Organizations can either decide the relative security of the function, port, protocol, and/or service or base the security decision on the assessment of other entities. Unsecure protocols include Bluetooth, FTP, and peer-to-peer networking.

==== CM-7(2) Prevent Program Execution[[cm-7-2]]

===== Control
Prevent program execution in accordance with _[Assignment: {cm-7-2_prm_1}]_.

===== Supplemental Guidance
Prevention of program execution addresses organizational policies, rules of behavior, and/or access agreements that restrict software usage and the terms and conditions imposed by the developer or manufacturer, including software licensing and copyrights. Restrictions include prohibiting auto-execute features, restricting roles allowed to approve program execution, permitting or prohibiting specific software programs, or restricting the number of program instances executed at the same time.

==== CM-7(3) Registration Compliance[[cm-7-3]]

===== Control
Ensure compliance with _[Assignment: {cm-7-3_prm_1}]_.

===== Supplemental Guidance
Organizations use the registration process to manage, track, and provide oversight for systems and implemented functions, ports, protocols, and services.

==== CM-7(4) Unauthorized Software - Deny-by-exception[[cm-7-4]]

===== Control
(a) Identify _[Assignment: {cm-7-4_prm_1}]_;
(b) Employ an allow-all, deny-by-exception policy to prohibit the execution of unauthorized software programs on the system; and
(c) Review and update the list of unauthorized software programs _[Assignment: {cm-7-4_prm_2}]_.

===== Supplemental Guidance
Unauthorized software programs can be limited to specific versions or from a specific source. The concept of prohibiting the execution of unauthorized software may also be applied to user actions, system ports and protocols, IP addresses/ranges, websites, and MAC addresses.

==== CM-7(5) Authorized Software - Allow-by-exception[[cm-7-5]]

===== Control
(a) Identify _[Assignment: {cm-7-5_prm_1}]_;
(b) Employ a deny-all, permit-by-exception policy to allow the execution of authorized software programs on the system; and
(c) Review and update the list of authorized software programs _[Assignment: {cm-7-5_prm_2}]_.

===== Supplemental Guidance
Authorized software programs can be limited to specific versions or from a specific source. To facilitate a comprehensive authorized software process and increase the strength of protection for attacks that bypass application level authorized software, software programs may be decomposed into and monitored at different levels of detail. These levels include applications, application programming interfaces, application modules, scripts, system processes, system services, kernel functions, registries, drivers, and dynamic link libraries. The concept of permitting the execution of authorized software may also be applied to user actions, system ports and protocols, IP addresses/ranges, websites, and MAC addresses. Organizations consider verifying the integrity of authorized software programs using digital signatures, cryptographic checksums, or hash functions. Verification of authorized software can occur either prior to execution or at system startup. The identification of authorized URLs for websites is addressed in 

==== CM-7(6) Confined Environments with Limited Privileges[[cm-7-6]]

===== Control
Require that the following user-installed software execute in a confined physical or virtual machine environment with limited privileges: _[Assignment: {cm-7-6_prm_1}]_.

===== Supplemental Guidance
Organizations identify software that may be of concern regarding its origin or potential for containing malicious code. For this type of software, user installations occur in confined environments of operation to limit or contain damage from malicious code that may be executed.

==== CM-7(7) Code Execution in Protected Environments[[cm-7-7]]

===== Control
Allow execution of binary or machine-executable code only in confined physical or virtual machine environments and with the explicit approval of _[Assignment: {cm-7-7_prm_1}]_ when such code is:
(a) Obtained from sources with limited or no warranty; and/or
(b) Without the provision of source code.

===== Supplemental Guidance
Code execution in protected environments applies to all sources of binary or machine-executable code, including commercial software and firmware and open-source software.

==== CM-7(8) Binary or Machine Executable Code[[cm-7-8]]

===== Control
(a) Prohibit the use of binary or machine-executable code from sources with limited or no warranty or without the provision of source code; and
(b) Allow exceptions only for compelling mission or operational requirements and with the approval of the authorizing official.

===== Supplemental Guidance
Binary or machine executable code applies to all sources of binary or machine-executable code, including commercial software and firmware and open-source software. Organizations assess software products without accompanying source code or from sources with limited or no warranty for potential security impacts. The assessments address the fact that software products without the provision of source code may be difficult to review, repair, or extend. In addition, there may be no owners to make such repairs on behalf of organizations. If open-source software is used, the assessments address the fact that there is no warranty, the open-source software could contain back doors or malware, and there may be no support available.

==== CM-7(9) Prohibiting The Use of Unauthorized Hardware[[cm-7-9]]

===== Control
(a) Identify _[Assignment: {cm-7-9_prm_1}]_;
(b) Prohibit the use or connection of unauthorized hardware components;
(c) Review and update the list of authorized hardware components _[Assignment: {cm-7-9_prm_2}]_.

===== Supplemental Guidance
Hardware components provide the foundation for organizational systems and the platform for the execution of authorized software programs. Managing the inventory of hardware components and controlling which hardware components are permitted to be installed or connected to organizational systems is essential in order to provide adequate security.

== CM-8 System Component Inventory[[cm-8]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Develop and document an inventory of system components that:
1. Accurately reflects the system;
2. Includes all components within the system;
3. Does not include duplicate accounting of components or components assigned to any other system;
4. Is at the level of granularity deemed necessary for tracking and reporting; and
5. Includes the following information to achieve system component accountability: _[Assignment: {cm-8_prm_1}]_; and
b. Review and update the system component inventory _[Assignment: {cm-8_prm_2}]_.

=== Supplemental Guidance
System components are discrete, identifiable information technology assets that include hardware, software, and firmware. Organizations may choose to implement centralized system component inventories that include components from all organizational systems. In such situations, organizations ensure that the inventories include system-specific information required for component accountability. The information necessary for effective accountability of system components includes the system name, software owners, software version numbers, hardware inventory specifications, software license information, and for networked components, the machine names and network addresses across all implemented protocols (e.g., IPv4, IPv6). Inventory specifications include date of receipt, cost, model, serial number, manufacturer, supplier information, component type, and physical location.
Preventing duplicate accounting of system components addresses the lack of accountability that occurs when component ownership and system association is not known, especially in large or complex connected systems. Effective prevention of duplicate accounting of system components necessitates use of a unique identifier for each component. For software inventory, centrally managed software that is accessed via other systems is addressed as a component of the system on which it is installed and managed. Software installed on multiple organizational systems and managed at the system level is addressed for each individual system and may appear more than once in a centralized component inventory, necessitating a system association for each software instance in the centralized inventory to avoid duplicate accounting of components. Scanning systems implementing multiple network protocols (e.g., IPv4 and IPv6) can result in duplicate components being identified in different address spaces. The implementation of 

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-57pt1r5[SP 800-57-1], https://doi.org/10.6028/NIST.SP.800-57pt2r1[SP 800-57-2], https://doi.org/10.6028/NIST.SP.800-57pt3r1[SP 800-57-3], https://doi.org/10.6028/NIST.SP.800-128[SP 800-128], https://doi.org/10.6028/NIST.IR.8011-2[IR 8011-2], https://doi.org/10.6028/NIST.IR.8011-3[IR 8011-3]

=== Control Enhancements
==== CM-8(1) Updates During Installation and Removal[[cm-8-1]]

===== Control
Update the inventory of system components as part of component installations, removals, and system updates.

===== Supplemental Guidance
Organizations can improve the accuracy, completeness, and consistency of system component inventories if the inventories are updated as part of component installations or removals or during general system updates. If inventories are not updated at these key times, there is a greater likelihood that the information will not be appropriately captured and documented. System updates include hardware, software, and firmware components.

==== CM-8(2) Automated Maintenance[[cm-8-2]]

===== Control
Maintain the currency, completeness, accuracy, and availability of the inventory of system components using _[Assignment: {cm-8-2_prm_1}]_.

===== Supplemental Guidance
Organizations maintain system inventories to the extent feasible. For example, virtual machines can be difficult to monitor because such machines are not visible to the network when not in use. In such cases, organizations maintain as up-to-date, complete, and accurate an inventory as is deemed reasonable. Automated maintenance can be achieved by the implementation of 

==== CM-8(3) Automated Unauthorized Component Detection[[cm-8-3]]

===== Control
(a) Detect the presence of unauthorized hardware, software, and firmware components within the system using _[Assignment: {cm-8-3_prm_1}]_
                     _[Assignment: {cm-8-3_prm_2}]_; and
(b) Take the following actions when unauthorized components are detected: _[Assignment: {cm-8-3_prm_3}]_.

===== Supplemental Guidance
Automated unauthorized component detection is applied in addition to the monitoring for unauthorized remote connections and mobile devices. Monitoring for unauthorized system components may be accomplished on an ongoing basis or by the periodic scanning of systems for that purpose. Automated mechanisms may also be used to prevent the connection of unauthorized components (see 

==== CM-8(4) Accountability Information[[cm-8-4]]

===== Control
Include in the system component inventory information, a means for identifying by _[Assignment: {cm-8-4_prm_1}]_, individuals responsible and accountable for administering those components.

===== Supplemental Guidance
Identifying individuals who are responsible and accountable for administering system components ensures that the assigned components are properly administered and that organizations can contact those individuals if some action is required (e.g., when the component is determined to be the source of a breach, needs to be recalled or replaced, or needs to be relocated).

==== CM-8(5) No Duplicate Accounting of Components[[cm-8-5]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:cm.adoc#cm-8[CM-8]

==== CM-8(6) Assessed Configurations and Approved Deviations[[cm-8-6]]

===== Control
Include assessed component configurations and any approved deviations to current deployed configurations in the system component inventory.

===== Supplemental Guidance
Assessed configurations and approved deviations focus on configuration settings established by organizations for system components, the specific components that have been assessed to determine compliance with the required configuration settings, and any approved deviations from established configuration settings.

==== CM-8(7) Centralized Repository[[cm-8-7]]

===== Control
Provide a centralized repository for the inventory of system components.

===== Supplemental Guidance
Organizations may implement centralized system component inventories that include components from all organizational systems. Centralized repositories of component inventories provide opportunities for efficiencies in accounting for organizational hardware, software, and firmware assets. Such repositories may also help organizations rapidly identify the location and responsible individuals of components that have been compromised, breached, or are otherwise in need of mitigation actions. Organizations ensure that the resulting centralized inventories include system-specific information required for proper component accountability.

==== CM-8(8) Automated Location Tracking[[cm-8-8]]

===== Control
Support the tracking of system components by geographic location using _[Assignment: {cm-8-8_prm_1}]_.

===== Supplemental Guidance
The use of automated mechanisms to track the location of system components can increase the accuracy of component inventories. Such capability may help organizations rapidly identify the location and responsible individuals of system components that have been compromised, breached, or are otherwise in need of mitigation actions. The use of tracking mechanisms can be coordinated with senior agency officials for privacy if there are implications that affect individual privacy.

==== CM-8(9) Assignment of Components to Systems[[cm-8-9]]

===== Control
(a) Assign system components to a system; and
(b) Receive an acknowledgement from _[Assignment: {cm-8-9_prm_1}]_ of this assignment.

===== Supplemental Guidance
System components that are not assigned to a system may be unmanaged, lack the required protection, and become an organizational vulnerability.

== CM-9 Configuration Management Plan[[cm-9]]

=== Control
Develop, document, and implement a configuration management plan for the system that:
a. Addresses roles, responsibilities, and configuration management processes and procedures;
b. Establishes a process for identifying configuration items throughout the system development life cycle and for managing the configuration of the configuration items;
c. Defines the configuration items for the system and places the configuration items under configuration management;
d. Is reviewed and approved by _[Assignment: {cm-9_prm_1}]_; and
e. Protects the configuration management plan from unauthorized disclosure and modification.

=== Supplemental Guidance
Configuration management activities occur throughout the system development life cycle. As such, there are developmental configuration management activities (e.g., the control of code and software libraries) and operational configuration management activities (e.g., control of installed components and how the components are configured). Configuration management plans satisfy the requirements in configuration management policies while being tailored to individual systems. Configuration management plans define processes and procedures for how configuration management is used to support system development life cycle activities.
Configuration management plans are generated during the development and acquisition stage of the system development life cycle. The plans describe how to advance changes through change management processes; update configuration settings and baselines; maintain component inventories; control development, test, and operational environments; and develop, release, and update key documents.
Organizations can employ templates to help ensure the consistent and timely development and implementation of configuration management plans. Templates can represent a configuration management plan for the organization with subsets of the plan implemented on a system by system basis. Configuration management approval processes include the designation of key stakeholders responsible for reviewing and approving proposed changes to systems, and personnel who conduct security and privacy impact analyses prior to the implementation of changes to the systems. Configuration items are the system components, such as the hardware, software, firmware, and documentation to be configuration-managed. As systems continue through the system development life cycle, new configuration items may be identified, and some existing configuration items may no longer need to be under configuration control.

=== References
https://doi.org/10.6028/NIST.SP.800-128[SP 800-128]

=== Control Enhancements
==== CM-9(1) Assignment of Responsibility[[cm-9-1]]

===== Control
Assign responsibility for developing the configuration management process to organizational personnel that are not directly involved in system development.

===== Supplemental Guidance
In the absence of dedicated configuration management teams assigned within organizations, system developers may be tasked with developing configuration management processes using personnel who are not directly involved in system development or system integration. This separation of duties ensures that organizations establish and maintain a sufficient degree of independence between the system development and integration processes and configuration management processes to facilitate quality control and more effective oversight.

== CM-10 Software Usage Restrictions[[cm-10]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2022-11-01

|===

=== Control
a. Use software and associated documentation in accordance with contract agreements and copyright laws;
b. Track the use of software and associated documentation protected by quantity licenses to control copying and distribution; and
c. Control and document the use of peer-to-peer file sharing technology to ensure that this capability is not used for the unauthorized distribution, display, performance, or reproduction of copyrighted work.

=== TAMUS Implementation Details
The System member ensures software installed on System-owned or -managed information systems is used in accordance with the applicable software license(s) and understands unauthorized or unlicensed use of software is regarded as a serious matter subject to disciplinary action.

=== Supplemental Guidance
Software license tracking can be accomplished by manual or automated methods, depending on organizational needs. Examples of contract agreements include software license agreements and non-disclosure agreements.


=== Control Enhancements
==== CM-10(1) Open-source Software[[cm-10-1]]

===== Control
Establish the following restrictions on the use of open-source software: _[Assignment: {cm-10-1_prm_1}]_.

===== Supplemental Guidance
Open-source software refers to software that is available in source code form. Certain software rights normally reserved for copyright holders are routinely provided under software license agreements that permit individuals to study, change, and improve the software. From a security perspective, the major advantage of open-source software is that it provides organizations with the ability to examine the source code. In some cases, there is an online community associated with the software that inspects, tests,  updates, and reports on issues found in software on an ongoing basis. However, remediating vulnerabilities in open-source software may be problematic. There may also be licensing issues associated with open-source software, including the constraints on derivative use of such software. Open-source software that is available only in binary form may increase the level of risk in using such software.

== CM-11 User-installed Software[[cm-11]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2022-11-01

|===

=== Control
a. Establish _[Assignment: {cm-11_prm_1}]_ governing the installation of software by users;
b. Enforce software installation policies through the following methods: _[Assignment: {cm-11_prm_2}]_; and
c. Monitor policy compliance _[Assignment: {cm-11_prm_3}]_.

=== Supplemental Guidance
If provided the necessary privileges, users can install software in organizational systems. To maintain control over the software installed, organizations identify permitted and prohibited actions regarding software installation. Permitted software installations include updates and security patches to existing software and downloading new applications from organization-approved 


=== Control Enhancements
==== CM-11(1) Alerts for Unauthorized Installations[[cm-11-1]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:cm.adoc#cm-8-3[CM-8.3]

==== CM-11(2) Software Installation with Privileged Status[[cm-11-2]]

===== Control
Allow user installation of software only with explicit privileged status.

===== Supplemental Guidance
Privileged status can be obtained, for example, by serving in the role of system administrator.

==== CM-11(3) Automated Enforcement and Monitoring[[cm-11-3]]

===== Control
Enforce and monitor compliance with software installation policies using _[Assignment: {cm-11-3_prm_1}]_.

===== Supplemental Guidance
Organizations enforce and monitor compliance with software installation policies using automated mechanisms to more quickly detect and respond to unauthorized software installation which can be an indicator of an internal or external hostile attack.

== CM-12 Information Location[[cm-12]]

=== Control
a. Identify and document the location of _[Assignment: {cm-12_prm_1}]_ and the specific system components on which the information is processed and stored;
b. Identify and document the users who have access to the system and system components where the information is processed and stored; and
c. Document changes to the location (i.e., system or system components) where the information is processed and stored.

=== Supplemental Guidance
Information location addresses the need to understand where information is being processed and stored. Information location includes identifying where specific information types and information reside in system components and how information is being processed so that information flow can be understood and adequate protection and policy management provided for such information and system components. The security category of the information is also a factor in determining the controls necessary to protect the information and the system component where the information resides (see 

=== References
https://doi.org/10.6028/NIST.FIPS.199[FIPS 199], https://doi.org/10.6028/NIST.SP.800-60v1r1[SP 800-60-1], https://doi.org/10.6028/NIST.SP.800-60v2r1[SP 800-60-2]

=== Control Enhancements
==== CM-12(1) Automated Tools to Support Information Location[[cm-12-1]]

===== Control
Use automated tools to identify _[Assignment: {cm-12-1_prm_1}]_ on _[Assignment: {cm-12-1_prm_2}]_ to ensure controls are in place to protect organizational information and individual privacy.

===== Supplemental Guidance
The use of automated tools helps to increase the effectiveness and efficiency of the information location capability implemented within the system. Automation also helps organizations manage the data produced during information location activities and share such information across the organization. The output of automated information location tools can be used to guide and inform system architecture and design decisions.

== CM-13 Data Action Mapping[[cm-13]]

=== Control
Develop and document a map of system data actions.

=== Supplemental Guidance
Data actions are system operations that process personally identifiable information. The processing of such information encompasses the full information life cycle, which includes collection, generation, transformation, use, disclosure, retention, and disposal. A map of system data actions includes discrete data actions, elements of personally identifiable information being processed in the data actions, system components involved in the data actions, and the owners or operators of the system components. Understanding what personally identifiable information is being processed (e.g., the sensitivity of the personally identifiable information), how personally identifiable information is being processed (e.g., if the data action is visible to the individual or is processed in another part of the system), and by whom (e.g., individuals may have different privacy perceptions based on the entity that is processing the personally identifiable information) provides a number of contextual factors that are important to assessing the degree of privacy risk created by the system. Data maps can be illustrated in different ways, and the level of detail may vary based on the mission and business needs of the organization. The data map may be an overlay of any system design artifact that the organization is using. The development of this map may necessitate coordination between the privacy and security programs regarding the covered data actions and the components that are identified as part of the system.


== CM-14 Signed Components[[cm-14]]

=== Control
Prevent the installation of _[Assignment: {cm-14_prm_1}]_ without verification that the component has been digitally signed using a certificate that is recognized and approved by the organization.

=== Supplemental Guidance
Software and firmware components prevented from installation unless signed with recognized and approved certificates include software and firmware version updates, patches, service packs, device drivers, and basic input/output system updates. Organizations can identify applicable software and firmware components by type, by specific items, or a combination of both. Digital signatures and organizational verification of such signatures is a method of code authentication.

=== References
https://doi.org/10.6028/NIST.IR.8062[IR 8062]

