= Identification and Authentication
:toc:
:toclevels: 1
:ia-1_prm_1: organization-defined personnel or roles
:ia-1_prm_2: one-or-more: Organization-level, Mission/business process-level, System-level
:ia-1_prm_3: organization-defined official
:ia-1_prm_4: organization-defined frequency
:ia-1_prm_5: organization-defined events
:ia-1_prm_6: organization-defined frequency
:ia-1_prm_7: organization-defined events
:ia-2-6_prm_1: one-or-more: local, network, remote
:ia-2-6_prm_2: one-or-more: privileged accounts, non-privileged accounts
:ia-2-6_prm_3: organization-defined strength of mechanism requirements
:ia-2-8_prm_1: one-or-more: privileged accounts, non-privileged accounts
:ia-2-10_prm_1: organization-defined system accounts and services
:ia-2-13_prm_1: organization-defined conditions
:ia-2-13_prm_2: organization-defined out-of-band authentication
:ia-3_prm_1: organization-defined devices and/or types of devices
:ia-3_prm_2: one-or-more: local, remote, network
:ia-3-1_prm_1: organization-defined devices and/or types of devices
:ia-3-1_prm_2: one-or-more: local, remote, network
:ia-3-3_prm_1: organization-defined lease information and lease duration
:ia-3-4_prm_1: organization-defined configuration management process
:ia-4_prm_1: organization-defined personnel or roles
:ia-4_prm_2: organization-defined time period
:ia-4-4_prm_1: organization-defined characteristic identifying individual status
:ia-4-5_prm_1: organization-defined dynamic identifier policy
:ia-4-6_prm_1: organization-defined external organizations
:ia-4-9_prm_1: organization-defined protected central storage
:ia-5_prm_1: organization-defined time period by authenticator type
:ia-5_prm_2: organization-defined events
:ia-5-1_prm_1: organization-defined frequency
:ia-5-1_prm_2: organization-defined composition and complexity rules
:ia-5-8_prm_1: organization-defined security controls
:ia-5-9_prm_1: organization-defined external organizations
:ia-5-10_prm_1: organization-defined binding rules
:ia-5-12_prm_1: organization-defined biometric quality requirements
:ia-5-13_prm_1: organization-defined time period
:ia-5-16_prm_1: organization-defined types of and/or specific authenticators
:ia-5-16_prm_2: in person, by a trusted external party
:ia-5-16_prm_3: organization-defined registration authority
:ia-5-16_prm_4: organization-defined personnel or roles
:ia-5-18_prm_1: organization-defined password managers
:ia-5-18_prm_2: organization-defined controls
:ia-8-4_prm_1: organization-defined identity management profiles
:ia-8-5_prm_1: organization-defined policy
:ia-8-6_prm_1: organization-defined measures
:ia-9_prm_1: organization-defined system services and applications
:ia-10_prm_1: organization-defined supplemental authentication techniques or mechanisms
:ia-10_prm_2: organization-defined circumstances or situations
:ia-11_prm_1: organization-defined circumstances or situations requiring re-authentication
:ia-12-3_prm_1: organizational defined methods of validation and verification
:ia-12-5_prm_1: registration code, notice of proofing
:ia-12-6_prm_1: organization-defined identity assurance level

== IA-1 Policy and Procedures[[ia-1]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Develop, document, and disseminate to _[Assignment: {ia-1_prm_1}]_:
1. _[Assignment: {ia-1_prm_2}]_ identification and authentication policy that:
(a) Addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance; and
(b) Is consistent with applicable laws, executive orders, directives, regulations, policies, standards, and guidelines; and
2. Procedures to facilitate the implementation of the identification and authentication policy and the associated identification and authentication controls;
b. Designate an _[Assignment: {ia-1_prm_3}]_ to manage the development, documentation, and dissemination of the identification and authentication policy and procedures; and
c. Review and update the current identification and authentication:
1. Policy _[Assignment: {ia-1_prm_4}]_ and following _[Assignment: {ia-1_prm_5}]_; and
2. Procedures _[Assignment: {ia-1_prm_6}]_ and following _[Assignment: {ia-1_prm_7}]_.

=== Supplemental Guidance
Identification and authentication policy and procedures address the controls in the IA family that are implemented within systems and organizations. The risk management strategy is an important factor in establishing such policies and procedures. Policies and procedures contribute to security and privacy assurance. Therefore, it is important that security and privacy programs collaborate on the development of identification and authentication policy and procedures. Security and privacy program policies and procedures at the organization level are preferable, in general, and may obviate the need for mission- or system-specific policies and procedures. The policy can be included as part of the general security and privacy policy or be represented by multiple policies that reflect the complex nature of organizations. Procedures can be established for security and privacy programs, for mission or business processes, and for systems, if needed. Procedures describe how the policies or controls are implemented and can be directed at the individual or role that is the object of the procedure. Procedures can be documented in system security and privacy plans or in one or more separate documents. Events that may precipitate an update to identification and authentication policy and procedures include assessment or audit findings, security incidents or breaches, or changes in applicable laws, executive orders, directives, regulations, policies, standards, and guidelines. Simply restating controls does not constitute an organizational policy or procedure.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.FIPS.201-2[FIPS 201-2], https://doi.org/10.6028/NIST.SP.800-12r1[SP 800-12], https://doi.org/10.6028/NIST.SP.800-30r1[SP 800-30], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-63-3[SP 800-63-3], https://doi.org/10.6028/NIST.SP.800-73-4[SP 800-73-4], https://doi.org/10.6028/NIST.SP.800-76-2[SP 800-76-2], https://doi.org/10.6028/NIST.SP.800-78-4[SP 800-78-4], https://doi.org/10.6028/NIST.SP.800-100[SP 800-100], https://doi.org/10.6028/NIST.IR.7874[IR 7874]

== IA-2 Identification and Authentication (organizational Users)[[ia-2]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2022-11-01

|===

=== Control
Uniquely identify and authenticate organizational users and associate that unique identification with processes acting on behalf of those users.

=== Supplemental Guidance
Organizations can satisfy the identification and authentication requirements by complying with the requirements in 
Organizations employ passwords, physical authenticators, or biometrics to authenticate user identities or, in the case of multi-factor authentication, some combination thereof. Access to organizational systems is defined as either local access or network access. Local access is any access to organizational systems by users or processes acting on behalf of users, where access is obtained through direct connections without the use of networks. Network access is access to organizational systems by users (or processes acting on behalf of users) where access is obtained through network connections (i.e., nonlocal accesses). Remote access is a type of network access that involves communication through external networks. Internal networks include local area networks and wide area networks.
The use of encrypted virtual private networks for network connections between organization-controlled endpoints and non-organization-controlled endpoints may be treated as internal networks with respect to protecting the confidentiality and integrity of information traversing the network. Identification and authentication requirements for non-organizational users are described in 

=== References
https://doi.org/10.6028/NIST.FIPS.140-3[FIPS 140-3], https://doi.org/10.6028/NIST.FIPS.201-2[FIPS 201-2], https://doi.org/10.6028/NIST.FIPS.202[FIPS 202], https://doi.org/10.6028/NIST.SP.800-63-3[SP 800-63-3], https://doi.org/10.6028/NIST.SP.800-73-4[SP 800-73-4], https://doi.org/10.6028/NIST.SP.800-76-2[SP 800-76-2], https://doi.org/10.6028/NIST.SP.800-78-4[SP 800-78-4], https://doi.org/10.6028/NIST.SP.800-79-2[SP 800-79-2], https://doi.org/10.6028/NIST.SP.800-156[SP 800-156], https://doi.org/10.6028/NIST.SP.800-166[SP 800-166], https://doi.org/10.6028/NIST.IR.7539[IR 7539], https://doi.org/10.6028/NIST.IR.7676[IR 7676], https://doi.org/10.6028/NIST.IR.7817[IR 7817], https://doi.org/10.6028/NIST.IR.7849[IR 7849], https://doi.org/10.6028/NIST.IR.7870[IR 7870], https://doi.org/10.6028/NIST.IR.7874[IR 7874], https://doi.org/10.6028/NIST.IR.7966[IR 7966]

=== Control Enhancements
==== IA-2(1) Multi-factor Authentication to Privileged Accounts[[ia-2-1]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

===== Control
Implement multi-factor authentication for access to privileged accounts.

===== Supplemental Guidance
Multi-factor authentication requires the use of two or more different factors to achieve authentication. The authentication factors are defined as follows: something you know (e.g., a personal identification number [PIN]), something you have (e.g., a physical authenticator such as a cryptographic private key), or something you are (e.g., a biometric). Multi-factor authentication solutions that feature physical authenticators include hardware authenticators that provide time-based or challenge-response outputs and smart cards such as the U.S. Government Personal Identity Verification (PIV) card or the Department of Defense (DoD) Common Access Card (CAC). In addition to authenticating users at the system level (i.e., at logon), organizations may employ authentication mechanisms at the application level, at their discretion, to provide increased security. Regardless of the type of access (i.e., local, network, remote), privileged accounts are authenticated using multi-factor options appropriate for the level of risk. Organizations can add additional security measures, such as additional or more rigorous authentication mechanisms, for specific types of access.

==== IA-2(2) Multi-factor Authentication to Non-privileged Accounts[[ia-2-2]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

===== Control
Implement multi-factor authentication for access to non-privileged accounts.

===== Supplemental Guidance
Multi-factor authentication requires the use of two or more different factors to achieve authentication. The authentication factors are defined as follows: something you know (e.g., a personal identification number [PIN]), something you have (e.g., a physical authenticator such as a cryptographic private key), or something you are (e.g., a biometric). Multi-factor authentication solutions that feature physical authenticators include hardware authenticators that provide time-based or challenge-response outputs and smart cards such as the U.S. Government Personal Identity Verification card or the DoD Common Access Card. In addition to authenticating users at the system level, organizations may also employ authentication mechanisms at the application level, at their discretion, to provide increased information security. Regardless of the type of access (i.e., local, network, remote), non-privileged accounts are authenticated using multi-factor options appropriate for the level of risk. Organizations can provide additional security measures, such as additional or more rigorous authentication mechanisms, for specific types of access.

==== IA-2(3) Local Access to Privileged Accounts[[ia-2-3]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ia.adoc#ia-2-1[IA-2.1]

==== IA-2(4) Local Access to Non-privileged Accounts[[ia-2-4]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ia.adoc#ia-2-2[IA-2.2]

==== IA-2(5) Individual Authentication with Group Authentication[[ia-2-5]]

===== Control
When shared accounts or authenticators are employed, require users to be individually authenticated before granting access to the shared accounts or resources.

===== Supplemental Guidance
Individual authentication prior to shared group authentication mitigates the risk of using group accounts or authenticators.

==== IA-2(6) Access to Accounts -separate Device[[ia-2-6]]

===== Control
Implement multi-factor authentication for _[Assignment: {ia-2-6_prm_1}]_ access to _[Assignment: {ia-2-6_prm_2}]_ such that:
(a) One of the factors is provided by a device separate from the system gaining access; and
(b) The device meets _[Assignment: {ia-2-6_prm_3}]_.

===== Supplemental Guidance
The purpose of requiring a device that is separate from the system to which the user is attempting to gain access for one of the factors during multi-factor authentication is to reduce the likelihood of compromising authenticators or credentials stored on the system. Adversaries may be able to compromise such authenticators or credentials and subsequently impersonate authorized users. Implementing one of the factors on a separate device (e.g., a hardware token), provides a greater strength of mechanism and an increased level of assurance in the authentication process.

==== IA-2(7) Network Access to Non-privileged Accounts - Separate Device[[ia-2-7]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ia.adoc#ia-2-6[IA-2.6]

==== IA-2(8) Access to Accounts - Replay Resistant[[ia-2-8]]

===== Control
Implement replay-resistant authentication mechanisms for access to _[Assignment: {ia-2-8_prm_1}]_.

===== Supplemental Guidance
Authentication processes resist replay attacks if it is impractical to achieve successful authentications by replaying previous authentication messages. Replay-resistant techniques include protocols that use nonces or challenges such as time synchronous or cryptographic authenticators.

==== IA-2(9) Network Access to Non-privileged Accounts - Replay Resistant[[ia-2-9]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ia.adoc#ia-2-8[IA-2.8]

==== IA-2(10) Single Sign-on[[ia-2-10]]

===== Control
Provide a single sign-on capability for _[Assignment: {ia-2-10_prm_1}]_.

===== Supplemental Guidance
Single sign-on enables users to log in once and gain access to multiple system resources. Organizations consider the operational efficiencies provided by single sign-on capabilities with the risk introduced by allowing access to multiple systems via a single authentication event. Single sign-on can present opportunities to improve system security, for example by providing the ability to add multi-factor authentication for applications and systems (existing and new) that may not be able to natively support multi-factor authentication.

==== IA-2(11) Remote Access - Separate Device[[ia-2-11]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ia.adoc#ia-2-6[IA-2.6]

==== IA-2(12) Acceptance of PIV Credentials[[ia-2-12]]

===== Control
Accept and electronically verify Personal Identity Verification-compliant credentials.

===== Supplemental Guidance
Acceptance of Personal Identity Verification (PIV)-compliant credentials applies to organizations implementing logical access control and physical access control systems. PIV-compliant credentials are those credentials issued by federal agencies that conform to FIPS Publication 201 and supporting guidance documents. The adequacy and reliability of PIV card issuers are authorized using 

==== IA-2(13) Out-of-band Authentication[[ia-2-13]]

===== Control
Implement the following out-of-band authentication mechanisms under _[Assignment: {ia-2-13_prm_1}]_: _[Assignment: {ia-2-13_prm_2}]_.

===== Supplemental Guidance
Out-of-band authentication refers to the use of two separate communication paths to identify and authenticate users or devices to an information system. The first path (i.e., the in-band path) is used to identify and authenticate users or devices and is generally the path through which information flows. The second path (i.e., the out-of-band path) is used to independently verify the authentication and/or requested action. For example, a user authenticates via a notebook computer to a remote server to which the user desires access and requests some action of the server via that communication path. Subsequently, the server contacts the user via the user's cell phone to verify that the requested action originated from the user. The user may confirm the intended action to an individual on the telephone or provide an authentication code via the telephone. Out-of-band authentication can be used to mitigate actual or suspected 

== IA-3 Device Identification and Authentication[[ia-3]]

=== Control
Uniquely identify and authenticate _[Assignment: {ia-3_prm_1}]_ before establishing a _[Assignment: {ia-3_prm_2}]_ connection.

=== Supplemental Guidance
Devices that require unique device-to-device identification and authentication are defined by type, device, or a combination of type and device. Organization-defined device types include devices that are not owned by the organization. Systems use shared known information (e.g., Media Access Control [MAC], Transmission Control Protocol/Internet Protocol [TCP/IP] addresses) for device identification or organizational authentication solutions (e.g., Institute of Electrical and Electronics Engineers (IEEE) 802.1x and Extensible Authentication Protocol [EAP], RADIUS server with EAP-Transport Layer Security [TLS] authentication, Kerberos) to identify and authenticate devices on local and wide area networks. Organizations determine the required strength of authentication mechanisms based on the security categories of systems and mission or business requirements. Because of the challenges of implementing device authentication on a large scale, organizations can restrict the application of the control to a limited number/type of devices based on mission or business needs.


=== Control Enhancements
==== IA-3(1) Cryptographic Bidirectional Authentication[[ia-3-1]]

===== Control
Authenticate _[Assignment: {ia-3-1_prm_1}]_ before establishing _[Assignment: {ia-3-1_prm_2}]_ connection using bidirectional authentication that is cryptographically based.

===== Supplemental Guidance
A local connection is a connection with a device that communicates without the use of a network. A network connection is a connection with a device that communicates through a network. A remote connection is a connection with a device that communicates through an external network. Bidirectional authentication provides stronger protection to validate the identity of other devices for connections that are of greater risk.

==== IA-3(2) Cryptographic Bidirectional Network Authentication[[ia-3-2]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ia.adoc#ia-3-1[IA-3.1]

==== IA-3(3) Dynamic Address Allocation[[ia-3-3]]

===== Control
(a) Where addresses are allocated dynamically, standardize dynamic address allocation lease information and the lease duration assigned to devices in accordance with _[Assignment: {ia-3-3_prm_1}]_; and
(b) Audit lease information when assigned to a device.

===== Supplemental Guidance
The Dynamic Host Configuration Protocol (DHCP) is an example of a means by which clients can dynamically receive network address assignments.

==== IA-3(4) Device Attestation[[ia-3-4]]

===== Control
Handle device identification and authentication based on attestation by _[Assignment: {ia-3-4_prm_1}]_.

===== Supplemental Guidance
Device attestation refers to the identification and authentication of a device based on its configuration and known operating state. Device attestation can be determined via a cryptographic hash of the device. If device attestation is the means of identification and authentication, then it is important that patches and updates to the device are handled via a configuration management process such that the patches and updates are done securely and do not disrupt identification and authentication to other devices.

== IA-4 Identifier Management[[ia-4]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
Manage system identifiers by:
a. Receiving authorization from _[Assignment: {ia-4_prm_1}]_ to assign an individual, group, role, service, or device identifier;
b. Selecting an identifier that identifies an individual, group, role, service, or device;
c. Assigning the identifier to the intended individual, group, role, service, or device; and
d. Preventing reuse of identifiers for _[Assignment: {ia-4_prm_2}]_.

=== State Implementation Details
A user's access authorization shall be appropriately modified or removed when the user's employment or job responsibilities within the state organization change.

=== Supplemental Guidance
Common device identifiers include Media Access Control (MAC) addresses, Internet Protocol (IP) addresses, or device-unique token identifiers. The management of individual identifiers is not applicable to shared system accounts. Typically, individual identifiers are the usernames of the system accounts assigned to those individuals. In such instances, the account management activities of 

=== References
https://doi.org/10.6028/NIST.FIPS.201-2[FIPS 201-2], https://doi.org/10.6028/NIST.SP.800-63-3[SP 800-63-3], https://doi.org/10.6028/NIST.SP.800-73-4[SP 800-73-4], https://doi.org/10.6028/NIST.SP.800-76-2[SP 800-76-2], https://doi.org/10.6028/NIST.SP.800-78-4[SP 800-78-4]

=== Control Enhancements
==== IA-4(1) Prohibit Account Identifiers as Public Identifiers[[ia-4-1]]

===== Control
Prohibit the use of system account identifiers that are the same as public identifiers for individual accounts.

===== Supplemental Guidance
Prohibiting account identifiers as public identifiers applies to any publicly disclosed account identifier used for communication such as, electronic mail and instant messaging. Prohibiting the use of systems account identifiers that are the same as some public identifier, such as the individual identifier section of an electronic mail address, makes it more difficult for adversaries to guess user identifiers. Prohibiting account identifiers as public identifiers without the implementation of other supporting controls only complicates guessing of identifiers. Additional protections are required for authenticators and credentials to protect the account.

==== IA-4(2) Supervisor Authorization[[ia-4-2]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ia.adoc#ia-12-1[IA-12.1]

==== IA-4(3) Multiple Forms of Certification[[ia-4-3]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ia.adoc#ia-12-2[IA-12.2]

==== IA-4(4) Identify User Status[[ia-4-4]]

===== Control
Manage individual identifiers by uniquely identifying each individual as _[Assignment: {ia-4-4_prm_1}]_.

===== Supplemental Guidance
Characteristics that identify the status of individuals include contractors, foreign nationals, and non-organizational users. Identifying the status of individuals by these characteristics provides additional information about the people with whom organizational personnel are communicating. For example, it might be useful for a government employee to know that one of the individuals on an email message is a contractor.

==== IA-4(5) Dynamic Management[[ia-4-5]]

===== Control
Manage individual identifiers dynamically in accordance with _[Assignment: {ia-4-5_prm_1}]_.

===== Supplemental Guidance
In contrast to conventional approaches to identification that presume static accounts for preregistered users, many distributed systems establish identifiers at runtime for entities that were previously unknown. When identifiers are established at runtime for previously unknown entities, organizations can anticipate and provision for the dynamic establishment of identifiers. Pre-established trust relationships and mechanisms with appropriate authorities to validate credentials and related identifiers are essential.

==== IA-4(6) Cross-organization Management[[ia-4-6]]

===== Control
Coordinate with the following external organizations for cross-organization management of identifiers: _[Assignment: {ia-4-6_prm_1}]_.

===== Supplemental Guidance
Cross-organization identifier management provides the capability to identify individuals, groups, roles, or devices when conducting cross-organization activities involving the processing, storage, or transmission of information.

==== IA-4(7) In-person Registration[[ia-4-7]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ia.adoc#ia-12-4[IA-12.4]

==== IA-4(8) Pairwise Pseudonymous Identifiers[[ia-4-8]]

===== Control
Generate pairwise pseudonymous identifiers.

===== Supplemental Guidance
A pairwise pseudonymous identifier is an opaque unguessable subscriber identifier generated by an identity provider for use at a specific individual relying party. Generating distinct pairwise pseudonymous identifiers with no identifying information about a subscriber discourages subscriber activity tracking and profiling beyond the operational requirements established by an organization. The pairwise pseudonymous identifiers are unique to each relying party except in situations where relying parties can show a demonstrable relationship justifying an operational need for correlation, or all parties consent to being correlated in such a manner.

==== IA-4(9) Attribute Maintenance and Protection[[ia-4-9]]

===== Control
Maintain the attributes for each uniquely identified individual, device, or service in _[Assignment: {ia-4-9_prm_1}]_.

===== Supplemental Guidance
For each of the entities covered in 

== IA-5 Authenticator Management[[ia-5]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
Manage system authenticators by:
a. Verifying, as part of the initial authenticator distribution, the identity of the individual, group, role, service, or device receiving the authenticator;
b. Establishing initial authenticator content for any authenticators issued by the organization;
c. Ensuring that authenticators have sufficient strength of mechanism for their intended use;
d. Establishing and implementing administrative procedures for initial authenticator distribution, for lost or compromised or damaged authenticators, and for revoking authenticators;
e. Changing default authenticators prior to first use;
f. Changing or refreshing authenticators _[Assignment: {ia-5_prm_1}]_ or when _[Assignment: {ia-5_prm_2}]_ occur;
g. Protecting authenticator content from unauthorized disclosure and modification;
h. Requiring individuals to take, and having devices implement, specific controls to protect authenticators; and
i. Changing authenticators for group or role accounts when membership to those accounts changes.

=== Supplemental Guidance
Authenticators include passwords, cryptographic devices, biometrics, certificates, one-time password devices, and ID badges. Device authenticators include certificates and passwords. Initial authenticator content is the actual content of the authenticator (e.g., the initial password). In contrast, the requirements for authenticator content contain specific criteria or characteristics (e.g., minimum password length). Developers may deliver system components with factory default authentication credentials (i.e., passwords) to allow for initial installation and configuration. Default authentication credentials are often well known, easily discoverable, and present a significant risk. The requirement to protect individual authenticators may be implemented via control 
Systems support authenticator management by organization-defined settings and restrictions for various authenticator characteristics (e.g., minimum password length, validation time window for time synchronous one-time tokens, and number of allowed rejections during the verification stage of biometric authentication). Actions can be taken to safeguard individual authenticators, including maintaining possession of authenticators, not sharing authenticators with others, and immediately reporting lost, stolen, or compromised authenticators. Authenticator management includes issuing and revoking authenticators for temporary access when no longer needed.

=== References
https://doi.org/10.6028/NIST.FIPS.140-3[FIPS 140-3], https://doi.org/10.6028/NIST.FIPS.180-4[FIPS 180-4], https://doi.org/10.6028/NIST.FIPS.201-2[FIPS 201-2], https://doi.org/10.6028/NIST.FIPS.202[FIPS 202], https://doi.org/10.6028/NIST.SP.800-63-3[SP 800-63-3], https://doi.org/10.6028/NIST.SP.800-73-4[SP 800-73-4], https://doi.org/10.6028/NIST.SP.800-76-2[SP 800-76-2], https://doi.org/10.6028/NIST.SP.800-78-4[SP 800-78-4], https://doi.org/10.6028/NIST.IR.7539[IR 7539], https://doi.org/10.6028/NIST.IR.7817[IR 7817], https://doi.org/10.6028/NIST.IR.7849[IR 7849], https://doi.org/10.6028/NIST.IR.7870[IR 7870], https://doi.org/10.6028/NIST.IR.8040[IR 8040]

=== Control Enhancements
==== IA-5(1) Password-based Authentication[[ia-5-1]]

===== Control
For password-based authentication:
(a) Maintain a list of commonly-used, expected, or compromised passwords and update the list _[Assignment: {ia-5-1_prm_1}]_ and when organizational passwords are suspected to have been compromised directly or indirectly;
(b) Verify, when users create or update passwords, that the passwords are not found on the list of commonly-used, expected, or compromised passwords in IA-5(1)(a);
(c) Transmit passwords only over cryptographically-protected channels;
(d) Store passwords using an approved salted key derivation function, preferably using a keyed hash;
(e) Require immediate selection of a new password upon account recovery;
(f) Allow user selection of long passwords and passphrases, including spaces and all printable characters;
(g) Employ automated tools to assist the user in selecting strong password authenticators; and
(h) Enforce the following composition and complexity rules: _[Assignment: {ia-5-1_prm_2}]_.

===== Supplemental Guidance
Password-based authentication applies to passwords regardless of whether they are used in single-factor or multi-factor authentication. Long passwords or passphrases are preferable over shorter passwords. Enforced composition rules provide marginal security benefits while decreasing usability. However, organizations may choose to establish certain rules for password generation (e.g., minimum character length for long passwords) under certain circumstances and can enforce this requirement in IA-5(1)(h). Account recovery can occur, for example, in situations when a password is forgotten. Cryptographically protected passwords include salted one-way cryptographic hashes of passwords. The list of commonly used, compromised, or expected passwords includes passwords obtained from previous breach corpuses, dictionary words, and repetitive or sequential characters. The list includes context-specific words, such as the name of the service, username, and derivatives thereof.

==== IA-5(2) Public Key-based Authentication[[ia-5-2]]

===== Control
(a) For public key-based authentication:
(1) Enforce authorized access to the corresponding private key; and
(2) Map the authenticated identity to the account of the individual or group; and
(b) When public key infrastructure (PKI) is used:
(1) Validate certificates by constructing and verifying a certification path to an accepted trust anchor, including checking certificate status information; and
(2) Implement a local cache of revocation data to support path discovery and validation.

===== Supplemental Guidance
Public key cryptography is a valid authentication mechanism for individuals, machines, and devices. For PKI solutions, status information for certification paths includes certificate revocation lists or certificate status protocol responses. For PIV cards, certificate validation involves the construction and verification of a certification path to the Common Policy Root trust anchor, which includes certificate policy processing. Implementing a local cache of revocation data to support path discovery and validation also supports system availability in situations where organizations are unable to access revocation information via the network.

==== IA-5(3) In-person or Trusted External Party Registration[[ia-5-3]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ia.adoc#ia-12-4[IA-12.4]

==== IA-5(4) Automated Support for Password Strength Determination[[ia-5-4]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ia.adoc#ia-5-1[IA-5.1]

==== IA-5(5) Change Authenticators Prior to Delivery[[ia-5-5]]

===== Control
Require developers and installers of system components to provide unique authenticators or change default authenticators prior to delivery and installation.

===== Supplemental Guidance
Changing authenticators prior to the delivery and installation of system components extends the requirement for organizations to change default authenticators upon system installation by requiring developers and/or installers to provide unique authenticators or change default authenticators for system components prior to delivery and/or installation. However, it typically does not apply to developers of commercial off-the-shelf information technology products. Requirements for unique authenticators can be included in acquisition documents prepared by organizations when procuring systems or system components.

==== IA-5(6) Protection of Authenticators[[ia-5-6]]

===== Control
Protect authenticators commensurate with the security category of the information to which use of the authenticator permits access.

===== Supplemental Guidance
For systems that contain multiple security categories of information without reliable physical or logical separation between categories, authenticators used to grant access to the systems are protected commensurate with the highest security category of information on the systems. Security categories of information are determined as part of the security categorization process.

==== IA-5(7) No Embedded Unencrypted Static Authenticators[[ia-5-7]]

===== Control
Ensure that unencrypted static authenticators are not embedded in applications or other forms of static storage.

===== Supplemental Guidance
In addition to applications, other forms of static storage include access scripts and function keys. Organizations exercise caution when determining whether embedded or stored authenticators are in encrypted or unencrypted form. If authenticators are used in the manner stored, then those representations are considered unencrypted authenticators.

==== IA-5(8) Multiple System Accounts[[ia-5-8]]

===== Control
Implement _[Assignment: {ia-5-8_prm_1}]_ to manage the risk of compromise due to individuals having accounts on multiple systems.

===== Supplemental Guidance
When individuals have accounts on multiple systems and use the same authenticators such as passwords, there is the risk that a compromise of one account may lead to the compromise of other accounts. Alternative approaches include having different authenticators (passwords) on all systems, employing a single sign-on or federation mechanism, or using some form of one-time passwords on all systems. Organizations can also use rules of behavior (see 

==== IA-5(9) Federated Credential Management[[ia-5-9]]

===== Control
Use the following external organizations to federate credentials: _[Assignment: {ia-5-9_prm_1}]_.

===== Supplemental Guidance
Federation provides organizations with the capability to authenticate individuals and devices when conducting cross-organization activities involving the processing, storage, or transmission of information. Using a specific list of approved external organizations for authentication helps to ensure that those organizations are vetted and trusted.

==== IA-5(10) Dynamic Credential Binding[[ia-5-10]]

===== Control
Bind identities and authenticators dynamically using the following rules: _[Assignment: {ia-5-10_prm_1}]_.

===== Supplemental Guidance
Authentication requires some form of binding between an identity and the authenticator that is used to confirm the identity. In conventional approaches, binding is established by pre-provisioning both the identity and the authenticator to the system. For example, the binding between a username (i.e., identity) and a password (i.e., authenticator) is accomplished by provisioning the identity and authenticator as a pair in the system. New authentication techniques allow the binding between the identity and the authenticator to be implemented external to a system. For example, with smartcard credentials, the identity and authenticator are bound together on the smartcard. Using these credentials, systems can authenticate identities that have not been pre-provisioned, dynamically provisioning the identity after authentication. In these situations, organizations can anticipate the dynamic provisioning of identities. Pre-established trust relationships and mechanisms with appropriate authorities to validate identities and related credentials are essential.

==== IA-5(11) Hardware Token-based Authentication[[ia-5-11]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ia.adoc#ia-2-1[IA-2.1], xref:ia.adoc#ia-2-2[IA-2.2]

==== IA-5(12) Biometric Authentication Performance[[ia-5-12]]

===== Control
For biometric-based authentication, employ mechanisms that satisfy the following biometric quality requirements _[Assignment: {ia-5-12_prm_1}]_.

===== Supplemental Guidance
Unlike password-based authentication, which provides exact matches of user-input passwords to stored passwords, biometric authentication does not provide exact matches. Depending on the type of biometric and the type of collection mechanism, there is likely to be some divergence from the presented biometric and the stored biometric that serves as the basis for comparison. Matching performance is the rate at which a biometric algorithm correctly results in a match for a genuine user and rejects other users. Biometric performance requirements include the match rate, which reflects the accuracy of the biometric matching algorithm used by a system.

==== IA-5(13) Expiration of Cached Authenticators[[ia-5-13]]

===== Control
Prohibit the use of cached authenticators after _[Assignment: {ia-5-13_prm_1}]_.

===== Supplemental Guidance
Cached authenticators are used to authenticate to the local machine when the network is not available. If cached authentication information is out of date, the validity of the authentication information may be questionable.

==== IA-5(14) Managing Content of PKI Trust Stores[[ia-5-14]]

===== Control
For PKI-based authentication, employ an organization-wide methodology for managing the content of PKI trust stores installed across all platforms, including networks, operating systems, browsers, and applications.

===== Supplemental Guidance
An organization-wide methodology for managing the content of PKI trust stores helps improve the accuracy and currency of PKI-based authentication credentials across the organization.

==== IA-5(15) Gsa-approved Products and Services[[ia-5-15]]

===== Control
Use only General Services Administration-approved products and services for identity, credential, and access management.

===== Supplemental Guidance
General Services Administration (GSA)-approved products and services are products and services that have been approved through the GSA conformance program, where applicable, and posted to the GSA Approved Products List. GSA provides guidance for teams to design and build functional and secure systems that comply with Federal Identity, Credential, and Access Management (FICAM) policies, technologies, and implementation patterns.

==== IA-5(16) In-person or Trusted External Party Authenticator Issuance[[ia-5-16]]

===== Control
Require that the issuance of _[Assignment: {ia-5-16_prm_1}]_ be conducted _[Assignment: {ia-5-16_prm_2}]_ before _[Assignment: {ia-5-16_prm_3}]_ with authorization by _[Assignment: {ia-5-16_prm_4}]_.

===== Supplemental Guidance
Issuing authenticators in person or by a trusted external party enhances and reinforces the trustworthiness of the identity proofing process.

==== IA-5(17) Presentation Attack Detection for Biometric Authenticators[[ia-5-17]]

===== Control
Employ presentation attack detection mechanisms for biometric-based authentication.

===== Supplemental Guidance
Biometric characteristics do not constitute secrets. Such characteristics can be obtained by online web accesses, taking a picture of someone with a camera phone to obtain facial images with or without their knowledge, lifting from objects that someone has touched (e.g., a latent fingerprint), or capturing a high-resolution image (e.g., an iris pattern). Presentation attack detection technologies including liveness detection, can mitigate the risk of these types of attacks by making it difficult to produce artifacts intended to defeat the biometric sensor.

==== IA-5(18) Password Managers[[ia-5-18]]

===== Control
(a) Employ _[Assignment: {ia-5-18_prm_1}]_ to generate and manage passwords; and
(b) Protect the passwords using _[Assignment: {ia-5-18_prm_2}]_.

===== Supplemental Guidance
For systems where static passwords are employed, it is often a challenge to ensure that the passwords are suitably complex and that the same passwords are not employed on multiple systems. A password manager is a solution to this problem as it automatically generates and stores strong and different passwords for various accounts. A potential risk of using password managers is that adversaries can target the collection of passwords generated by the password manager. Therefore, the collection of passwords requires protection including encrypting the passwords (see 

== IA-6 Authentication Feedback[[ia-6]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2022-11-01

|===

=== Control
Obscure feedback of authentication information during the authentication process to protect the information from possible exploitation and use by unauthorized individuals.

=== Supplemental Guidance
Authentication feedback from systems does not provide information that would allow unauthorized individuals to compromise authentication mechanisms. For some types of systems, such as desktops or notebooks with relatively large monitors, the threat (referred to as shoulder surfing) may be significant. For other types of systems, such as mobile devices with small displays, the threat may be less significant and is balanced against the increased likelihood of typographic input errors due to small keyboards. Thus, the means for obscuring authentication feedback is selected accordingly. Obscuring authentication feedback includes displaying asterisks when users type passwords into input devices or displaying feedback for a very limited time before obscuring it.


== IA-7 Cryptographic Module Authentication[[ia-7]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2022-11-01

|===

=== Control
Implement mechanisms for authentication to a cryptographic module that meet the requirements of applicable laws, executive orders, directives, policies, regulations, standards, and guidelines for such authentication.

=== Supplemental Guidance
Authentication mechanisms may be required within a cryptographic module to authenticate an operator accessing the module and to verify that the operator is authorized to assume the requested role and perform services within that role.

=== References
https://doi.org/10.6028/NIST.FIPS.140-3[FIPS 140-3]

== IA-8 Identification and Authentication (non-organizational Users)[[ia-8]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2022-11-01

|===

=== Control
Uniquely identify and authenticate non-organizational users or processes acting on behalf of non-organizational users.

=== Supplemental Guidance
Non-organizational users include system users other than organizational users explicitly covered by 

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://www.idmanagement.gov/topics/fpki[FED PKI], https://doi.org/10.6028/NIST.FIPS.201-2[FIPS 201-2], https://doi.org/10.6028/NIST.SP.800-63-3[SP 800-63-3], https://doi.org/10.6028/NIST.SP.800-79-2[SP 800-79-2], https://doi.org/10.6028/NIST.SP.800-116r1[SP 800-116], https://doi.org/10.6028/NIST.IR.8062[IR 8062]

=== Control Enhancements
==== IA-8(1) Acceptance of PIV Credentials from Other Agencies[[ia-8-1]]

===== Control
Accept and electronically verify Personal Identity Verification-compliant credentials from other federal agencies.

===== Supplemental Guidance
Acceptance of Personal Identity Verification (PIV) credentials from other federal agencies applies to both logical and physical access control systems. PIV credentials are those credentials issued by federal agencies that conform to FIPS Publication 201 and supporting guidelines. The adequacy and reliability of PIV card issuers are addressed and authorized using 

==== IA-8(2) Acceptance of External Authenticators[[ia-8-2]]

===== Control
(a) Accept only external authenticators that are NIST-compliant; and
(b) Document and maintain a list of accepted external authenticators.

===== Supplemental Guidance
Acceptance of only NIST-compliant external authenticators applies to organizational systems that are accessible to the public (e.g., public-facing websites). External authenticators are issued by nonfederal government entities and are compliant with 

==== IA-8(3) Use of Ficam-approved Products[[ia-8-3]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ia.adoc#ia-8-2[IA-8.2]

==== IA-8(4) Use of Defined Profiles[[ia-8-4]]

===== Control
Conform to the following profiles for identity management _[Assignment: {ia-8-4_prm_1}]_.

===== Supplemental Guidance
Organizations define profiles for identity management based on open identity management standards. To ensure that open identity management standards are viable, robust, reliable, sustainable, and interoperable as documented, the Federal Government assesses and scopes the standards and technology implementations against applicable laws, executive orders, directives, policies, regulations, standards, and guidelines.

==== IA-8(5) Acceptance of PIV-I Credentials[[ia-8-5]]

===== Control
Accept and verify federated or PKI credentials that meet _[Assignment: {ia-8-5_prm_1}]_.

===== Supplemental Guidance
Acceptance of PIV-I credentials can be implemented by PIV, PIV-I, and other commercial or external identity providers. The acceptance and verification of PIV-I-compliant credentials apply to both logical and physical access control systems. The acceptance and verification of PIV-I credentials address nonfederal issuers of identity cards that desire to interoperate with United States Government PIV systems and that can be trusted by Federal Government-relying parties. The X.509 certificate policy for the Federal Bridge Certification Authority (FBCA) addresses PIV-I requirements. The PIV-I card is commensurate with the PIV credentials as defined in cited references. PIV-I credentials are the credentials issued by a PIV-I provider whose PIV-I certificate policy maps to the Federal Bridge PIV-I Certificate Policy. A PIV-I provider is cross-certified with the FBCA (directly or through another PKI bridge) with policies that have been mapped and approved as meeting the requirements of the PIV-I policies defined in the FBCA certificate policy.

==== IA-8(6) Disassociability[[ia-8-6]]

===== Control
Implement the following measures to disassociate user attributes or identifier assertion relationships among individuals, credential service providers, and relying parties: _[Assignment: {ia-8-6_prm_1}]_.

===== Supplemental Guidance
Federated identity solutions can create increased privacy risks due to the tracking and profiling of individuals. Using identifier mapping tables or cryptographic techniques to blind credential service providers and relying parties from each other or to make identity attributes less visible to transmitting parties can reduce these privacy risks.

== IA-9 Service Identification and Authentication[[ia-9]]

=== Control
Uniquely identify and authenticate _[Assignment: {ia-9_prm_1}]_ before establishing communications with devices, users, or other services or applications.

=== Supplemental Guidance
Services that may require identification and authentication include web applications using digital certificates or services or applications that query a database. Identification and authentication methods for system services and applications include information or code signing, provenance graphs, and electronic signatures that indicate the sources of services. Decisions regarding the validity of identification and authentication claims can be made by services separate from the services acting on those decisions. This can occur in distributed system architectures. In such situations, the identification and authentication decisions (instead of actual identifiers and authentication data) are provided to the services that need to act on those decisions.


=== Control Enhancements
==== IA-9(1) Information Exchange[[ia-9-1]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ia.adoc#ia-9[IA-9]

==== IA-9(2) Transmission of Decisions[[ia-9-2]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ia.adoc#ia-9[IA-9]

== IA-10 Adaptive Authentication[[ia-10]]

=== Control
Require individuals accessing the system to employ _[Assignment: {ia-10_prm_1}]_ under specific _[Assignment: {ia-10_prm_2}]_.

=== Supplemental Guidance
Adversaries may compromise individual authentication mechanisms employed by organizations and subsequently attempt to impersonate legitimate users. To address this threat, organizations may employ specific techniques or mechanisms and establish protocols to assess suspicious behavior. Suspicious behavior may include accessing information that individuals do not typically access as part of their duties, roles, or responsibilities; accessing greater quantities of information than individuals would routinely access; or attempting to access information from suspicious network addresses. When pre-established conditions or triggers occur, organizations can require individuals to provide additional authentication information. Another potential use for adaptive authentication is to increase the strength of mechanism based on the number or types of records being accessed. Adaptive authentication does not replace and is not used to avoid the use of multi-factor authentication mechanisms but can augment implementations of multi-factor authentication.

=== References
https://doi.org/10.6028/NIST.SP.800-63-3[SP 800-63-3]

== IA-11 Re-authentication[[ia-11]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
Require users to re-authenticate when _[Assignment: {ia-11_prm_1}]_.

=== TAMUS Implementation Details
The System member limits the lifetime of browser cookies used for binding authenticated sessions to System-owned or -managed information systems to no more than five (5) days.

=== Supplemental Guidance
In addition to the re-authentication requirements associated with device locks, organizations may require re-authentication of individuals in certain situations, including when roles, authenticators or credentials change, when security categories of systems change, when the execution of privileged functions occurs, after a fixed time period, or periodically.

=== References
https://doi.org/10.6028/NIST.SP.800-63b[NIST Special Publication 800-63B]

== IA-12 Identity Proofing[[ia-12]]

=== Control
a. Identity proof users that require accounts for logical access to systems based on appropriate identity assurance level requirements as specified in applicable standards and guidelines;
b. Resolve user identities to a unique individual; and
c. Collect, validate, and verify identity evidence.

=== Supplemental Guidance
Identity proofing is the process of collecting, validating, and verifying a user's identity information for the purposes of establishing credentials for accessing a system. Identity proofing is intended to mitigate threats to the registration of users and the establishment of their accounts. Standards and guidelines specifying identity assurance levels for identity proofing include 

=== References
https://doi.org/10.6028/NIST.FIPS.201-2[FIPS 201-2], https://doi.org/10.6028/NIST.SP.800-63-3[SP 800-63-3], https://doi.org/10.6028/NIST.SP.800-63a[SP 800-63A], https://doi.org/10.6028/NIST.SP.800-79-2[SP 800-79-2]

=== Control Enhancements
==== IA-12(1) Supervisor Authorization[[ia-12-1]]

===== Control
Require that the registration process to receive an account for logical access includes supervisor or sponsor authorization.

===== Supplemental Guidance
Including supervisor or sponsor authorization as part of the registration process provides an additional level of scrutiny to ensure that the user's management chain is aware of the account, the account is essential to carry out organizational missions and functions, and the user's privileges are appropriate for the anticipated responsibilities and authorities within the organization.

==== IA-12(2) Identity Evidence[[ia-12-2]]

===== Control
Require evidence of individual identification be presented to the registration authority.

===== Supplemental Guidance
Identity evidence, such as documentary evidence or a combination of documents and biometrics, reduces the likelihood of individuals using fraudulent identification to establish an identity or at least increases the work factor of potential adversaries. The forms of acceptable evidence are consistent with the risks to the systems, roles, and privileges associated with the user's account.

==== IA-12(3) Identity Evidence Validation and Verification[[ia-12-3]]

===== Control
Require that the presented identity evidence be validated and verified through _[Assignment: {ia-12-3_prm_1}]_.

===== Supplemental Guidance
Validation and verification of identity evidence increases the assurance that accounts and identifiers are being established for the correct user and authenticators are being bound to that user. Validation refers to the process of confirming that the evidence is genuine and authentic, and the data contained in the evidence is correct, current, and related to an individual. Verification confirms and establishes a linkage between the claimed identity and the actual existence of the user presenting the evidence. Acceptable methods for validating and verifying identity evidence are consistent with the risks to the systems, roles, and privileges associated with the users account.

==== IA-12(4) In-person Validation and Verification[[ia-12-4]]

===== Control
Require that the validation and verification of identity evidence be conducted in person before a designated registration authority.

===== Supplemental Guidance
In-person proofing reduces the likelihood of fraudulent credentials being issued because it requires the physical presence of individuals, the presentation of physical identity documents, and actual face-to-face interactions with designated registration authorities.

==== IA-12(5) Address Confirmation[[ia-12-5]]

===== Control
Require that a _[Assignment: {ia-12-5_prm_1}]_ be delivered through an out-of-band channel to verify the users address (physical or digital) of record.

===== Supplemental Guidance
To make it more difficult for adversaries to pose as legitimate users during the identity proofing process, organizations can use out-of-band methods to ensure that the individual associated with an address of record is the same individual that participated in the registration. Confirmation can take the form of a temporary enrollment code or a notice of proofing. The delivery address for these artifacts is obtained from records and not self-asserted by the user. The address can include a physical or digital address. A home address is an example of a physical address. Email addresses and telephone numbers are examples of digital addresses.

==== IA-12(6) Accept Externally-proofed Identities[[ia-12-6]]

===== Control
Accept externally-proofed identities at _[Assignment: {ia-12-6_prm_1}]_.

===== Supplemental Guidance
To limit unnecessary re-proofing of identities, particularly of non-PIV users, organizations accept proofing conducted at a commensurate level of assurance by other agencies or organizations. Proofing is consistent with organizational security policy and the identity assurance level appropriate for the system, application, or information accessed. Accepting externally-proofed identities is a fundamental component of managing federated identities across agencies and organizations.

