= Incident Response
:toc:
:toclevels: 1
:ir-1_prm_1: organization-defined personnel or roles
:ir-1_prm_2: one-or-more: Organization-level, Mission/business process-level, System-level
:ir-1_prm_3: organization-defined official
:ir-1_prm_4: organization-defined frequency
:ir-1_prm_5: organization-defined events
:ir-1_prm_6: organization-defined frequency
:ir-1_prm_7: organization-defined events
:ir-2_prm_1: organization-defined time period
:ir-2_prm_2: organization-defined frequency
:ir-2_prm_3: organization-defined frequency
:ir-2_prm_4: organization-defined events
:ir-2-2_prm_1: organization-defined automated mechanisms
:ir-3_prm_1: organization-defined frequency
:ir-3_prm_2: organization-defined tests
:ir-3-1_prm_1: organization-defined automated mechanisms
:ir-4-1_prm_1: organization-defined automated mechanisms
:ir-4-2_prm_1: organization-defined system components
:ir-4-2_prm_2: organization-defined types of dynamic reconfiguration
:ir-4-3_prm_1: organization-defined classes of incidents
:ir-4-3_prm_2: organization-defined actions to take in response to classes of incidents
:ir-4-5_prm_1: organization-defined security violations
:ir-4-7_prm_1: organization-defined entities
:ir-4-8_prm_1: organization-defined external organizations
:ir-4-8_prm_2: organization-defined incident information
:ir-4-9_prm_1: organization-defined dynamic response capabilities
:ir-4-11_prm_1: organization-defined time period
:ir-4-13_prm_1: organization-defined environments or resources
:ir-5-1_prm_1: organization-defined automated mechanisms
:ir-6_prm_1: organization-defined time period
:ir-6_prm_2: organization-defined authorities
:ir-6-1_prm_1: organization-defined automated mechanisms
:ir-6-2_prm_1: organization-defined personnel or roles
:ir-7-1_prm_1: organization-defined automated mechanisms
:ir-8_prm_1: organization-defined personnel or roles
:ir-8_prm_2: organization-defined frequency
:ir-8_prm_3: organization-defined entities, personnel, or roles
:ir-8_prm_4: organization-defined incident response personnel (identified by name and/or by role) and organizational elements
:ir-8_prm_5: organization-defined incident response personnel (identified by name and/or by role) and organizational elements
:ir-9_prm_1: organization-defined personnel or roles
:ir-9_prm_2: organization-defined personnel or roles
:ir-9_prm_3: organization-defined actions
:ir-9-2_prm_1: organization-defined frequency
:ir-9-3_prm_1: organization-defined procedures
:ir-9-4_prm_1: organization-defined controls

== IR-1 Policy and Procedures[[ir-1]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Develop, document, and disseminate to _[Assignment: {ir-1_prm_1}]_:
1. _[Assignment: {ir-1_prm_2}]_ incident response policy that:
(a) Addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance; and
(b) Is consistent with applicable laws, executive orders, directives, regulations, policies, standards, and guidelines; and
2. Procedures to facilitate the implementation of the incident response policy and the associated incident response controls;
b. Designate an _[Assignment: {ir-1_prm_3}]_ to manage the development, documentation, and dissemination of the incident response policy and procedures; and
c. Review and update the current incident response:
1. Policy _[Assignment: {ir-1_prm_4}]_ and following _[Assignment: {ir-1_prm_5}]_; and
2. Procedures _[Assignment: {ir-1_prm_6}]_ and following _[Assignment: {ir-1_prm_7}]_.

=== State Implementation Details
State organizations shall assess the significance of a security incident based on the business impact on the affected resources and the current and potential technical effect of the incident, e.g., loss of revenue, productivity, access to services, reputation, unauthorized disclosure of confidential information, or propagation to other networks.

=== Supplemental Guidance
Incident response policy and procedures address the controls in the IR family that are implemented within systems and organizations. The risk management strategy is an important factor in establishing such policies and procedures. Policies and procedures contribute to security and privacy assurance. Therefore, it is important that security and privacy programs collaborate on the development of incident response policy and procedures. Security and privacy program policies and procedures at the organization level are preferable, in general, and may obviate the need for mission- or system-specific policies and procedures. The policy can be included as part of the general security and privacy policy or be represented by multiple policies that reflect the complex nature of organizations. Procedures can be established for security and privacy programs, for mission or business processes, and for systems, if needed. Procedures describe how the policies or controls are implemented and can be directed at the individual or role that is the object of the procedure. Procedures can be documented in system security and privacy plans or in one or more separate documents. Events that may precipitate an update to incident response policy and procedures include assessment or audit findings, security incidents or breaches, or changes in laws, executive orders, directives, regulations, policies, standards, and guidelines. Simply restating controls does not constitute an organizational policy or procedure.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-12r1[SP 800-12], https://doi.org/10.6028/NIST.SP.800-30r1[SP 800-30], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-50[SP 800-50], https://doi.org/10.6028/NIST.SP.800-61r2[SP 800-61], https://doi.org/10.6028/NIST.SP.800-83r1[SP 800-83], https://doi.org/10.6028/NIST.SP.800-100[SP 800-100]

== IR-2 Incident Response Training[[ir-2]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Provide incident response training to system users consistent with assigned roles and responsibilities:
1. Within _[Assignment: {ir-2_prm_1}]_ of assuming an incident response role or responsibility or acquiring system access;
2. When required by system changes; and
3. _[Assignment: {ir-2_prm_2}]_ thereafter; and
b. Review and update incident response training content _[Assignment: {ir-2_prm_3}]_ and following _[Assignment: {ir-2_prm_4}]_.

=== State Implementation Details
The state organization trains personnel in their incident response roles and responsibilities with respect to the information system and provides refresher training at least annually.

=== Supplemental Guidance
Incident response training is associated with the assigned roles and responsibilities of organizational personnel to ensure that the appropriate content and level of detail are included in such training. For example, users may only need to know who to call or how to recognize an incident; system administrators may require additional training on how to handle incidents; and incident responders may receive more specific training on forensics, data collection techniques, reporting, system recovery, and system restoration. Incident response training includes user training in identifying and reporting suspicious activities from external and internal sources. Incident response training for users may be provided as part of 

=== References
https://obamawhitehouse.archives.gov/sites/default/files/omb/memoranda/2017/m-17-12_0.pdf[OMB M-17-12], https://doi.org/10.6028/NIST.SP.800-50[SP 800-50]

=== Control Enhancements
==== IR-2(1) Simulated Events[[ir-2-1]]

===== Control
Incorporate simulated events into incident response training to facilitate the required response by personnel in crisis situations.

===== Supplemental Guidance
Organizations establish requirements for responding to incidents in incident response plans. Incorporating simulated events into incident response training helps to ensure that personnel understand their individual responsibilities and what specific actions to take in crisis situations.

==== IR-2(2) Automated Training Environments[[ir-2-2]]

===== Control
Provide an incident response training environment using _[Assignment: {ir-2-2_prm_1}]_.

===== Supplemental Guidance
Automated mechanisms can provide a more thorough and realistic incident response training environment. This can be accomplished, for example, by providing more complete coverage of incident response issues, selecting more realistic training scenarios and environments, and stressing the response capability.

==== IR-2(3) Breach[[ir-2-3]]

===== Control
Provide incident response training on how to identify and respond to a breach, including the organization's process for reporting a breach.

===== Supplemental Guidance
For federal agencies, an incident that involves personally identifiable information is considered a breach. A breach results in the loss of control, compromise, unauthorized disclosure, unauthorized acquisition, or a similar occurrence where a person other than an authorized user accesses or potentially accesses personally identifiable information or an authorized user accesses or potentially accesses such information for other than authorized purposes. The incident response training emphasizes the obligation of individuals to report both confirmed and suspected breaches involving information in any medium or form, including paper, oral, and electronic. Incident response training includes tabletop exercises that simulate a breach. See 

== IR-3 Incident Response Testing[[ir-3]]

[width=50\%]
|===
|NIST Baseline |Required By 

|MODERATE
|2023-05-01

|===

=== Control
Test the effectiveness of the incident response capability for the system _[Assignment: {ir-3_prm_1}]_ using the following tests: _[Assignment: {ir-3_prm_2}]_.

=== Supplemental Guidance
Organizations test incident response capabilities to determine their effectiveness and identify potential weaknesses or deficiencies. Incident response testing includes the use of checklists, walk-through or tabletop exercises, and simulations (parallel or full interrupt). Incident response testing can include a determination of the effects on organizational operations and assets and individuals due to incident response. The use of qualitative and quantitative data aids in determining the effectiveness of incident response processes.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-84[SP 800-84], https://doi.org/10.6028/NIST.SP.800-115[SP 800-115]

=== Control Enhancements
==== IR-3(1) Automated Testing[[ir-3-1]]

===== Control
Test the incident response capability using _[Assignment: {ir-3-1_prm_1}]_.

===== Supplemental Guidance
Organizations use automated mechanisms to more thoroughly and effectively test incident response capabilities. This can be accomplished by providing more complete coverage of incident response issues, selecting realistic test scenarios and environments, and stressing the response capability.

==== IR-3(2) Coordination with Related Plans[[ir-3-2]]

===== Control
Coordinate incident response testing with organizational elements responsible for related plans.

===== Supplemental Guidance
Organizational plans related to incident response testing include business continuity plans, disaster recovery plans, continuity of operations plans, contingency plans, crisis communications plans, critical infrastructure plans, and occupant emergency plans.

==== IR-3(3) Continuous Improvement[[ir-3-3]]

===== Control
Use qualitative and quantitative data from testing to:
(a) Determine the effectiveness of incident response processes;
(b) Continuously improve incident response processes; and
(c) Provide incident response measures and metrics that are accurate, consistent, and in a reproducible format.

===== Supplemental Guidance
To help incident response activities function as intended, organizations may use metrics and evaluation criteria to assess incident response programs as part of an effort to continually improve response performance. These efforts facilitate improvement in incident response efficacy and lessen the impact of incidents.

== IR-4 Incident Handling[[ir-4]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Implement an incident handling capability for incidents that is consistent with the incident response plan and includes preparation, detection and analysis, containment, eradication, and recovery;
b. Coordinate incident handling activities with contingency planning activities;
c. Incorporate lessons learned from ongoing incident handling activities into incident response procedures, training, and testing, and implement the resulting changes accordingly; and
d. Ensure the rigor, intensity, scope, and results of incident handling activities are comparable and predictable across the organization.

=== Supplemental Guidance
Organizations recognize that incident response capabilities are dependent on the capabilities of organizational systems and the mission and business processes being supported by those systems. Organizations consider incident response as part of the definition, design, and development of mission and business processes and systems. Incident-related information can be obtained from a variety of sources, including audit monitoring, physical access monitoring, and network monitoring; user or administrator reports; and reported supply chain events. An effective incident handling capability includes coordination among many organizational entities (e.g., mission or business owners, system owners, authorizing officials, human resources offices, physical security offices, personnel security offices, legal departments, risk executive [function], operations personnel, procurement offices). Suspected security incidents include the receipt of suspicious email communications that can contain malicious code. Suspected supply chain incidents include the insertion of counterfeit hardware or malicious code into organizational systems or system components. For federal agencies, an incident that involves personally identifiable information is considered a breach. A breach results in unauthorized disclosure, the loss of control, unauthorized acquisition, compromise, or a similar occurrence where a person other than an authorized user accesses or potentially accesses personally identifiable information or an authorized user accesses or potentially accesses such information for other than authorized purposes.

=== References
https://www.congress.gov/bill/115th-congress/senate-bill/3085[FASC18], https://www.federalregister.gov/d/2020-18939[41 CFR 201], https://obamawhitehouse.archives.gov/sites/default/files/omb/memoranda/2017/m-17-12_0.pdf[OMB M-17-12], https://doi.org/10.6028/NIST.SP.800-61r2[SP 800-61], https://doi.org/10.6028/NIST.SP.800-86[SP 800-86], https://doi.org/10.6028/NIST.SP.800-101r1[SP 800-101], https://doi.org/10.6028/NIST.SP.800-150[SP 800-150], https://doi.org/10.6028/NIST.SP.800-160v2[SP 800-160-2], https://doi.org/10.6028/NIST.SP.800-184[SP 800-184], https://doi.org/10.6028/NIST.IR.7559[IR 7559]

=== Control Enhancements
==== IR-4(1) Automated Incident Handling Processes[[ir-4-1]]

===== Control
Support the incident handling process using _[Assignment: {ir-4-1_prm_1}]_.

===== Supplemental Guidance
Automated mechanisms that support incident handling processes include online incident management systems and tools that support the collection of live response data, full network packet capture, and forensic analysis.

==== IR-4(2) Dynamic Reconfiguration[[ir-4-2]]

===== Control
Include the following types of dynamic reconfiguration for _[Assignment: {ir-4-2_prm_1}]_ as part of the incident response capability: _[Assignment: {ir-4-2_prm_2}]_.

===== Supplemental Guidance
Dynamic reconfiguration includes changes to router rules, access control lists, intrusion detection or prevention system parameters, and filter rules for guards or firewalls. Organizations may perform dynamic reconfiguration of systems to stop attacks, misdirect attackers, and isolate components of systems, thus limiting the extent of the damage from breaches or compromises. Organizations include specific time frames for achieving the reconfiguration of systems in the definition of the reconfiguration capability, considering the potential need for rapid response to effectively address cyber threats.

==== IR-4(3) Continuity of Operations[[ir-4-3]]

===== Control
Identify _[Assignment: {ir-4-3_prm_1}]_ and take the following actions in response to those incidents to ensure continuation of organizational mission and business functions: _[Assignment: {ir-4-3_prm_2}]_.

===== Supplemental Guidance
Classes of incidents include malfunctions due to design or implementation errors and omissions, targeted malicious attacks, and untargeted malicious attacks. Incident response actions include orderly system degradation, system shutdown, fall back to manual mode or activation of alternative technology whereby the system operates differently, employing deceptive measures, alternate information flows, or operating in a mode that is reserved for when systems are under attack. Organizations consider whether continuity of operations requirements during an incident conflict with the capability to automatically disable the system as specified as part of 

==== IR-4(4) Information Correlation[[ir-4-4]]

===== Control
Correlate incident information and individual incident responses to achieve an organization-wide perspective on incident awareness and response.

===== Supplemental Guidance
Sometimes, a threat event, such as a hostile cyber-attack, can only be observed by bringing together information from different sources, including various reports and reporting procedures established by organizations.

==== IR-4(5) Automatic Disabling of System[[ir-4-5]]

===== Control
Implement a configurable capability to automatically disable the system if _[Assignment: {ir-4-5_prm_1}]_ are detected.

===== Supplemental Guidance
Organizations consider whether the capability to automatically disable the system conflicts with continuity of operations requirements specified as part of 

==== IR-4(6) Insider Threats[[ir-4-6]]

===== Control
Implement an incident handling capability for incidents involving insider threats.

===== Supplemental Guidance
Explicit focus on handling incidents involving insider threats provides additional emphasis on this type of threat and the need for specific incident handling capabilities to provide appropriate and timely responses.

==== IR-4(7) Insider Threats - Intra-organization Coordination[[ir-4-7]]

===== Control
Coordinate an incident handling capability for insider threats that includes the following organizational entities _[Assignment: {ir-4-7_prm_1}]_.

===== Supplemental Guidance
Incident handling for insider threat incidents (e.g., preparation, detection and analysis, containment, eradication, and recovery) requires coordination among many organizational entities, including mission or business owners, system owners, human resources offices, procurement offices, personnel offices, physical security offices, senior agency information security officer, operations personnel, risk executive (function), senior agency official for privacy, and legal counsel. In addition, organizations may require external support from federal, state, and local law enforcement agencies.

==== IR-4(8) Correlation with External Organizations[[ir-4-8]]

===== Control
Coordinate with _[Assignment: {ir-4-8_prm_1}]_ to correlate and share _[Assignment: {ir-4-8_prm_2}]_ to achieve a cross-organization perspective on incident awareness and more effective incident responses.

===== Supplemental Guidance
The coordination of incident information with external organizations-including mission or business partners, military or coalition partners, customers, and developers-can provide significant benefits. Cross-organizational coordination can serve as an important risk management capability. This capability allows organizations to leverage information from a variety of sources to effectively respond to incidents and breaches that could potentially affect the organization's operations, assets, and individuals.

==== IR-4(9) Dynamic Response Capability[[ir-4-9]]

===== Control
Employ _[Assignment: {ir-4-9_prm_1}]_ to respond to incidents.

===== Supplemental Guidance
The dynamic response capability addresses the timely deployment of new or replacement organizational capabilities in response to incidents. This includes capabilities implemented at the mission and business process level and at the system level.

==== IR-4(10) Supply Chain Coordination[[ir-4-10]]

===== Control
Coordinate incident handling activities involving supply chain events with other organizations involved in the supply chain.

===== Supplemental Guidance
Organizations involved in supply chain activities include product developers, system integrators, manufacturers, packagers, assemblers, distributors, vendors, and resellers. Supply chain incidents can occur anywhere through or to the supply chain and include compromises or breaches that involve primary or sub-tier providers, information technology products, system components, development processes or personnel, and distribution processes or warehousing facilities. Organizations consider including processes for protecting and sharing incident information in information exchange agreements and their obligations for reporting incidents to government oversight bodies (e.g., Federal Acquisition Security Council).

==== IR-4(11) Integrated Incident Response Team[[ir-4-11]]

===== Control
Establish and maintain an integrated incident response team that can be deployed to any location identified by the organization in _[Assignment: {ir-4-11_prm_1}]_.

===== Supplemental Guidance
An integrated incident response team is a team of experts that assesses, documents, and responds to incidents so that organizational systems and networks can recover quickly and implement the necessary controls to avoid future incidents. Incident response team personnel include forensic and malicious code analysts, tool developers, systems security and privacy engineers, and real-time operations personnel. The incident handling capability includes performing rapid forensic preservation of evidence and analysis of and response to intrusions. For some organizations, the incident response team can be a cross-organizational entity.
An integrated incident response team facilitates information sharing and allows organizational personnel (e.g., developers, implementers, and operators) to leverage team knowledge of the threat and implement defensive measures that enable organizations to deter intrusions more effectively. Moreover, integrated teams promote the rapid detection of intrusions, the development of appropriate mitigations, and the deployment of effective defensive measures. For example, when an intrusion is detected, the integrated team can rapidly develop an appropriate response for operators to implement, correlate the new incident with information on past intrusions, and augment ongoing cyber intelligence development. Integrated incident response teams are better able to identify adversary tactics, techniques, and procedures that are linked to the operations tempo or specific mission and business functions and to define responsive actions in a way that does not disrupt those mission and business functions. Incident response teams can be distributed within organizations to make the capability resilient.

==== IR-4(12) Malicious Code and Forensic Analysis[[ir-4-12]]

===== Control
Analyze malicious code and/or other residual artifacts remaining in the system after the incident.

===== Supplemental Guidance
When conducted carefully in an isolated environment, analysis of malicious code and other residual artifacts of a security incident or breach can give the organization insight into adversary tactics, techniques, and procedures. It can also indicate the identity or some defining characteristics of the adversary. In addition, malicious code analysis can help the organization develop responses to future incidents.

==== IR-4(13) Behavior Analysis[[ir-4-13]]

===== Control
Analyze anomalous or suspected adversarial behavior in or related to _[Assignment: {ir-4-13_prm_1}]_.

===== Supplemental Guidance
If the organization maintains a deception environment, an analysis of behaviors in that environment, including resources targeted by the adversary and timing of the incident or event, can provide insight into adversarial tactics, techniques, and procedures. External to a deception environment, the analysis of anomalous adversarial behavior (e.g., changes in system performance or usage patterns) or suspected behavior (e.g., changes in searches for the location of specific resources) can give the organization such insight.

==== IR-4(14) Security Operations Center[[ir-4-14]]

===== Control
Establish and maintain a security operations center.

===== Supplemental Guidance
A security operations center (SOC) is the focal point for security operations and computer network defense for an organization. The purpose of the SOC is to defend and monitor an organization's systems and networks (i.e., cyber infrastructure) on an ongoing basis. The SOC is also responsible for detecting, analyzing, and responding to cybersecurity incidents in a timely manner. The organization staffs the SOC with skilled technical and operational personnel (e.g., security analysts, incident response personnel, systems security engineers) and implements a combination of technical, management, and operational controls (including monitoring, scanning, and forensics tools) to monitor, fuse, correlate, analyze, and respond to threat and security-relevant event data from multiple sources. These sources include perimeter defenses, network devices (e.g., routers, switches), and endpoint agent data feeds. The SOC provides a holistic situational awareness capability to help organizations determine the security posture of the system and organization. A SOC capability can be obtained in a variety of ways. Larger organizations may implement a dedicated SOC while smaller organizations may employ third-party organizations to provide such a capability.

==== IR-4(15) Public Relations and Reputation Repair[[ir-4-15]]

===== Control
(a) Manage public relations associated with an incident; and
(b) Employ measures to repair the reputation of the organization.

===== Supplemental Guidance
It is important for an organization to have a strategy in place for addressing incidents that have been brought to the attention of the general public, have cast the organization in a negative light, or have affected the organization's constituents (e.g., partners, customers). Such publicity can be extremely harmful to the organization and affect its ability to carry out its mission and business functions. Taking proactive steps to repair the organization's reputation is an essential aspect of reestablishing the trust and confidence of its constituents.

== IR-5 Incident Monitoring[[ir-5]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
Track and document incidents.

=== Supplemental Guidance
Documenting incidents includes maintaining records about each incident, the status of the incident, and other pertinent information necessary for forensics as well as evaluating incident details, trends, and handling. Incident information can be obtained from a variety of sources, including network monitoring, incident reports, incident response teams, user complaints, supply chain partners, audit monitoring, physical access monitoring, and user and administrator reports. 

=== References
https://doi.org/10.6028/NIST.SP.800-61r2[SP 800-61]

=== Control Enhancements
==== IR-5(1) Automated Tracking, Data Collection, and Analysis[[ir-5-1]]

===== Control
Track incidents and collect and analyze incident information using _[Assignment: {ir-5-1_prm_1}]_.

===== Supplemental Guidance
Automated mechanisms for tracking incidents and collecting and analyzing incident information include Computer Incident Response Centers or other electronic databases of incidents and network monitoring devices.

== IR-6 Incident Reporting[[ir-6]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Require personnel to report suspected incidents to the organizational incident response capability within _[Assignment: {ir-6_prm_1}]_; and
b. Report incident information to _[Assignment: {ir-6_prm_2}]_.

=== State Implementation Details
a. Security incidents shall be promptly reported to immediate supervisors and the state organization Information Security Officer. Security incidents that require timely reporting to the department include those events that are assessed to:
(1) Propagate to other state systems;
(2) Result in criminal violations that shall be reported to law enforcement; or
(3) Involve the unauthorized disclosure or modification of confidential information, e.g., sensitive personal information as defined in SS521.002(a)(2), Business and Commerce Code, and other applicable laws that may require public notification.
b. If the security incident is assessed to involve suspected criminal activity (e.g., violations of Chapters 33, Penal Code (Computer Crimes) or Chapter 33A, Penal Code (Telecommunications Crimes)), the security incident shall be investigated,
              reported, and documented in a manner that restores operation promptly while meeting the legal requirements for handling of evidence.
c. Depending on the criticality of the incident, it will not always be feasible to gather all the information prior to reporting. In such cases, incident response teams should continue to report information to the department as it is collected. The
              department shall instruct state organizations as to the manner in which they shall report such information to the department. Supporting vendors or other third parties that report security incident information to a state organization shall submit
              such reports to the state organization in the form and manner specified by the department, unless otherwise directed by the state organization.
d. Summary reports of security-related events shall be sent to the department on a monthly basis no later than nine (9) calendar days after the end of the month. Organizations shall submit summary security incident reports in the form and manner
              specified by the department. Supporting vendors or other third parties that report security incident information to a state organization shall submit such reports to the state organization in the form and manner specified by the department, unless
              otherwise directed by the state organization.

=== TAMUS Implementation Details
The System member discloses incidents which compromise the confidentiality, integrity, or availability of major or high-impact information systems, or systems processing confidential information, as quickly as possible upon the discovery or receipt of notification of the incident, using the notification matrix in Appendix C: Incident Notification Process, unless a law enforcement agency determines such a notification will impede a criminal investigation.

=== Supplemental Guidance
The types of incidents reported, the content and timeliness of the reports, and the designated reporting authorities reflect applicable laws, executive orders, directives, regulations, policies, standards, and guidelines. Incident information can inform risk assessments, control effectiveness assessments, security requirements for acquisitions, and selection criteria for technology products.

=== References
https://www.congress.gov/bill/115th-congress/senate-bill/3085[FASC18], https://www.federalregister.gov/d/2020-18939[41 CFR 201], https://us-cert.cisa.gov/incident-notification-guidelines[USCERT IR], https://doi.org/10.6028/NIST.SP.800-61r2[SP 800-61]

=== Control Enhancements
==== IR-6(1) Automated Reporting[[ir-6-1]]

===== Control
Report incidents using _[Assignment: {ir-6-1_prm_1}]_.

===== Supplemental Guidance
The recipients of incident reports are specified in 

==== IR-6(2) Vulnerabilities Related to Incidents[[ir-6-2]]

===== Control
Report system vulnerabilities associated with reported incidents to _[Assignment: {ir-6-2_prm_1}]_.

===== Supplemental Guidance
Reported incidents that uncover system vulnerabilities are analyzed by organizational personnel including system owners, mission and business owners, senior agency information security officers, senior agency officials for privacy, authorizing officials, and the risk executive (function). The analysis can serve to prioritize and initiate mitigation actions to address the discovered system vulnerability.

==== IR-6(3) Supply Chain Coordination[[ir-6-3]]

===== Control
Provide incident information to the provider of the product or service and other organizations involved in the supply chain or supply chain governance for systems or system components related to the incident.

===== Supplemental Guidance
Organizations involved in supply chain activities include product developers, system integrators, manufacturers, packagers, assemblers, distributors, vendors, and resellers. Entities that provide supply chain governance include the Federal Acquisition Security Council (FASC). Supply chain incidents include compromises or breaches that involve information technology products, system components, development processes or personnel, distribution processes, or warehousing facilities. Organizations determine the appropriate information to share and consider the value gained from informing external organizations about supply chain incidents, including the ability to improve processes or to identify the root cause of an incident.

== IR-7 Incident Response Assistance[[ir-7]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
Provide an incident response support resource, integral to the organizational incident response capability, that offers advice and assistance to users of the system for the handling and reporting of incidents.

=== State Implementation Details
The state organization provides an incident response support resource that offers advice and assistance to users of the information system for the handling and reporting of security incidents. The support resource is an integral part of the organization's incident response capability.

=== Supplemental Guidance
Incident response support resources provided by organizations include help desks, assistance groups, automated ticketing systems to open and track incident response tickets, and access to forensics services or consumer redress services, when required.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.IR.7559[IR 7559]

=== Control Enhancements
==== IR-7(1) Automation Support for Availability of Information and Support[[ir-7-1]]

===== Control
Increase the availability of incident response information and support using _[Assignment: {ir-7-1_prm_1}]_.

===== Supplemental Guidance
Automated mechanisms can provide a push or pull capability for users to obtain incident response assistance. For example, individuals may have access to a website to query the assistance capability, or the assistance capability can proactively send incident response information to users (general distribution or targeted) as part of increasing understanding of current response capabilities and support.

==== IR-7(2) Coordination with External Providers[[ir-7-2]]

===== Control
(a) Establish a direct, cooperative relationship between its incident response capability and external providers of system protection capability; and
(b) Identify organizational incident response team members to the external providers.

===== Supplemental Guidance
External providers of a system protection capability include the Computer Network Defense program within the U.S. Department of Defense. External providers help to protect, monitor, analyze, detect, and respond to unauthorized activity within organizational information systems and networks. It may be beneficial to have agreements in place with external providers to clarify the roles and responsibilities of each party before an incident occurs.

== IR-8 Incident Response Plan[[ir-8]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Develop an incident response plan that:
1. Provides the organization with a roadmap for implementing its incident response capability;
2. Describes the structure and organization of the incident response capability;
3. Provides a high-level approach for how the incident response capability fits into the overall organization;
4. Meets the unique requirements of the organization, which relate to mission, size, structure, and functions;
5. Defines reportable incidents;
6. Provides metrics for measuring the incident response capability within the organization;
7. Defines the resources and management support needed to effectively maintain and mature an incident response capability;
8. Addresses the sharing of incident information;
9. Is reviewed and approved by _[Assignment: {ir-8_prm_1}]_
                     _[Assignment: {ir-8_prm_2}]_; and
10. Explicitly designates responsibility for incident response to _[Assignment: {ir-8_prm_3}]_.
b. Distribute copies of the incident response plan to _[Assignment: {ir-8_prm_4}]_;
c. Update the incident response plan to address system and organizational changes or problems encountered during plan implementation, execution, or testing;
d. Communicate incident response plan changes to _[Assignment: {ir-8_prm_5}]_; and
e. Protect the incident response plan from unauthorized disclosure and modification.

=== Supplemental Guidance
It is important that organizations develop and implement a coordinated approach to incident response. Organizational mission and business functions determine the structure of incident response capabilities. As part of the incident response capabilities, organizations consider the coordination and sharing of information with external organizations, including external service providers and other organizations involved in the supply chain. For incidents involving personally identifiable information (i.e., breaches), include a process to determine whether notice to oversight organizations or affected individuals is appropriate and provide that notice accordingly.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-61r2[SP 800-61], https://obamawhitehouse.archives.gov/sites/default/files/omb/memoranda/2017/m-17-12_0.pdf[OMB M-17-12]

=== Control Enhancements
==== IR-8(1) Breaches[[ir-8-1]]

===== Control
Include the following in the Incident Response Plan for breaches involving personally identifiable information:
(a) A process to determine if notice to individuals or other organizations, including oversight organizations, is needed;
(b) An assessment process to determine the extent of the harm, embarrassment, inconvenience, or unfairness to affected individuals and any mechanisms to mitigate such harms; and
(c) Identification of applicable privacy requirements.

===== Supplemental Guidance
Organizations may be required by law, regulation, or policy to follow specific procedures relating to breaches, including notice to individuals, affected organizations, and oversight bodies; standards of harm; and mitigation or other specific requirements.

== IR-9 Information Spillage Response[[ir-9]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
Respond to information spills by:
a. Assigning _[Assignment: {ir-9_prm_1}]_ with responsibility for responding to information spills;
b. Identifying the specific information involved in the system contamination;
c. Alerting _[Assignment: {ir-9_prm_2}]_ of the information spill using a method of communication not associated with the spill;
d. Isolating the contaminated system or system component;
e. Eradicating the information from the contaminated system or component;
f. Identifying other systems or system components that may have been subsequently contaminated; and
g. Performing the following additional actions: _[Assignment: {ir-9_prm_3}]_.

=== Supplemental Guidance
Information spillage refers to instances where information is placed on systems that are not authorized to process such information. Information spills occur when information that is thought to be a certain classification or impact level is transmitted to a system and subsequently is determined to be of a higher classification or impact level. At that point, corrective action is required. The nature of the response is based on the classification or impact level of the spilled information, the security capabilities of the system, the specific nature of the contaminated storage media, and the access authorizations of individuals with authorized access to the contaminated system. The methods used to communicate information about the spill after the fact do not involve methods directly associated with the actual spill to minimize the risk of further spreading the contamination before such contamination is isolated and eradicated.


=== Control Enhancements
==== IR-9(1) Responsible Personnel[[ir-9-1]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ir.adoc#ir-9[IR-9]

==== IR-9(2) Training[[ir-9-2]]

===== Control
Provide information spillage response training _[Assignment: {ir-9-2_prm_1}]_.

===== Supplemental Guidance
Organizations establish requirements for responding to information spillage incidents in incident response plans. Incident response training on a regular basis helps to ensure that organizational personnel understand their individual responsibilities and what specific actions to take when spillage incidents occur.

==== IR-9(3) Post-spill Operations[[ir-9-3]]

===== Control
Implement the following procedures to ensure that organizational personnel impacted by information spills can continue to carry out assigned tasks while contaminated systems are undergoing corrective actions: _[Assignment: {ir-9-3_prm_1}]_.

===== Supplemental Guidance
Corrective actions for systems contaminated due to information spillages may be time-consuming. Personnel may not have access to the contaminated systems while corrective actions are being taken, which may potentially affect their ability to conduct organizational business.

==== IR-9(4) Exposure to Unauthorized Personnel[[ir-9-4]]

===== Control
Employ the following controls for personnel exposed to information not within assigned access authorizations: _[Assignment: {ir-9-4_prm_1}]_.

===== Supplemental Guidance
Controls include ensuring that personnel who are exposed to spilled information are made aware of the laws, executive orders, directives, regulations, policies, standards, and guidelines regarding the information and the restrictions imposed based on exposure to such information.

== IR-10 Integrated Information Security Analysis Team[[ir-10]]

[width=50\%]
|===



|===

Status:: Withdrawn

Moved To:: xref:ir.adoc#ir-4-11[IR-4.11]


