= Media Protection
:toc:
:toclevels: 1
:mp-1_prm_1: organization-defined personnel or roles
:mp-1_prm_2: one-or-more: Organization-level, Mission/business process-level, System-level
:mp-1_prm_3: organization-defined official
:mp-1_prm_4: organization-defined frequency
:mp-1_prm_5: organization-defined events
:mp-1_prm_6: organization-defined frequency
:mp-1_prm_7: organization-defined events
:mp-2_prm_1: organization-defined types of digital and/or non-digital media
:mp-2_prm_2: organization-defined personnel or roles
:mp-3_prm_1: organization-defined types of system media
:mp-3_prm_2: organization-defined controlled areas
:mp-4_prm_1: organization-defined types of digital and/or non-digital media
:mp-4_prm_2: organization-defined controlled areas
:mp-4-2_prm_1: organization-defined automated mechanisms
:mp-5_prm_1: organization-defined types of system media
:mp-5_prm_2: organization-defined controls
:mp-6_prm_1: organization-defined system media
:mp-6_prm_2: organization-defined sanitization techniques and procedures
:mp-6-2_prm_1: organization-defined frequency
:mp-6-3_prm_1: organization-defined circumstances requiring sanitization of portable storage devices
:mp-6-7_prm_1: organization-defined system media
:mp-6-8_prm_1: organization-defined systems or system components
:mp-6-8_prm_2: remotely, under the following conditions: _[Assignment: organization-defined conditions]_
:mp-6-8_prm_3: organization-defined conditions
:mp-7_prm_1: Restrict, Prohibit
:mp-7_prm_2: organization-defined types of system media
:mp-7_prm_3: organization-defined systems or system components
:mp-7_prm_4: organization-defined controls
:mp-8_prm_1: organization-defined system media downgrading process
:mp-8_prm_2: organization-defined system media requiring downgrading
:mp-8-2_prm_1: organization-defined frequency

== MP-1 Policy and Procedures[[mp-1]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Develop, document, and disseminate to _[Assignment: {mp-1_prm_1}]_:
1. _[Assignment: {mp-1_prm_2}]_ media protection policy that:
(a) Addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance; and
(b) Is consistent with applicable laws, executive orders, directives, regulations, policies, standards, and guidelines; and
2. Procedures to facilitate the implementation of the media protection policy and the associated media protection controls;
b. Designate an _[Assignment: {mp-1_prm_3}]_ to manage the development, documentation, and dissemination of the media protection policy and procedures; and
c. Review and update the current media protection:
1. Policy _[Assignment: {mp-1_prm_4}]_ and following _[Assignment: {mp-1_prm_5}]_; and
2. Procedures _[Assignment: {mp-1_prm_6}]_ and following _[Assignment: {mp-1_prm_7}]_.

=== Supplemental Guidance
Media protection policy and procedures address the controls in the MP family that are implemented within systems and organizations. The risk management strategy is an important factor in establishing such policies and procedures. Policies and procedures contribute to security and privacy assurance. Therefore, it is important that security and privacy programs collaborate on the development of media protection policy and procedures. Security and privacy program policies and procedures at the organization level are preferable, in general, and may obviate the need for mission- or system-specific policies and procedures. The policy can be included as part of the general security and privacy policy or be represented by multiple policies that reflect the complex nature of organizations. Procedures can be established for security and privacy programs, for mission or business processes, and for systems, if needed. Procedures describe how the policies or controls are implemented and can be directed at the individual or role that is the object of the procedure. Procedures can be documented in system security and privacy plans or in one or more separate documents. Events that may precipitate an update to media protection policy and procedures include assessment or audit findings, security incidents or breaches, or changes in applicable laws, executive orders, directives, regulations, policies, standards, and guidelines. Simply restating controls does not constitute an organizational policy or procedure.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-12r1[SP 800-12], https://doi.org/10.6028/NIST.SP.800-30r1[SP 800-30], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-100[SP 800-100]

== MP-2 Media Access[[mp-2]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2022-11-01

|===

=== Control
Restrict access to _[Assignment: {mp-2_prm_1}]_ to _[Assignment: {mp-2_prm_2}]_.

=== Supplemental Guidance
System media includes digital and non-digital media. Digital media includes flash drives, diskettes, magnetic tapes, external or removable hard disk drives (e.g., solid state, magnetic), compact discs, and digital versatile discs. Non-digital media includes paper and microfilm. Denying access to patient medical records in a community hospital unless the individuals seeking access to such records are authorized healthcare providers is an example of restricting access to non-digital media. Limiting access to the design specifications stored on compact discs in the media library to individuals on the system development team is an example of restricting access to digital media.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.FIPS.199[FIPS 199], https://doi.org/10.6028/NIST.SP.800-111[SP 800-111]

=== Control Enhancements
==== MP-2(1) Automated Restricted Access[[mp-2-1]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:mp.adoc#mp-4-2[MP-4.2]

==== MP-2(2) Cryptographic Protection[[mp-2-2]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:sc.adoc#sc-28-1[SC-28.1]

== MP-3 Media Marking[[mp-3]]

=== Control
a. Mark system media indicating the distribution limitations, handling caveats, and applicable security markings (if any) of the information; and
b. Exempt _[Assignment: {mp-3_prm_1}]_ from marking if the media remain within _[Assignment: {mp-3_prm_2}]_.

=== TAMUS Implementation Details
The System member marks, physically or electronically, removable electronic media and information resources output containing sensitive personal information [TxBCC 521.002](#5b23f2c5-4c42-4b0e-a75b-34af3bcafb10) by indicating the ownership, distribution limitations, handling caveats, and applicable data categorizations.

=== Supplemental Guidance
Security marking refers to the application or use of human-readable security attributes. Digital media includes diskettes, magnetic tapes, external or removable hard disk drives (e.g., solid state, magnetic), flash drives, compact discs, and digital versatile discs. Non-digital media includes paper and microfilm. Controlled unclassified information is defined by the National Archives and Records Administration along with the appropriate safeguarding and dissemination requirements for such information and is codified in 

=== References
https://statutes.capitol.texas.gov/Docs/BC/htm/BC.521.htm[Texas Business and Commerce Code SS521.002], https://obamawhitehouse.archives.gov/the-press-office/2010/11/04/executive-order-13556-controlled-unclassified-information[EO 13556], https://www.federalregister.gov/documents/2016/09/14/2016-21665/controlled-unclassified-information[32 CFR 2002], https://doi.org/10.6028/NIST.FIPS.199[FIPS 199]

== MP-4 Media Storage[[mp-4]]

=== Control
a. Physically control and securely store _[Assignment: {mp-4_prm_1}]_ within _[Assignment: {mp-4_prm_2}]_; and
b. Protect system media types defined in MP-4a until the media are destroyed or sanitized using approved equipment, techniques, and procedures.

=== Supplemental Guidance
System media includes digital and non-digital media. Digital media includes flash drives, diskettes, magnetic tapes, external or removable hard disk drives (e.g., solid state, magnetic), compact discs, and digital versatile discs. Non-digital media includes paper and microfilm. Physically controlling stored media includes conducting inventories, ensuring procedures are in place to allow individuals to check out and return media to the library, and maintaining accountability for stored media. Secure storage includes a locked drawer, desk, or cabinet or a controlled media library. The type of media storage is commensurate with the security category or classification of the information on the media. Controlled areas are spaces that provide physical and procedural controls to meet the requirements established for protecting information and systems. Fewer controls may be needed for media that contains information determined to be in the public domain, publicly releasable, or have limited adverse impacts on organizations, operations, or individuals if accessed by other than authorized personnel. In these situations, physical access controls provide adequate protection.

=== References
https://doi.org/10.6028/NIST.FIPS.199[FIPS 199], https://doi.org/10.6028/NIST.SP.800-56Ar3[SP 800-56A], https://doi.org/10.6028/NIST.SP.800-56Br2[SP 800-56B], https://doi.org/10.6028/NIST.SP.800-56Cr2[SP 800-56C], https://doi.org/10.6028/NIST.SP.800-57pt1r5[SP 800-57-1], https://doi.org/10.6028/NIST.SP.800-57pt2r1[SP 800-57-2], https://doi.org/10.6028/NIST.SP.800-57pt3r1[SP 800-57-3], https://doi.org/10.6028/NIST.SP.800-111[SP 800-111]

=== Control Enhancements
==== MP-4(1) Cryptographic Protection[[mp-4-1]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:sc.adoc#sc-28-1[SC-28.1]

==== MP-4(2) Automated Restricted Access[[mp-4-2]]

===== Control
Restrict access to media storage areas and log access attempts and access granted using _[Assignment: {mp-4-2_prm_1}]_.

===== Supplemental Guidance
Automated mechanisms include keypads, biometric readers, or card readers on the external entries to media storage areas.

== MP-5 Media Transport[[mp-5]]

=== Control
a. Protect and control _[Assignment: {mp-5_prm_1}]_ during transport outside of controlled areas using _[Assignment: {mp-5_prm_2}]_;
b. Maintain accountability for system media during transport outside of controlled areas;
c. Document activities associated with the transport of system media; and
d. Restrict the activities associated with the transport of system media to authorized personnel.

=== Supplemental Guidance
System media includes digital and non-digital media. Digital media includes flash drives, diskettes, magnetic tapes, external or removable hard disk drives (e.g., solid state and  magnetic), compact discs, and digital versatile discs. Non-digital media includes microfilm and paper. Controlled areas are spaces for which organizations provide physical or procedural controls to meet requirements established for protecting information and systems. Controls to protect media during transport include cryptography and locked containers. Cryptographic mechanisms can provide confidentiality and integrity protections depending on the mechanisms implemented. Activities associated with media transport include releasing media for transport, ensuring that media enters the appropriate transport processes, and the actual transport. Authorized transport and courier personnel may include individuals external to the organization. Maintaining accountability of media during transport includes restricting transport activities to authorized personnel and tracking and/or obtaining records of transport activities as the media moves through the transportation system to prevent and detect loss, destruction, or tampering. Organizations establish documentation requirements for activities associated with the transport of system media in accordance with organizational assessments of risk. Organizations maintain the flexibility to define record-keeping methods for the different types of media transport as part of a system of transport-related records.

=== References
https://doi.org/10.6028/NIST.FIPS.199[FIPS 199], https://doi.org/10.6028/NIST.SP.800-60v1r1[SP 800-60-1], https://doi.org/10.6028/NIST.SP.800-60v2r1[SP 800-60-2]

=== Control Enhancements
==== MP-5(1) Protection Outside of Controlled Areas[[mp-5-1]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:mp.adoc#mp-5[MP-5]

==== MP-5(2) Documentation of Activities[[mp-5-2]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:mp.adoc#mp-5[MP-5]

==== MP-5(3) Custodians[[mp-5-3]]

===== Control
Employ an identified custodian during transport of system media outside of controlled areas.

===== Supplemental Guidance
Identified custodians provide organizations with specific points of contact during the media transport process and facilitate individual accountability. Custodial responsibilities can be transferred from one individual to another if an unambiguous custodian is identified.

==== MP-5(4) Cryptographic Protection[[mp-5-4]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:sc.adoc#sc-28-1[SC-28.1]

== MP-6 Media Sanitization[[mp-6]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Sanitize _[Assignment: {mp-6_prm_1}]_ prior to disposal, release out of organizational control, or release for reuse using _[Assignment: {mp-6_prm_2}]_; and
b. Employ sanitization mechanisms with the strength and integrity commensurate with the security category or classification of the information.

=== State Implementation Details
1. Prior to the sale or transfer of data processing equipment, to other than another Texas state agency or agent of the state, state agencies shall assess whether to remove data from any associated storage device.
2. Electronic state records shall be destroyed in accordance with SS441.185, Government Code. If the record retention period applicable for an electronic state record has not expired at the time the record is removed from data process equipment, the
              state agency shall retain a hard copy or other electronic copy of the record for the required retention period.
3. If it is possible that restricted personal information, confidential information, mission critical information, intellectual property, or licensed software is contained on the storage device, the storage device should be sanitized or the storage
              device should be removed and destroyed. Additional information on sanitization tools and methods of destruction (that comply with the Department of Defense 5220.22-M standard) are provided in the "Sale or Transfer of Computers and Software"
              guidelines available at http://www.dir.texas.gov.
State agencies shall keep a record/form (electronic or hard copy) documenting the removal and completion of the process with the following information:
a. date;
b. description of the item(s) and serial number(s);
c. inventory number(s);
d. the process and sanitization tools used to remove the data or method of destruction; and
e. the name and address of the organization the equipment was transferred to.

=== Supplemental Guidance
Media sanitization applies to all digital and non-digital system media subject to disposal or reuse, whether or not the media is considered removable. Examples include digital media in scanners, copiers, printers, notebook computers, workstations, network components, mobile devices, and non-digital media (e.g., paper and microfilm). The sanitization process removes information from system media such that the information cannot be retrieved or reconstructed. Sanitization techniques-including clearing, purging, cryptographic erase, de-identification of personally identifiable information, and destruction-prevent the disclosure of information to unauthorized individuals when such media is reused or released for disposal. Organizations determine the appropriate sanitization methods, recognizing that destruction is sometimes necessary when other methods cannot be applied to media requiring sanitization. Organizations use discretion on the employment of approved sanitization techniques and procedures for media that contains information deemed to be in the public domain or publicly releasable or information deemed to have no adverse impact on organizations or individuals if released for reuse or disposal. Sanitization of non-digital media includes destruction, removing a classified appendix from an otherwise unclassified document, or redacting selected sections or words from a document by obscuring the redacted sections or words in a manner equivalent in effectiveness to removing them from the document. NSA standards and policies control the sanitization process for media that contains classified information. NARA policies control the sanitization process for controlled unclassified information.

=== References
https://www.federalregister.gov/documents/2016/09/14/2016-21665/controlled-unclassified-information[32 CFR 2002], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://www.archives.gov/cui[NARA CUI], https://doi.org/10.6028/NIST.FIPS.199[FIPS 199], https://doi.org/10.6028/NIST.SP.800-60v1r1[SP 800-60-1], https://doi.org/10.6028/NIST.SP.800-60v2r1[SP 800-60-2], https://doi.org/10.6028/NIST.SP.800-88r1[SP 800-88], https://doi.org/10.6028/NIST.SP.800-124r1[SP 800-124], https://doi.org/10.6028/NIST.IR.8023[IR 8023], https://www.nsa.gov/resources/everyone/media-destruction[NSA MEDIA]

=== Control Enhancements
==== MP-6(1) Review, Approve, Track, Document, and Verify[[mp-6-1]]

===== Control
Review, approve, track, document, and verify media sanitization and disposal actions.

===== Supplemental Guidance
Organizations review and approve media to be sanitized to ensure compliance with records retention policies. Tracking and documenting actions include listing personnel who reviewed and approved sanitization and disposal actions, types of media sanitized, files stored on the media, sanitization methods used, date and time of the sanitization actions, personnel who performed the sanitization, verification actions taken and personnel who performed the verification, and the disposal actions taken. Organizations verify that the sanitization of the media was effective prior to disposal.

==== MP-6(2) Equipment Testing[[mp-6-2]]

===== Control
Test sanitization equipment and procedures _[Assignment: {mp-6-2_prm_1}]_ to ensure that the intended sanitization is being achieved.

===== Supplemental Guidance
Testing of sanitization equipment and procedures may be conducted by qualified and authorized external entities, including federal agencies or external service providers.

==== MP-6(3) Nondestructive Techniques[[mp-6-3]]

===== Control
Apply nondestructive sanitization techniques to portable storage devices prior to connecting such devices to the system under the following circumstances: _[Assignment: {mp-6-3_prm_1}]_.

===== Supplemental Guidance
Portable storage devices include external or removable hard disk drives (e.g., solid state, magnetic), optical discs, magnetic or optical tapes, flash memory devices, flash memory cards, and other external or removable disks. Portable storage devices can be obtained from untrustworthy sources and contain malicious code that can be inserted into or transferred to organizational systems through USB ports or other entry portals. While scanning storage devices is recommended, sanitization provides additional assurance that such devices are free of malicious code. Organizations consider nondestructive sanitization of portable storage devices when the devices are purchased from manufacturers or vendors prior to initial use or when organizations cannot maintain a positive chain of custody for the devices.

==== MP-6(4) Controlled Unclassified Information[[mp-6-4]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:mp.adoc#mp-6[MP-6]

==== MP-6(5) Classified Information[[mp-6-5]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:mp.adoc#mp-6[MP-6]

==== MP-6(6) Media Destruction[[mp-6-6]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:mp.adoc#mp-6[MP-6]

==== MP-6(7) Dual Authorization[[mp-6-7]]

===== Control
Enforce dual authorization for the sanitization of _[Assignment: {mp-6-7_prm_1}]_.

===== Supplemental Guidance
Organizations employ dual authorization to help ensure that system media sanitization cannot occur unless two technically qualified individuals conduct the designated task. Individuals who sanitize system media possess sufficient skills and expertise to determine if the proposed sanitization reflects applicable federal and organizational standards, policies, and procedures. Dual authorization also helps to ensure that sanitization occurs as intended, protecting against errors and false claims of having performed the sanitization actions. Dual authorization may also be known as two-person control. To reduce the risk of collusion, organizations consider rotating dual authorization duties to other individuals.

==== MP-6(8) Remote Purging or Wiping of Information[[mp-6-8]]

===== Control
Provide the capability to purge or wipe information from _[Assignment: {mp-6-8_prm_1}]_
                  _[Assignment: {mp-6-8_prm_2}]_.

===== Supplemental Guidance
Remote purging or wiping of information protects information on organizational systems and system components if systems or components are obtained by unauthorized individuals. Remote purge or wipe commands require strong authentication to help mitigate the risk of unauthorized individuals purging or wiping the system, component, or device. The purge or wipe function can be implemented in a variety of ways, including by overwriting data or information multiple times or by destroying the key necessary to decrypt encrypted data.

== MP-7 Media Use[[mp-7]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. _[Assignment: {mp-7_prm_1}]_ the use of _[Assignment: {mp-7_prm_2}]_ on _[Assignment: {mp-7_prm_3}]_ using _[Assignment: {mp-7_prm_4}]_; and
b. Prohibit the use of portable storage devices in organizational systems when such devices have no identifiable owner.

=== Supplemental Guidance
System media includes both digital and non-digital media. Digital media includes diskettes, magnetic tapes, flash drives, compact discs, digital versatile discs, and removable hard disk drives. Non-digital media includes paper and microfilm. Media use protections also apply to mobile devices with information storage capabilities. In contrast to 

=== References
https://doi.org/10.6028/NIST.FIPS.199[FIPS 199], https://doi.org/10.6028/NIST.SP.800-111[SP 800-111]

=== Control Enhancements
==== MP-7(1) Prohibit Use Without Owner[[mp-7-1]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:mp.adoc#mp-7[MP-7]

==== MP-7(2) Prohibit Use of Sanitization-resistant Media[[mp-7-2]]

===== Control
Prohibit the use of sanitization-resistant media in organizational systems.

===== Supplemental Guidance
Sanitization resistance refers to how resistant media are to non-destructive sanitization techniques with respect to the capability to purge information from media. Certain types of media do not support sanitization commands, or if supported, the interfaces are not supported in a standardized way across these devices. Sanitization-resistant media includes compact flash, embedded flash on boards and devices, solid state drives, and USB removable media.

== MP-8 Media Downgrading[[mp-8]]

=== Control
a. Establish _[Assignment: {mp-8_prm_1}]_ that includes employing downgrading mechanisms with strength and integrity commensurate with the security category or classification of the information;
b. Verify that the system media downgrading process is commensurate with the security category and/or classification level of the information to be removed and the access authorizations of the potential recipients of the downgraded information;
c. Identify _[Assignment: {mp-8_prm_2}]_; and
d. Downgrade the identified system media using the established process.

=== Supplemental Guidance
Media downgrading applies to digital and non-digital media subject to release outside of the organization, whether the media is considered removable or not. When applied to system media, the downgrading process removes information from the media, typically by security category or classification level, such that the information cannot be retrieved or reconstructed. Downgrading of media includes redacting information to enable wider release and distribution. Downgrading ensures that empty space on the media is devoid of information.

=== References
https://www.federalregister.gov/documents/2016/09/14/2016-21665/controlled-unclassified-information[32 CFR 2002], https://www.nsa.gov/resources/everyone/media-destruction[NSA MEDIA]

=== Control Enhancements
==== MP-8(1) Documentation of Process[[mp-8-1]]

===== Control
Document system media downgrading actions.

===== Supplemental Guidance
Organizations can document the media downgrading process by providing information, such as the downgrading technique employed, the identification number of the downgraded media, and the identity of the individual that authorized and/or performed the downgrading action.

==== MP-8(2) Equipment Testing[[mp-8-2]]

===== Control
Test downgrading equipment and procedures _[Assignment: {mp-8-2_prm_1}]_ to ensure that downgrading actions are being achieved.

===== Supplemental Guidance
None.

==== MP-8(3) Controlled Unclassified Information[[mp-8-3]]

===== Control
Downgrade system media containing controlled unclassified information prior to public release.

===== Supplemental Guidance
The downgrading of controlled unclassified information uses approved sanitization tools, techniques, and procedures.

==== MP-8(4) Classified Information[[mp-8-4]]

===== Control
Downgrade system media containing classified information prior to release to individuals without required access authorizations.

===== Supplemental Guidance
Downgrading of classified information uses approved sanitization tools, techniques, and procedures to transfer information confirmed to be unclassified from classified systems to unclassified media.

