= Planning
:toc:
:toclevels: 1
:pl-1_prm_1: organization-defined personnel or roles
:pl-1_prm_2: one-or-more: Organization-level, Mission/business process-level, System-level
:pl-1_prm_3: organization-defined official
:pl-1_prm_4: organization-defined frequency
:pl-1_prm_5: organization-defined events
:pl-1_prm_6: organization-defined frequency
:pl-1_prm_7: organization-defined events
:pl-2_prm_1: organization-defined individuals or groups
:pl-2_prm_2: organization-defined personnel or roles
:pl-2_prm_3: organization-defined frequency
:pl-4_prm_1: organization-defined frequency
:pl-4_prm_2: one-or-more: _[Assignment: organization-defined frequency]_, when the rules are revised or updated
:pl-4_prm_3: organization-defined frequency
:pl-7_prm_1: organization-defined frequency
:pl-8_prm_1: organization-defined frequency
:pl-8-1_prm_1: organization-defined controls
:pl-8-1_prm_2: organization-defined locations and architectural layers
:pl-8-2_prm_1: organization-defined controls
:pl-8-2_prm_2: organization-defined locations and architectural layers
:pl-9_prm_1: organization-defined controls and related processes

== PL-1 Policy and Procedures[[pl-1]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Develop, document, and disseminate to _[Assignment: {pl-1_prm_1}]_:
1. _[Assignment: {pl-1_prm_2}]_ planning policy that:
(a) Addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance; and
(b) Is consistent with applicable laws, executive orders, directives, regulations, policies, standards, and guidelines; and
2. Procedures to facilitate the implementation of the planning policy and the associated planning controls;
b. Designate an _[Assignment: {pl-1_prm_3}]_ to manage the development, documentation, and dissemination of the planning policy and procedures; and
c. Review and update the current planning:
1. Policy _[Assignment: {pl-1_prm_4}]_ and following _[Assignment: {pl-1_prm_5}]_; and
2. Procedures _[Assignment: {pl-1_prm_6}]_ and following _[Assignment: {pl-1_prm_7}]_.

=== State Implementation Details
As required by TAC 202.23/73(a), the state organization delivers, at least annually, to the organization head a report on state organization information security program.

=== Supplemental Guidance
Planning policy and procedures for the controls in the PL family implemented within systems and organizations. The risk management strategy is an important factor in establishing such policies and procedures. Policies and procedures contribute to security and privacy assurance. Therefore, it is important that security and privacy programs collaborate on their development. Security and privacy program policies and procedures at the organization level are preferable, in general, and may obviate the need for mission level or system-specific policies and procedures. The policy can be included as part of the general security and privacy policy or be represented by multiple policies that reflect the complex nature of organizations. Procedures can be established for security and privacy programs, for mission/business processes, and for systems, if needed. Procedures describe how the policies or controls are implemented and can be directed at the individual or role that is the object of the procedure. Procedures can be documented in system security and privacy plans or in one or more separate documents. Events that may precipitate an update to planning policy and procedures include, but are not limited to, assessment or audit findings, security incidents or breaches, or changes in laws, executive orders, directives, regulations, policies, standards, and guidelines. Simply restating controls does not constitute an organizational policy or procedure.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-12r1[SP 800-12], https://doi.org/10.6028/NIST.SP.800-18r1[SP 800-18], https://doi.org/10.6028/NIST.SP.800-30r1[SP 800-30], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-100[SP 800-100]

== PL-2 System Security and Privacy Plans[[pl-2]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Develop security and privacy plans for the system that:
1. Are consistent with the organization's enterprise architecture;
2. Explicitly define the constituent system components;
3. Describe the operational context of the system in terms of mission and business processes;
4. Identify the individuals that fulfill system roles and responsibilities;
5. Identify the information types processed, stored, and transmitted by the system;
6. Provide the security categorization of the system, including supporting rationale;
7. Describe any specific threats to the system that are of concern to the organization;
8. Provide the results of a privacy risk assessment for systems processing personally identifiable information;
9. Describe the operational environment for the system and any dependencies on or connections to other systems or system components;
10. Provide an overview of the security and privacy requirements for the system;
11. Identify any relevant control baselines or overlays, if applicable;
12. Describe the controls in place or planned for meeting the security and privacy requirements, including a rationale for any tailoring decisions;
13. Include risk determinations for security and privacy architecture and design decisions;
14. Include security- and privacy-related activities affecting the system that require planning and coordination with _[Assignment: {pl-2_prm_1}]_; and
15. Are reviewed and approved by the authorizing official or designated representative prior to plan implementation.
b. Distribute copies of the plans and communicate subsequent changes to the plans to _[Assignment: {pl-2_prm_2}]_;
c. Review the plans _[Assignment: {pl-2_prm_3}]_;
d. Update the plans to address changes to the system and environment of operation or problems identified during plan implementation or control assessments; and
e. Protect the plans from unauthorized disclosure and modification.

=== Supplemental Guidance
System security and privacy plans are scoped to the system and system components within the defined authorization boundary and contain an overview of the security and privacy requirements for the system and the controls selected to satisfy the requirements. The plans describe the intended application of each selected control in the context of the system with a sufficient level of detail to correctly implement the control and to subsequently assess the effectiveness of the control. The control documentation describes how system-specific and hybrid controls are implemented and the plans and expectations regarding the functionality of the system. System security and privacy plans can also be used in the design and development of systems in support of life cycle-based security and privacy engineering processes. System security and privacy plans are living documents that are updated and adapted throughout the system development life cycle (e.g., during capability determination, analysis of alternatives, requests for proposal, and design reviews). 
Organizations may develop a single, integrated security and privacy plan or maintain separate plans. Security and privacy plans relate security and privacy requirements to a set of controls and control enhancements. The plans describe how the controls and control enhancements meet the security and privacy requirements but do not provide detailed, technical descriptions of the design or implementation of the controls and control enhancements. Security and privacy plans contain sufficient information (including specifications of control parameter values for selection and assignment operations explicitly or by reference) to enable a design and implementation that is unambiguously compliant with the intent of the plans and subsequent determinations of risk to organizational operations and assets, individuals, other organizations, and the Nation if the plan is implemented.
Security and privacy plans need not be single documents. The plans can be a collection of various documents, including documents that already exist. Effective security and privacy plans make extensive use of references to policies, procedures, and additional documents, including design and implementation specifications where more detailed information can be obtained. The use of references helps reduce the documentation associated with security and privacy programs and maintains the security- and privacy-related information in other established management and operational areas, including enterprise architecture, system development life cycle, systems engineering, and acquisition. Security and privacy plans need not contain detailed contingency plan or incident response plan information but can instead provide-explicitly or by reference-sufficient information to define what needs to be accomplished by those plans.
Security- and privacy-related activities that may require coordination and planning with other individuals or groups within the organization include assessments, audits, inspections, hardware and software maintenance, acquisition and supply chain risk management, patch management, and contingency plan testing. Planning and coordination include emergency and nonemergency (i.e., planned or non-urgent unplanned) situations. The process defined by organizations to plan and coordinate security- and privacy-related activities can also be included in other documents, as appropriate.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-18r1[SP 800-18], https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37], https://doi.org/10.6028/NIST.SP.800-160v1[SP 800-160-1], https://doi.org/10.6028/NIST.SP.800-160v2[SP 800-160-2]

=== Control Enhancements
==== PL-2(1) Concept of Operations[[pl-2-1]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:pl.adoc#pl-7[PL-7]

==== PL-2(2) Functional Architecture[[pl-2-2]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:pl.adoc#pl-8[PL-8]

==== PL-2(3) Plan and Coordinate with Other Organizational Entities[[pl-2-3]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:pl.adoc#pl-2[PL-2]

== PL-3 System Security Plan Update[[pl-3]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:pl.adoc#pl-2[PL-2]


== PL-4 Rules of Behavior[[pl-4]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Establish and provide to individuals requiring access to the system, the rules that describe their responsibilities and expected behavior for information and system usage, security, and privacy;
b. Receive a documented acknowledgment from such individuals, indicating that they have read, understand, and agree to abide by the rules of behavior, before authorizing access to information and the system;
c. Review and update the rules of behavior _[Assignment: {pl-4_prm_1}]_; and
d. Require individuals who have acknowledged a previous version of the rules of behavior to read and re-acknowledge _[Assignment: {pl-4_prm_2}]_.

=== TAMUS Implementation Details
The System member:
a. documents acceptable use guidelines;
b. ensures users formally acknowledge, agree to abide by, and adhere to prudent and responsible Internet use practices (including reasonable personal use) outlined in Texas A&M System Policy 33.04, Use of System Resources [TAMUS 33.04](#a444439a-d0c7-4d93-b98d-3eeb506f2a1e), and the
                member's acceptable use guidelines;
c. establishes a documented process for authorization to monitor member information resources, and
d. monitors information resources in accordance with Texas A&M System Policy 29.01, Information Resources [TAMUS 29.01](#ac9542bc-0446-48f5-b565-a888d6b043a7).

=== Supplemental Guidance
Rules of behavior represent a type of access agreement for organizational users. Other types of access agreements include nondisclosure agreements, conflict-of-interest agreements, and acceptable use agreements (see 

=== References
https://policies.tamus.edu/29-01.pdf[Texas A&M University System Policy 29.01], https://policies.tamus.edu/33-04.pdf[Texas A&M University System Policy 33.04], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-18r1[SP 800-18]

=== Control Enhancements
==== PL-4(1) Social Media and External Site/application Usage Restrictions[[pl-4-1]]

===== Control
Include in the rules of behavior, restrictions on:
(a) Use of social media, social networking sites, and external sites/applications;
(b) Posting organizational information on public websites; and
(c) Use of organization-provided identifiers (e.g., email addresses) and authentication secrets (e.g., passwords) for creating accounts on external sites/applications.

===== Supplemental Guidance
Social media, social networking, and external site/application usage restrictions address rules of behavior related to the use of social media, social networking, and external sites when organizational personnel are using such sites for official duties or in the conduct of official business, when organizational information is involved in social media and social networking transactions, and when personnel access social media and networking sites from organizational systems. Organizations also address specific rules that prevent unauthorized entities from obtaining non-public organizational information from social media and networking sites either directly or through inference. Non-public information includes personally identifiable information and system account information.

== PL-5 Privacy Impact Assessment[[pl-5]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ra.adoc#ra-8[RA-8]


== PL-6 Security-related Activity Planning[[pl-6]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:pl.adoc#pl-2[PL-2]


== PL-7 Concept of Operations[[pl-7]]

=== Control
a. Develop a Concept of Operations (CONOPS) for the system describing how the organization intends to operate the system from the perspective of information security and privacy; and
b. Review and update the CONOPS _[Assignment: {pl-7_prm_1}]_.

=== Supplemental Guidance
The CONOPS may be included in the security or privacy plans for the system or in other system development life cycle documents. The CONOPS is a living document that requires updating throughout the system development life cycle. For example, during system design reviews, the concept of operations is checked to ensure that it remains consistent with the design for controls, the system architecture, and the operational procedures. Changes to the CONOPS are reflected in ongoing updates to the security and privacy plans, security and privacy architectures, and other organizational documents, such as procurement specifications, system development life cycle documents, and systems engineering documents.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130]

== PL-8 Security and Privacy Architectures[[pl-8]]

=== Control
a. Develop security and privacy architectures for the system that:
1. Describe the requirements and approach to be taken for protecting the confidentiality, integrity, and availability of organizational information;
2. Describe the requirements and approach to be taken for processing personally identifiable information to minimize privacy risk to individuals;
3. Describe how the architectures are integrated into and support the enterprise architecture; and
4. Describe any assumptions about, and dependencies on, external systems and services;
b. Review and update the architectures _[Assignment: {pl-8_prm_1}]_ to reflect changes in the enterprise architecture; and
c. Reflect planned architecture changes in security and privacy plans, Concept of Operations (CONOPS), criticality analysis, organizational procedures, and procurements and acquisitions.

=== Supplemental Guidance
The security and privacy architectures at the system level are consistent with the organization-wide security and privacy architectures described in 

In today's modern computing architectures, it is becoming less common for organizations to control all information resources. There may be key dependencies on external information services and service providers. Describing such dependencies in the security and privacy architectures is necessary for developing a comprehensive mission and business protection strategy. Establishing, developing, documenting, and maintaining under configuration control a baseline configuration for organizational systems is critical to implementing and maintaining effective architectures. The development of the architectures is coordinated with the senior agency information security officer and the senior agency official for privacy to ensure that the controls needed to support security and privacy requirements are identified and effectively implemented. In many circumstances, there may be no distinction between the security and privacy architecture for a system. In other circumstances, security objectives may be adequately satisfied, but privacy objectives may only be partially satisfied by the security requirements. In these cases, consideration of the privacy requirements needed to achieve satisfaction will result in a distinct privacy architecture. The documentation, however, may simply reflect the combined architectures.


=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-160v1[SP 800-160-1], https://doi.org/10.6028/NIST.SP.800-160v2[SP 800-160-2]

=== Control Enhancements
==== PL-8(1) Defense in Depth[[pl-8-1]]

===== Control
Design the security and privacy architectures for the system using a defense-in-depth approach that:
(a) Allocates _[Assignment: {pl-8-1_prm_1}]_ to _[Assignment: {pl-8-1_prm_2}]_; and
(b) Ensures that the allocated controls operate in a coordinated and mutually reinforcing manner.

===== Supplemental Guidance
Organizations strategically allocate security and privacy controls in the security and privacy architectures so that adversaries must overcome multiple controls to achieve their objective. Requiring adversaries to defeat multiple controls makes it more difficult to attack information resources by increasing the work factor of the adversary; it also increases the likelihood of detection. The coordination of allocated controls is essential to ensure that an attack that involves one control does not create adverse, unintended consequences by interfering with other controls. Unintended consequences can include system lockout and cascading alarms. The placement of controls in systems and organizations is an important activity that requires thoughtful analysis. The value of organizational assets is an important consideration in providing additional layering. Defense-in-depth architectural approaches include modularity and layering (see 

==== PL-8(2) Supplier Diversity[[pl-8-2]]

===== Control
Require that _[Assignment: {pl-8-2_prm_1}]_ allocated to _[Assignment: {pl-8-2_prm_2}]_ are obtained from different suppliers.

===== Supplemental Guidance
Information technology products have different strengths and weaknesses. Providing a broad spectrum of products complements the individual offerings. For example, vendors offering malicious code protection typically update their products at different times, often developing solutions for known viruses, Trojans, or worms based on their priorities and development schedules. By deploying different products at different locations, there is an increased likelihood that at least one of the products will detect the malicious code. With respect to privacy, vendors may offer products that track personally identifiable information in systems. Products may use different tracking methods. Using multiple products may result in more assurance that personally identifiable information is inventoried.

== PL-9 Central Management[[pl-9]]

=== Control
Centrally manage _[Assignment: {pl-9_prm_1}]_.

=== Supplemental Guidance
Central management refers to organization-wide management and implementation of selected controls and processes. This includes planning, implementing, assessing, authorizing, and monitoring the organization-defined, centrally managed controls and processes. As the central management of controls is generally associated with the concept of common (inherited) controls, such management promotes and facilitates standardization of control implementations and management and the judicious use of organizational resources. Centrally managed controls and processes may also meet independence requirements for assessments in support of initial and ongoing authorizations to operate and as part of organizational continuous monitoring.
Automated tools (e.g., security information and event management tools or enterprise security monitoring and management tools) can improve the accuracy, consistency, and availability of information associated with centrally managed controls and processes. Automation can also provide data aggregation and data correlation capabilities; alerting mechanisms; and dashboards to support risk-based decision-making within the organization.
As part of the control selection processes, organizations determine the controls that may be suitable for central management based on resources and capabilities. It is not always possible to centrally manage every aspect of a control. In such cases, the control can be treated as a hybrid control with the control managed and implemented centrally or at the system level. The controls and control enhancements that are candidates for full or partial central management include but are not limited to: 

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37]

== PL-10 Baseline Selection[[pl-10]]

=== Control
Select a control baseline for the system.

=== Supplemental Guidance
Control baselines are predefined sets of controls specifically assembled to address the protection needs of a group, organization, or community of interest. Controls are chosen for baselines to either satisfy mandates imposed by laws, executive orders, directives, regulations, policies, standards, and guidelines or address threats common to all users of the baseline under the assumptions specific to the baseline. Baselines represent a starting point for the protection of individuals' privacy, information, and information systems with subsequent tailoring actions to manage risk in accordance with mission, business, or other constraints (see 

=== References
https://doi.org/10.6028/NIST.FIPS.199[FIPS 199], https://doi.org/10.6028/NIST.FIPS.200[FIPS 200], https://doi.org/10.6028/NIST.SP.800-30r1[SP 800-30], https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-53B[SP 800-53B], https://doi.org/10.6028/NIST.SP.800-60v1r1[SP 800-60-1], https://doi.org/10.6028/NIST.SP.800-60v2r1[SP 800-60-2], https://doi.org/10.6028/NIST.SP.800-160v1[SP 800-160-1], https://www.cnss.gov/CNSS/issuances/Instructions.cfm[CNSSI 1253]

== PL-11 Baseline Tailoring[[pl-11]]

=== Control
Tailor the selected control baseline by applying specified tailoring actions.

=== Supplemental Guidance
The concept of tailoring allows organizations to specialize or customize a set of baseline controls by applying a defined set of tailoring actions. Tailoring actions facilitate such specialization and customization by allowing organizations to develop security and privacy plans that reflect their specific mission and business functions, the environments where their systems operate, the threats and vulnerabilities that can affect their systems, and any other conditions or situations that can impact their mission or business success. Tailoring guidance is provided in 

=== References
https://doi.org/10.6028/NIST.FIPS.199[FIPS 199], https://doi.org/10.6028/NIST.FIPS.200[FIPS 200], https://doi.org/10.6028/NIST.SP.800-30r1[SP 800-30], https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-53B[SP 800-53B], https://doi.org/10.6028/NIST.SP.800-60v1r1[SP 800-60-1], https://doi.org/10.6028/NIST.SP.800-60v2r1[SP 800-60-2], https://doi.org/10.6028/NIST.SP.800-160v1[SP 800-160-1], https://www.cnss.gov/CNSS/issuances/Instructions.cfm[CNSSI 1253]

