= Program Management
:toc:
:toclevels: 1
:pm-1_prm_1: organization-defined frequency
:pm-1_prm_2: organization-defined events
:pm-5_prm_1: organization-defined frequency
:pm-5-1_prm_1: organization-defined frequency
:pm-7-1_prm_1: organization-defined non-essential functions or services
:pm-9_prm_1: organization-defined frequency
:pm-11_prm_1: organization-defined frequency
:pm-17_prm_1: organization-defined frequency
:pm-18_prm_1: organization-defined frequency
:pm-23_prm_1: organization-defined roles
:pm-23_prm_2: organization-defined responsibilities
:pm-25_prm_1: organization-defined frequency
:pm-26_prm_1: organization-defined time period
:pm-26_prm_2: organization-defined time period
:pm-26_prm_3: organization-defined time period
:pm-27_prm_1: organization-defined privacy reports
:pm-27_prm_2: organization-defined oversight bodies
:pm-27_prm_3: organization-defined officials
:pm-27_prm_4: organization-defined frequency
:pm-28_prm_1: organization-defined personnel
:pm-28_prm_2: organization-defined frequency
:pm-30_prm_1: organization-defined frequency
:pm-31_prm_1: organization-defined metrics
:pm-31_prm_2: organization-defined frequencies
:pm-31_prm_3: organization-defined frequencies
:pm-31_prm_4: organization-defined personnel or roles
:pm-31_prm_5: organization-defined frequency
:pm-32_prm_1: organization-defined systems or systems components

== PM-1 Information Security Program Plan[[pm-1]]

[width=50\%]
|===
|Required By 

|2023-05-01

|===

=== Control
a. Develop and disseminate an organization-wide information security program plan that:
1. Provides an overview of the requirements for the security program and a description of the security program management controls and common controls in place or planned for meeting those requirements;
2. Includes the identification and assignment of roles, responsibilities, management commitment, coordination among organizational entities, and compliance;
3. Reflects the coordination among organizational entities responsible for information security; and
4. Is approved by a senior official with responsibility and accountability for the risk being incurred to organizational operations (including mission, functions, image, and reputation), organizational assets, individuals, other organizations, and the Nation;
b. Review and update the organization-wide information security program plan _[Assignment: {pm-1_prm_1}]_ and following _[Assignment: {pm-1_prm_2}]_; and
c. Protect the information security program plan from unauthorized disclosure and modification.

=== Supplemental Guidance
An information security program plan is a formal document that provides an overview of the security requirements for an organization-wide information security program and describes the program management controls and common controls in place or planned for meeting those requirements. An information security program plan can be represented in a single document or compilations of documents. Privacy program plans and supply chain risk management plans are addressed separately in 
An information security program plan documents implementation details about program management and common controls. The plan provides sufficient information about the controls (including specification of parameters for assignment and selection operations, explicitly or by reference) to enable implementations that are unambiguously compliant with the intent of the plan and a determination of the risk to be incurred if the plan is implemented as intended. Updates to information security program plans include organizational changes and problems identified during plan implementation or control assessments.
Program management controls may be implemented at the organization level or the mission or business process level, and are essential for managing the organization's information security program. Program management controls are distinct from common, system-specific, and hybrid controls because program management controls are independent of any particular system. Together, the individual system security plans and the organization-wide information security program plan provide complete coverage for the security controls employed within the organization.
Common controls available for inheritance by organizational systems are documented in an appendix to the organization's information security program plan unless the controls are included in a separate security plan for a system. The organization-wide information security program plan indicates which separate security plans contain descriptions of common controls.
Events that may precipitate an update to the information security program plan include, but are not limited to, organization-wide assessment or audit findings, security incidents or breaches, or changes in laws, executive orders, directives, regulations, policies, standards, and guidelines.

=== References
https://www.congress.gov/113/plaws/publ283/PLAW-113publ283.pdf[FISMA], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39]

== PM-2 Information Security Program Leadership Role[[pm-2]]

[width=50\%]
|===
|Required By 

|2022-11-01

|===

=== Control
Appoint a senior agency information security officer with the mission and resources to coordinate, develop, implement, and maintain an organization-wide information security program.

=== Supplemental Guidance
The senior agency information security officer is an organizational official. For federal agencies (as defined by applicable laws, executive orders, regulations, directives, policies, and standards), this official is the senior agency information security officer. Organizations may also refer to this official as the senior information security officer or chief information security officer.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/M-17-25.pdf[OMB M-17-25], https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-181r1[SP 800-181]

== PM-3 Information Security and Privacy Resources[[pm-3]]

[width=50\%]
|===
|Required By 

|2023-05-01

|===

=== Control
a. Include the resources needed to implement the information security and privacy programs in capital planning and investment requests and document all exceptions to this requirement;
b. Prepare documentation required for addressing information security and privacy programs in capital planning and investment requests in accordance with applicable laws, executive orders, directives, policies, regulations, standards; and
c. Make available for expenditure, the planned information security and privacy resources.

=== State Implementation Details
State implementation of this standard is incorporated into TAC 202.

=== Supplemental Guidance
Organizations consider establishing champions for information security and privacy and, as part of including the necessary resources, assign specialized expertise and resources as needed. Organizations may designate and empower an Investment Review Board or similar group to manage and provide oversight for the information security and privacy aspects of the capital planning and investment control process.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130]

== PM-4 Plan of Action and Milestones Process[[pm-4]]

[width=50\%]
|===
|Required By 

|2023-05-01

|===

=== Control
a. Implement a process to ensure that plans of action and milestones for the information security, privacy, and supply chain risk management programs and associated organizational systems:
1. Are developed and maintained;
2. Document the remedial information security, privacy, and supply chain risk management actions to adequately respond to risk to organizational operations and assets, individuals, other organizations, and the Nation; and
3. Are reported in accordance with established reporting requirements.
b. Review plans of action and milestones for consistency with the organizational risk management strategy and organization-wide priorities for risk response actions.

=== Supplemental Guidance
The plan of action and milestones is a key organizational document and is subject to reporting requirements established by the Office of Management and Budget. Organizations develop plans of action and milestones with an organization-wide perspective, prioritizing risk response actions and ensuring consistency with the goals and objectives of the organization. Plan of action and milestones updates are based on findings from control assessments and continuous monitoring activities. There can be multiple plans of action and milestones corresponding to the information system level, mission/business process level, and organizational/governance level. While plans of action and milestones are required for federal organizations, other types of organizations can help reduce risk by documenting and tracking planned remediations. Specific guidance on plans of action and milestones at the system level is provided in 

=== References
https://www.govinfo.gov/content/pkg/STATUTE-88/pdf/STATUTE-88-Pg1896.pdf[PRIVACT], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37]

== PM-5 System Inventory[[pm-5]]

[width=50\%]
|===
|Required By 

|2023-05-01

|===

=== Control
Develop and update _[Assignment: {pm-5_prm_1}]_ an inventory of organizational systems.

=== TAMUS Implementation Details
The System member:
a. designates a single system of record for inventory of all information systems [SP 800-171r2](#edeba4a2-6aec-49c5-9763-207a3970a366) and network-attached operational technology [SP 800-37r2](#482e4c99-9dc4-41ad-bba8-0f3f0032c1f8) owned or managed by the member;
b. includes any cloud computing services [SP 800-145](#1d635223-295d-4ac9-a117-9c7558cb9ea3) operated by the member in its inventory of information systems, and
c. designates which data regarding an information system to record in the inventory of information systems. At a minimum, the data includes a unique identifier (e.g., serial number or system name), owner, custodian, description of the
                information sytem's function or major application, and highest level of data categorization stored/processed on the information system.

=== Supplemental Guidance


=== References
https://doi.org/10.6028/NIST.SP.800-145[NIST Special Publication 800-145], https://doi.org/10.6028/NIST.SP.800-171r2[NIST Special Publication 800-171 Rev. 2], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.IR.8062[IR 8062]

=== Control Enhancements
==== PM-5(1) Inventory of Personally Identifiable Information[[pm-5-1]]

===== Control
Establish, maintain, and update _[Assignment: {pm-5-1_prm_1}]_ an inventory of all systems, applications, and projects that process personally identifiable information.

===== Supplemental Guidance
An inventory of systems, applications, and projects that process personally identifiable information supports the mapping of data actions, providing individuals with privacy notices, maintaining accurate personally identifiable information, and limiting the processing of personally identifiable information when such information is not needed for operational purposes. Organizations may use this inventory to ensure that systems only process the personally identifiable information for authorized purposes and that this processing is still relevant and necessary for the purpose specified therein.

== PM-6 Measures of Performance[[pm-6]]

[width=50\%]
|===
|Required By 

|2023-05-01

|===

=== Control
Develop, monitor, and report on the results of information security and privacy measures of performance.

=== Supplemental Guidance
Measures of performance are outcome-based metrics used by an organization to measure the effectiveness or efficiency of the information security and privacy programs and the controls employed in support of the program. To facilitate security and privacy risk management, organizations consider aligning measures of performance with the organizational risk tolerance as defined in the risk management strategy.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-55r1[SP 800-55], https://doi.org/10.6028/NIST.SP.800-137[SP 800-137]

== PM-7 Enterprise Architecture[[pm-7]]

[width=50\%]
|===
|Required By 

|2023-05-01

|===

=== Control
Develop and maintain an enterprise architecture with consideration for information security, privacy, and the resulting risk to organizational operations and assets, individuals, other organizations, and the Nation.

=== State Implementation Details
State implementation of this standard is an outcome of TAC 202 implementation.

=== Supplemental Guidance
The integration of security and privacy requirements and controls into the enterprise architecture helps to ensure that security and privacy considerations are addressed throughout the system development life cycle and are explicitly related to the organization's mission and business processes. The process of security and privacy requirements integration also embeds into the enterprise architecture and the organization's security and privacy architectures consistent with the organizational risk management strategy. For PM-7, security and privacy architectures are developed at a system-of-systems level, representing all organizational systems. For 

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-160v1[SP 800-160-1], https://doi.org/10.6028/NIST.SP.800-160v2[SP 800-160-2]

=== Control Enhancements
==== PM-7(1) Offloading[[pm-7-1]]

===== Control
Offload _[Assignment: {pm-7-1_prm_1}]_ to other systems, system components, or an external provider.

===== Supplemental Guidance
Not every function or service that a system provides is essential to organizational mission or business functions. Printing or copying is an example of a non-essential but supporting service for an organization. Whenever feasible, such supportive but non-essential functions or services are not co-located with the functions or services that support essential mission or business functions. Maintaining such functions on the same system or system component increases the attack surface of the organization's mission-essential functions or services. Moving supportive but non-essential functions to a non-critical system, system component, or external provider can also increase efficiency by putting those functions or services under the control of individuals or providers who are subject matter experts in the functions or services.

== PM-8 Critical Infrastructure Plan[[pm-8]]

=== Control
Address information security and privacy issues in the development, documentation, and updating of a critical infrastructure and key resources protection plan.

=== Supplemental Guidance
Protection strategies are based on the prioritization of critical assets and resources. The requirement and guidance for defining critical infrastructure and key resources and for preparing an associated critical infrastructure protection plan are found in applicable laws, executive orders, directives, policies, regulations, standards, and guidelines.

=== References
https://obamawhitehouse.archives.gov/the-press-office/2013/02/12/executive-order-improving-critical-infrastructure-cybersecurity[EO 13636], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://www.dhs.gov/homeland-security-presidential-directive-7[HSPD 7], https://www.dhs.gov/xlibrary/assets/NIPP_Plan.pdf[DHS NIPP]

== PM-9 Risk Management Strategy[[pm-9]]

[width=50\%]
|===
|Required By 

|2023-05-01

|===

=== Control
a. Develops a comprehensive strategy to manage:
1. Security risk to organizational operations and assets, individuals, other organizations, and the Nation associated with the operation and use of organizational systems; and
2. Privacy risk to individuals resulting from the authorized processing of personally identifiable information;
b. Implement the risk management strategy consistently across the organization; and
c. Review and update the risk management strategy _[Assignment: {pm-9_prm_1}]_ or as required, to address organizational changes.

=== State Implementation Details
State implementation of this standard is incorporated into TAC 202.

=== Supplemental Guidance
An organization-wide risk management strategy includes an expression of the security and privacy risk tolerance for the organization, security and privacy risk mitigation strategies, acceptable risk assessment methodologies, a process for evaluating security and privacy risk across the organization with respect to the organization's risk tolerance, and approaches for monitoring risk over time. The senior accountable official for risk management (agency head or designated official) aligns information security management processes with strategic, operational, and budgetary planning processes. The risk executive function, led by the senior accountable official for risk management, can facilitate consistent application of the risk management strategy organization-wide. The risk management strategy can be informed by security and privacy risk-related inputs from other sources, both internal and external to the organization, to ensure that the strategy is broad-based and comprehensive. The supply chain risk management strategy described in 

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-30r1[SP 800-30], https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-161[SP 800-161], https://doi.org/10.6028/NIST.IR.8023[IR 8023]

== PM-10 Authorization Process[[pm-10]]

[width=50\%]
|===
|Required By 

|2023-05-01

|===

=== Control
a. Manage the security and privacy state of organizational systems and the environments in which those systems operate through authorization processes;
b. Designate individuals to fulfill specific roles and responsibilities within the organizational risk management process; and
c. Integrate the authorization processes into an organization-wide risk management program.

=== State Implementation Details
State implementation of this standard is incorporated into TAC 202.

=== Supplemental Guidance
Authorization processes for organizational systems and environments of operation require the implementation of an organization-wide risk management process and associated security and privacy standards and guidelines. Specific roles for risk management processes include a risk executive (function) and designated authorizing officials for each organizational system and common control provider. The authorization processes for the organization are integrated with continuous monitoring processes to facilitate ongoing understanding and acceptance of security and privacy risks to organizational operations, organizational assets, individuals, other organizations, and the Nation.

=== References
https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-181r1[SP 800-181]

== PM-11 Mission and Business Process Definition[[pm-11]]

=== Control
a. Define organizational mission and business processes with consideration for information security and privacy and the resulting risk to organizational operations, organizational assets, individuals, other organizations, and the Nation; and
b. Determine information protection and personally identifiable information processing needs arising from the defined mission and business processes; and
c. Review and revise the mission and business processes _[Assignment: {pm-11_prm_1}]_.

=== Supplemental Guidance
Protection needs are technology-independent capabilities that are required to counter threats to organizations, individuals, systems, and the Nation through the compromise of information (i.e., loss of confidentiality, integrity, availability, or privacy). Information protection and personally identifiable information processing needs are derived from the mission and business needs defined by organizational stakeholders, the mission and business processes designed to meet those needs, and the organizational risk management strategy. Information protection and personally identifiable information processing needs determine the required controls for the organization and the systems. Inherent to defining protection and personally identifiable information processing needs is an understanding of the adverse impact that could result if a compromise or breach of information occurs. The categorization process is used to make such potential impact determinations. Privacy risks to individuals can arise from the compromise of personally identifiable information, but they can also arise as unintended consequences or a byproduct of the processing of personally identifiable information at any stage of the information life cycle. Privacy risk assessments are used to prioritize the risks that are created for individuals from system processing of personally identifiable information. These risk assessments enable the selection of the required privacy controls for the organization and systems. Mission and business process definitions and the associated protection requirements are documented in accordance with organizational policies and procedures.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.FIPS.199[FIPS 199], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-60v1r1[SP 800-60-1], https://doi.org/10.6028/NIST.SP.800-60v2r1[SP 800-60-2], https://doi.org/10.6028/NIST.SP.800-160v1[SP 800-160-1]

== PM-12 Insider Threat Program[[pm-12]]

=== Control
Implement an insider threat program that includes a cross-discipline insider threat incident handling team.

=== Supplemental Guidance
Organizations that handle classified information are required, under Executive Order 13587 
Insider threat programs can leverage the existence of incident handling teams that organizations may already have in place, such as computer security incident response teams. Human resources records are especially important in this effort, as there is compelling evidence to show that some types of insider crimes are often preceded by nontechnical behaviors in the workplace, including ongoing patterns of disgruntled behavior and conflicts with coworkers and other colleagues. These precursors can guide organizational officials in more focused, targeted monitoring efforts. However, the use of human resource records could raise significant concerns for privacy. The participation of a legal team, including consultation with the senior agency official for privacy, ensures that monitoring activities are performed in accordance with applicable laws, executive orders, directives, regulations, policies, standards, and guidelines.

=== References
https://obamawhitehouse.archives.gov/the-press-office/2011/10/07/executive-order-13587-structural-reforms-improve-security-classified-net[EO 13587], https://obamawhitehouse.archives.gov/the-press-office/2012/11/21/presidential-memorandum-national-insider-threat-policy-and-minimum-stand[NITP12], https://www.dni.gov/files/NCSC/documents/nittf/National_Insider_Threat_Policy.pdf[ODNI NITP]

== PM-13 Security and Privacy Workforce[[pm-13]]

=== Control
Establish a security and privacy workforce development and improvement program.

=== Supplemental Guidance
Security and privacy workforce development and improvement programs include defining the knowledge, skills, and abilities needed to perform security and privacy duties and tasks; developing role-based training programs for individuals assigned security and privacy roles and responsibilities; and providing standards and guidelines for measuring and building individual qualifications for incumbents and applicants for security- and privacy-related positions. Such workforce development and improvement programs can also include security and privacy career paths to encourage security and privacy professionals to advance in the field and fill positions with greater responsibility. The programs encourage organizations to fill security- and privacy-related positions with qualified personnel. Security and privacy workforce development and improvement programs are complementary to organizational security awareness and training programs and focus on developing and institutionalizing the core security and privacy capabilities of personnel needed to protect organizational operations, assets, and individuals.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-181r1[SP 800-181]

== PM-14 Testing, Training, and Monitoring[[pm-14]]

[width=50\%]
|===
|Required By 

|2023-05-01

|===

=== Control
a. Implement a process for ensuring that organizational plans for conducting security and privacy testing, training, and monitoring activities associated with organizational systems:
1. Are developed and maintained; and
2. Continue to be executed; and
b. Review testing, training, and monitoring plans for consistency with the organizational risk management strategy and organization-wide priorities for risk response actions.

=== State Implementation Details
State implementation of this standard is incorporated into TAC 202.

=== TAMUS Implementation Details
The System member ensures an IT organization is designated to provide security monitoring for all information systems, in both centralized and decentralized IT environments, owned or managed by the member.

=== Supplemental Guidance
A process for organization-wide security and privacy testing, training, and monitoring helps ensure that organizations provide oversight for testing, training, and monitoring activities and that those activities are coordinated. With the growing importance of continuous monitoring programs, the implementation of information security and privacy across the three levels of the risk management hierarchy and the widespread use of common controls, organizations coordinate and consolidate the testing and monitoring activities that are routinely conducted as part of ongoing assessments supporting a variety of controls. Security and privacy training activities, while focused on individual systems and specific roles, require coordination across all organizational elements. Testing, training, and monitoring plans and activities are informed by current threat and vulnerability assessments.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-53Ar4[SP 800-53A], https://doi.org/10.6028/NIST.SP.800-115[SP 800-115], https://doi.org/10.6028/NIST.SP.800-137[SP 800-137]

== PM-15 Security and Privacy Groups and Associations[[pm-15]]

[width=50\%]
|===
|Required By 

|2023-05-01

|===

=== Control
Establish and institutionalize contact with selected groups and associations within the security and privacy communities:
a. To facilitate ongoing security and privacy education and training for organizational personnel;
b. To maintain currency with recommended security and privacy practices, techniques, and technologies; and
c. To share current security and privacy information, including threats, vulnerabilities, and incidents.

=== State Implementation Details
State implementation of this standard is incorporated into TAC 202.

=== Supplemental Guidance
Ongoing contact with security and privacy groups and associations is important in an environment of rapidly changing technologies and threats. Groups and associations include special interest groups, professional associations, forums, news groups, users' groups, and peer groups of security and privacy professionals in similar organizations. Organizations select security and privacy groups and associations based on mission and business functions. Organizations share threat, vulnerability, and incident information as well as contextual insights, compliance techniques, and privacy problems consistent with applicable laws, executive orders, directives, policies, regulations, standards, and guidelines.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130]

== PM-16 Threat Awareness Program[[pm-16]]

[width=50\%]
|===
|Required By 

|2022-11-01

|===

=== Control
Implement a threat awareness program that includes a cross-organization information-sharing capability for threat intelligence.

=== State Implementation Details
State implementation of this standard is incorporated into TAC 202.

=== Supplemental Guidance
Because of the constantly changing and increasing sophistication of adversaries, especially the advanced persistent threat (APT), it may be more likely that adversaries can successfully breach or compromise organizational systems. One of the best techniques to address this concern is for organizations to share threat information, including threat events (i.e., tactics, techniques, and procedures) that organizations have experienced, mitigations that organizations have found are effective against certain types of threats, and threat intelligence (i.e., indications and warnings about threats). Threat information sharing may be bilateral or multilateral. Bilateral threat sharing includes government-to-commercial and government-to-government cooperatives. Multilateral threat sharing includes organizations taking part in threat-sharing consortia. Threat information may require special agreements and protection, or it may be freely shared.


=== Control Enhancements
==== PM-16(1) Automated Means for Sharing Threat Intelligence[[pm-16-1]]

===== Control
Employ automated mechanisms to maximize the effectiveness of sharing threat intelligence information.

===== Supplemental Guidance
To maximize the effectiveness of monitoring, it is important to know what threat observables and indicators the sensors need to be searching for. By using well-established frameworks, services, and automated tools, organizations improve their ability to rapidly share and feed the relevant threat detection signatures into monitoring tools.

== PM-17 Protecting Controlled Unclassified Information on External Systems[[pm-17]]

=== Control
a. Establish policy and procedures to ensure that requirements for the protection of controlled unclassified information that is processed, stored or transmitted on external systems, are implemented in accordance with applicable laws, executive orders, directives, policies, regulations, and standards; and
b. Review and update the policy and procedures _[Assignment: {pm-17_prm_1}]_.

=== Supplemental Guidance
Controlled unclassified information is defined by the National Archives and Records Administration along with the safeguarding and dissemination requirements for such information and is codified in 

=== References
https://www.federalregister.gov/documents/2016/09/14/2016-21665/controlled-unclassified-information[32 CFR 2002], https://doi.org/10.6028/NIST.SP.800-171r2[SP 800-171], https://doi.org/10.6028/NIST.SP.800-172-draft[SP 800-172], https://www.archives.gov/cui[NARA CUI]

== PM-18 Privacy Program Plan[[pm-18]]

=== Control
a. Develop and disseminate an organization-wide privacy program plan that provides an overview of the agency's privacy program, and:
1. Includes a description of the structure of the privacy program and the resources dedicated to the privacy program;
2. Provides an overview of the requirements for the privacy program and a description of the privacy program management controls and common controls in place or planned for meeting those requirements;
3. Includes the role of the senior agency official for privacy and the identification and assignment of roles of other privacy officials and staff and their responsibilities;
4. Describes management commitment, compliance, and the strategic goals and objectives of the privacy program;
5. Reflects coordination among organizational entities responsible for the different aspects of privacy; and
6. Is approved by a senior official with responsibility and accountability for the privacy risk being incurred to organizational operations (including mission, functions, image, and reputation), organizational assets, individuals, other organizations, and the Nation; and
b. Update the plan _[Assignment: {pm-18_prm_1}]_ and to address changes in federal privacy laws and policy and organizational changes and problems identified during plan implementation or privacy control assessments.

=== Supplemental Guidance
A privacy program plan is a formal document that provides an overview of an organization's privacy program, including a description of the structure of the privacy program, the resources dedicated to the privacy program, the role of the senior agency official for privacy and other privacy officials and staff, the strategic goals and objectives of the privacy program, and the program management controls and common controls in place or planned for meeting applicable privacy requirements and managing privacy risks. Privacy program plans can be represented in single documents or compilations of documents.
The senior agency official for privacy is responsible for designating which privacy controls the organization will treat as program management, common, system-specific, and hybrid controls. Privacy program plans provide sufficient information about the privacy program management and common controls (including the specification of parameters and assignment and selection operations explicitly or by reference) to enable control implementations that are unambiguously compliant with the intent of the plans and a determination of the risk incurred if the plans are implemented as intended.
Program management controls are generally implemented at the organization level and are essential for managing the organization's privacy program. Program management controls are distinct from common, system-specific, and hybrid controls because program management controls are independent of any particular information system. Together, the privacy plans for individual systems and the organization-wide privacy program plan provide complete coverage for the privacy controls employed within the organization.
Common controls are documented in an appendix to the organization's privacy program plan unless the controls are included in a separate privacy plan for a system. The organization-wide privacy program plan indicates which separate privacy plans contain descriptions of privacy controls.

=== References
https://www.govinfo.gov/content/pkg/STATUTE-88/pdf/STATUTE-88-Pg1896.pdf[PRIVACT], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130]

== PM-19 Privacy Program Leadership Role[[pm-19]]

=== Control
Appoint a senior agency official for privacy with the authority, mission, accountability, and resources to coordinate, develop, and implement, applicable privacy requirements and manage privacy risks through the organization-wide privacy program.

=== Supplemental Guidance
The privacy officer is an organizational official. For federal agencies-as defined by applicable laws, executive orders, directives, regulations, policies, standards, and guidelines-this official is designated as the senior agency official for privacy. Organizations may also refer to this official as the chief privacy officer. The senior agency official for privacy also has roles on the data management board (see 

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130]

== PM-20 Dissemination of Privacy Program Information[[pm-20]]

=== Control
Maintain a central resource webpage on the organization's principal public website that serves as a central source of information about the organization's privacy program and that:
a. Ensures that the public has access to information about organizational privacy activities and can communicate with its senior agency official for privacy;
b. Ensures that organizational privacy practices and reports are publicly available; and
c. Employs publicly facing email addresses and/or phone lines to enable the public to provide feedback and/or direct questions to privacy offices regarding privacy practices.

=== Supplemental Guidance
For federal agencies, the webpage is located at www.[agency].gov/privacy. Federal agencies include public privacy impact assessments, system of records notices, computer matching notices and agreements, 

=== References
https://www.govinfo.gov/content/pkg/STATUTE-88/pdf/STATUTE-88-Pg1896.pdf[PRIVACT], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf[OMB M-17-06]

=== Control Enhancements
==== PM-20(1) Privacy Policies on Websites, Applications, and Digital Services[[pm-20-1]]

===== Control
Develop and post privacy policies on all external-facing websites, mobile applications, and other digital services, that:
(a) Are written in plain language and organized in a way that is easy to understand and navigate;
(b) Provide information needed by the public to make an informed decision about whether and how to interact with the organization; and
(c) Are updated whenever the organization makes a substantive change to the practices it describes and includes a time/date stamp to inform the public of the date of the most recent changes.

===== Supplemental Guidance
Organizations post privacy policies on all external-facing websites, mobile applications, and other digital services. Organizations post a link to the relevant privacy policy on any known, major entry points to the website, application, or digital service. In addition, organizations provide a link to the privacy policy on any webpage that collects personally identifiable information. Organizations may be subject to applicable laws, executive orders, directives, regulations, or policies that require the provision of specific information to the public. Organizational personnel consult with the senior agency official for privacy and legal counsel regarding such requirements.

== PM-21 Accounting of Disclosures[[pm-21]]

=== Control
a. Develop and maintain an accurate accounting of disclosures of personally identifiable information, including:
1. Date, nature, and purpose of each disclosure; and
2. Name and address, or other contact information of the individual or organization to which the disclosure was made;
b. Retain the accounting of disclosures for the length of the time the personally identifiable information is maintained or five years after the disclosure is made, whichever is longer; and
c. Make the accounting of disclosures available to the individual to whom the personally identifiable information relates upon request.

=== Supplemental Guidance
The purpose of accounting of disclosures is to allow individuals to learn to whom their personally identifiable information has been disclosed, to provide a basis for subsequently advising recipients of any corrected or disputed personally identifiable information, and to provide an audit trail for subsequent reviews of organizational compliance with conditions for disclosures. For federal agencies, keeping an accounting of disclosures is required by the 
Organizations can use any system for keeping notations of disclosures, if it can construct from such a system, a document listing of all disclosures along with the required information. Automated mechanisms can be used by organizations to determine when personally identifiable information is disclosed, including commercial services that provide notifications and alerts. Accounting of disclosures may also be used to help organizations verify compliance with applicable privacy statutes and policies governing the disclosure or dissemination of information and dissemination restrictions.

=== References
https://www.govinfo.gov/content/pkg/STATUTE-88/pdf/STATUTE-88-Pg1896.pdf[PRIVACT], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130]

== PM-22 Personally Identifiable Information Quality Management[[pm-22]]

=== Control
Develop and document organization-wide policies and procedures for:
a. Reviewing for the accuracy, relevance, timeliness, and completeness of personally identifiable information across the information life cycle;
b. Correcting or deleting inaccurate or outdated personally identifiable information;
c. Disseminating notice of corrected or deleted personally identifiable information to individuals or other appropriate entities; and
d. Appeals of adverse decisions on correction or deletion requests.

=== Supplemental Guidance
Personally identifiable information quality management includes steps that organizations take to confirm the accuracy and relevance of personally identifiable information throughout the information life cycle. The information life cycle includes the creation, collection, use, processing, storage, maintenance, dissemination, disclosure, and disposition of personally identifiable information. Organizational policies and procedures for personally identifiable information quality management are important because inaccurate or outdated personally identifiable information maintained by organizations may cause problems for individuals. Organizations consider the quality of personally identifiable information involved in business functions where inaccurate information may result in adverse decisions or the denial of benefits and services, or the disclosure of the information may cause stigmatization. Correct information, in certain circumstances, can cause problems for individuals that outweigh the benefits of organizations maintaining the information. Organizations consider creating policies and procedures for the removal of such information.
The senior agency official for privacy ensures that practical means and mechanisms exist and are accessible for individuals or their authorized representatives to seek the correction or deletion of personally identifiable information. Processes for correcting or deleting data are clearly defined and publicly available. Organizations use discretion in determining whether data is to be deleted or corrected based on the scope of requests, the changes sought, and the impact of the changes. Additionally, processes include the provision of responses to individuals of decisions to deny requests for correction or deletion. The responses include the reasons for the decisions, a means to record individual objections to the decisions, and a means of requesting reviews of the initial determinations.
Organizations notify individuals or their designated representatives when their personally identifiable information is corrected or deleted to provide transparency and confirm the completed action. Due to the complexity of data flows and storage, other entities may need to be informed of the correction or deletion. Notice supports the consistent correction and deletion of personally identifiable information across the data ecosystem.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://www.whitehouse.gov/wp-content/uploads/2019/04/M-19-15.pdf[OMB M-19-15], https://csrc.nist.gov/publications/detail/sp/800-188/draft[SP 800-188]

== PM-23 Data Governance Body[[pm-23]]

=== Control
Establish a Data Governance Body consisting of _[Assignment: {pm-23_prm_1}]_ with _[Assignment: {pm-23_prm_2}]_.

=== Supplemental Guidance
A Data Governance Body can help ensure that the organization has coherent policies and the ability to balance the utility of data with security and privacy requirements. The Data Governance Body establishes policies, procedures, and standards that facilitate data governance so that data, including personally identifiable information, is effectively managed and maintained in accordance with applicable laws, executive orders, directives, regulations, policies, standards, and guidance. Responsibilities can include developing and implementing guidelines that support data modeling, quality, integrity, and the de-identification needs of personally identifiable information across the information life cycle as well as reviewing and approving applications to release data outside of the organization, archiving the applications and the released data, and performing post-release monitoring to ensure that the assumptions made as part of the data release continue to be valid. Members include the chief information officer, senior agency information security officer, and senior agency official for privacy. Federal agencies are required to establish a Data Governance Body with specific roles and responsibilities in accordance with the 

=== References
https://www.congress.gov/115/plaws/publ435/PLAW-115publ435.pdf[EVIDACT], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://www.whitehouse.gov/wp-content/uploads/2019/07/M-19-23.pdf[OMB M-19-23], https://csrc.nist.gov/publications/detail/sp/800-188/draft[SP 800-188]

== PM-24 Data Integrity Board[[pm-24]]

=== Control
Establish a Data Integrity Board to:
a. Review proposals to conduct or participate in a matching program; and
b. Conduct an annual review of all matching programs in which the agency has participated.

=== Supplemental Guidance
A Data Integrity Board is the board of senior officials designated by the head of a federal agency and is responsible for, among other things, reviewing the agency's proposals to conduct or participate in a matching program and conducting an annual review of all matching programs in which the agency has participated. As a general matter, a matching program is a computerized comparison of records from two or more automated 

=== References
https://www.govinfo.gov/content/pkg/STATUTE-88/pdf/STATUTE-88-Pg1896.pdf[PRIVACT], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A108/omb_circular_a-108.pdf[OMB A-108]

== PM-25 Minimization of Personally Identifiable Information Used in Testing, Training, and Research[[pm-25]]

=== Control
a. Develop, document, and implement policies and procedures that address the use of personally identifiable information for internal testing, training, and research;
b. Limit or minimize the amount of personally identifiable information used for internal testing, training, and research purposes;
c. Authorize the use of personally identifiable information when such information is required for internal testing, training, and research; and
d. Review and update policies and procedures _[Assignment: {pm-25_prm_1}]_.

=== Supplemental Guidance
The use of personally identifiable information in testing, research, and training increases the risk of unauthorized disclosure or misuse of such information. Organizations consult with the senior agency official for privacy and/or legal counsel to ensure that the use of personally identifiable information in testing, training, and research is compatible with the original purpose for which it was collected. When possible, organizations use placeholder data to avoid exposure of personally identifiable information when conducting testing, training, and research.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130]

== PM-26 Complaint Management[[pm-26]]

=== Control
Implement a process for receiving and responding to complaints, concerns, or questions from individuals about the organizational security and privacy practices that includes:
a. Mechanisms that are easy to use and readily accessible by the public;
b. All information necessary for successfully filing complaints;
c. Tracking mechanisms to ensure all complaints received are reviewed and addressed within _[Assignment: {pm-26_prm_1}]_;
d. Acknowledgement of receipt of complaints, concerns, or questions from individuals within _[Assignment: {pm-26_prm_2}]_; and
e. Response to complaints, concerns, or questions from individuals within _[Assignment: {pm-26_prm_3}]_.

=== Supplemental Guidance
Complaints, concerns, and questions from individuals can serve as valuable sources of input to organizations and ultimately improve operational models, uses of technology, data collection practices, and controls. Mechanisms that can be used by the public include telephone hotline, email, or web-based forms. The information necessary for successfully filing complaints includes contact information for the senior agency official for privacy or other official designated to receive complaints. Privacy complaints may also include personally identifiable information which is handled in accordance with relevant policies and processes.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130]

== PM-27 Privacy Reporting[[pm-27]]

=== Control
a. Develop _[Assignment: {pm-27_prm_1}]_ and disseminate to:
1. _[Assignment: {pm-27_prm_2}]_ to demonstrate accountability with statutory, regulatory, and policy privacy mandates; and
2. _[Assignment: {pm-27_prm_3}]_ and other personnel with responsibility for monitoring privacy program compliance; and
b. Review and update privacy reports _[Assignment: {pm-27_prm_4}]_.

=== Supplemental Guidance
Through internal and external reporting, organizations promote accountability and transparency in organizational privacy operations. Reporting can also help organizations to determine progress in meeting privacy compliance requirements and privacy controls, compare performance across the federal government, discover vulnerabilities, identify gaps in policy and implementation, and identify models for success. For federal agencies, privacy reports include annual senior agency official for privacy reports to OMB, reports to Congress required by Implementing Regulations of the 9/11 Commission Act, and other public reports required by law, regulation, or policy, including internal policies of organizations. The senior agency official for privacy consults with legal counsel, where appropriate, to ensure that organizations meet all applicable privacy reporting requirements.

=== References
https://www.congress.gov/113/plaws/publ283/PLAW-113publ283.pdf[FISMA], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A108/omb_circular_a-108.pdf[OMB A-108]

== PM-28 Risk Framing[[pm-28]]

=== Control
a. Identify and document:
1. Assumptions affecting risk assessments, risk responses, and risk monitoring;
2. Constraints affecting risk assessments, risk responses, and risk monitoring;
3. Priorities and trade-offs considered by the organization for managing risk; and
4. Organizational risk tolerance;
b. Distribute the results of risk framing activities to _[Assignment: {pm-28_prm_1}]_; and
c. Review and update risk framing considerations _[Assignment: {pm-28_prm_2}]_.

=== Supplemental Guidance
Risk framing is most effective when conducted at the organization level and in consultation with stakeholders throughout the organization including mission, business, and system owners. The assumptions, constraints, risk tolerance, priorities, and trade-offs identified as part of the risk framing process inform the risk management strategy, which in turn informs the conduct of risk assessment, risk response, and risk monitoring activities. Risk framing results are shared with organizational personnel, including mission and business owners, information owners or stewards, system owners, authorizing officials, senior agency information security officer, senior agency official for privacy, and senior accountable official for risk management.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39]

== PM-29 Risk Management Program Leadership Roles[[pm-29]]

=== Control
a. Appoint a Senior Accountable Official for Risk Management to align organizational information security and privacy management processes with strategic, operational, and budgetary planning processes; and
b. Establish a Risk Executive (function) to view and analyze risk from an organization-wide perspective and ensure management of risk is consistent across the organization.

=== Supplemental Guidance
The senior accountable official for risk management leads the risk executive (function) in organization-wide risk management activities.

=== References
https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37], https://doi.org/10.6028/NIST.SP.800-181r1[SP 800-181]

== PM-30 Supply Chain Risk Management Strategy[[pm-30]]

=== Control
a. Develop an organization-wide strategy for managing supply chain risks associated with the development, acquisition, maintenance, and disposal of systems, system components, and system services;
b. Implement the supply chain risk management strategy consistently across the organization; and
c. Review and update the supply chain risk management strategy on _[Assignment: {pm-30_prm_1}]_ or as required, to address organizational changes.

=== Supplemental Guidance
An organization-wide supply chain risk management strategy includes an unambiguous expression of the supply chain risk appetite and tolerance for the organization, acceptable supply chain risk mitigation strategies or controls, a process for consistently evaluating and monitoring supply chain risk, approaches for implementing and communicating the supply chain risk management strategy, and the associated roles and responsibilities. Supply chain risk management includes considerations of the security and privacy risks associated with the development, acquisition, maintenance, and disposal of systems, system components, and system services. The supply chain risk management strategy can be incorporated into the organization's overarching risk management strategy and can guide and inform supply chain policies and system-level supply chain risk management plans. In addition, the use of a risk executive function can facilitate a consistent, organization-wide application of the supply chain risk management strategy. The supply chain risk management strategy is implemented at the organization and mission/business levels, whereas the supply chain risk management plan (see 

=== References
https://www.govinfo.gov/content/pkg/STATUTE-88/pdf/STATUTE-88-Pg1896.pdf[PRIVACT], https://www.congress.gov/bill/115th-congress/senate-bill/3085[FASC18], https://www.whitehouse.gov/presidential-actions/executive-order-securing-information-communications-technology-services-supply-chain[EO 13873], https://www.federalregister.gov/d/2020-18939[41 CFR 201], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf[OMB M-17-06], https://www.cnss.gov/CNSS/issuances/Directives.cfm[CNSSD 505], https://www.iso.org/standard/59648.html[ISO 27036], https://www.iso.org/standard/74399.html[ISO 20243], https://doi.org/10.6028/NIST.SP.800-161[SP 800-161], https://doi.org/10.6028/NIST.IR.8272[IR 8272]

=== Control Enhancements
==== PM-30(1) Suppliers of Critical or Mission-essential Items[[pm-30-1]]

===== Control
Identify, prioritize, and assess suppliers of critical or mission-essential technologies, products, and services.

===== Supplemental Guidance
The identification and prioritization of suppliers of critical or mission-essential technologies, products, and services is paramount to the mission/business success of organizations. The assessment of suppliers is conducted using supplier reviews (see 

== PM-31 Continuous Monitoring Strategy[[pm-31]]

=== Control
Develop an organization-wide continuous monitoring strategy and implement continuous monitoring programs that include:
a. Establishing the following organization-wide metrics to be monitored: _[Assignment: {pm-31_prm_1}]_;
b. Establishing _[Assignment: {pm-31_prm_2}]_ for monitoring and _[Assignment: {pm-31_prm_3}]_ for assessment of control effectiveness;
c. Ongoing monitoring of organizationally-defined metrics in accordance with the continuous monitoring strategy;
d. Correlation and analysis of information generated by control assessments and monitoring;
e. Response actions to address results of the analysis of control assessment and monitoring information; and
f. Reporting the security and privacy status of organizational systems to _[Assignment: {pm-31_prm_4}]_
                  _[Assignment: {pm-31_prm_5}]_.

=== Supplemental Guidance
Continuous monitoring at the organization level facilitates ongoing awareness of the security and privacy posture across the organization to support organizational risk management decisions. The terms 

=== References
https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-137[SP 800-137], https://doi.org/10.6028/NIST.SP.800-137A[SP 800-137A]

== PM-32 Purposing[[pm-32]]

=== Control
Analyze _[Assignment: {pm-32_prm_1}]_ supporting mission essential services or functions to ensure that the information resources are being used consistent with their intended purpose.

=== Supplemental Guidance
Systems are designed to support a specific mission or business function. However, over time, systems and system components may be used to support services and functions that are outside of the scope of the intended mission or business functions. This can result in exposing information resources to unintended environments and uses that can significantly increase threat exposure. In doing so, the systems are more vulnerable to compromise, which can ultimately impact the services and functions for which they were intended. This is especially impactful for mission-essential services and functions. By analyzing resource use, organizations can identify such potential exposures.

=== References
https://doi.org/10.6028/NIST.SP.800-160v1[SP 800-160-1], https://doi.org/10.6028/NIST.SP.800-160v2[SP 800-160-2]

