= Personnel Security
:toc:
:toclevels: 1
:ps-1_prm_1: organization-defined personnel or roles
:ps-1_prm_2: one-or-more: Organization-level, Mission/business process-level, System-level
:ps-1_prm_3: organization-defined official
:ps-1_prm_4: organization-defined frequency
:ps-1_prm_5: organization-defined events
:ps-1_prm_6: organization-defined frequency
:ps-1_prm_7: organization-defined events
:ps-2_prm_1: organization-defined frequency
:ps-3_prm_1: organization-defined conditions requiring rescreening and, where rescreening is so indicated, the frequency of rescreening
:ps-3-3_prm_1: organization-defined additional personnel screening criteria
:ps-3-4_prm_1: organization-defined information types
:ps-3-4_prm_2: organization-defined citizenship requirements
:ps-4_prm_1: organization-defined time period
:ps-4_prm_2: organization-defined information security topics
:ps-4-2_prm_1: organization-defined automated mechanisms
:ps-4-2_prm_2: one-or-more: notify _[Assignment: organization-defined personnel or roles]_ of individual termination actions, disable access to system resources
:ps-4-2_prm_3: organization-defined personnel or roles
:ps-5_prm_1: organization-defined transfer or reassignment actions
:ps-5_prm_2: organization-defined time period following the formal transfer action
:ps-5_prm_3: organization-defined personnel or roles
:ps-5_prm_4: organization-defined time period
:ps-6_prm_1: organization-defined frequency
:ps-6_prm_2: organization-defined frequency
:ps-7_prm_1: organization-defined personnel or roles
:ps-7_prm_2: organization-defined time period
:ps-8_prm_1: organization-defined personnel or roles
:ps-8_prm_2: organization-defined time period

== PS-1 Policy and Procedures[[ps-1]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Develop, document, and disseminate to _[Assignment: {ps-1_prm_1}]_:
1. _[Assignment: {ps-1_prm_2}]_ personnel security policy that:
(a) Addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance; and
(b) Is consistent with applicable laws, executive orders, directives, regulations, policies, standards, and guidelines; and
2. Procedures to facilitate the implementation of the personnel security policy and the associated personnel security controls;
b. Designate an _[Assignment: {ps-1_prm_3}]_ to manage the development, documentation, and dissemination of the personnel security policy and procedures; and
c. Review and update the current personnel security:
1. Policy _[Assignment: {ps-1_prm_4}]_ and following _[Assignment: {ps-1_prm_5}]_; and
2. Procedures _[Assignment: {ps-1_prm_6}]_ and following _[Assignment: {ps-1_prm_7}]_.

=== Supplemental Guidance
Personnel security policy and procedures for the controls in the PS family that are implemented within systems and organizations. The risk management strategy is an important factor in establishing such policies and procedures. Policies and procedures contribute to security and privacy assurance. Therefore, it is important that security and privacy programs collaborate on their development. Security and privacy program policies and procedures at the organization level are preferable, in general, and may obviate the need for mission level or system-specific policies and procedures. The policy can be included as part of the general security and privacy policy or be represented by multiple policies reflecting the complex nature of organizations. Procedures can be established for security and privacy programs, for mission/business processes, and for systems, if needed. Procedures describe how the policies or controls are implemented and can be directed at the individual or role that is the object of the procedure. Procedures can be documented in system security and privacy plans or in one or more separate documents. Events that may precipitate an update to personnel security policy and procedures include, but are not limited to, assessment or audit findings, security incidents or breaches, or changes in applicable laws, executive orders, directives, regulations, policies, standards, and guidelines. Simply restating controls does not constitute an organizational policy or procedure.

=== References
https://doi.org/10.6028/NIST.SP.800-12r1[SP 800-12], https://doi.org/10.6028/NIST.SP.800-30r1[SP 800-30], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-100[SP 800-100]

== PS-2 Position Risk Designation[[ps-2]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2022-11-01

|===

=== Control
a. Assign a risk designation to all organizational positions;
b. Establish screening criteria for individuals filling those positions; and
c. Review and update position risk designations _[Assignment: {ps-2_prm_1}]_.

=== State Implementation Details
All authorized users (including, but not limited to, state organization personnel, temporary employees, and employees of independent contractors) of the state organization's information resources, shall formally acknowledge that they will comply with the security policies and procedures of the state organization or they shall not be granted access to information resources. The state organization head or his or her designated representative will determine the method of acknowledgement and how often this acknowledgement must be re-executed by the user to maintain access to state organization information resources.

=== Supplemental Guidance
Position risk designations reflect Office of Personnel Management (OPM) policy and guidance. Proper position designation is the foundation of an effective and consistent suitability and personnel security program. The Position Designation System (PDS) assesses the duties and responsibilities of a position to determine the degree of potential damage to the efficiency or integrity of the service due to misconduct of an incumbent of a position and establishes the risk level of that position. The PDS assessment also determines if the duties and responsibilities of the position present the potential for position incumbents to bring about a material adverse effect on national security and the degree of that potential effect, which establishes the sensitivity level of a position. The results of the assessment determine what level of investigation is conducted for a position. Risk designations can guide and inform the types of authorizations that individuals receive when accessing organizational information and information systems. Position screening criteria include explicit information security role appointment requirements. Parts 1400 and 731 of Title 5, Code of Federal Regulations, establish the requirements for organizations to evaluate relevant covered positions for a position sensitivity and position risk designation commensurate with the duties and responsibilities of those positions.

=== References
https://www.govinfo.gov/content/pkg/CFR-2012-title5-vol2/pdf/CFR-2012-title5-vol2-sec731-106.pdf[5 CFR 731], https://doi.org/10.6028/NIST.SP.800-181r1[SP 800-181]

== PS-3 Personnel Screening[[ps-3]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2022-11-01

|===

=== Control
a. Screen individuals prior to authorizing access to the system; and
b. Rescreen individuals in accordance with _[Assignment: {ps-3_prm_1}]_.

=== Supplemental Guidance
Personnel screening and rescreening activities reflect applicable laws, executive orders, directives, regulations, policies, standards, guidelines, and specific criteria established for the risk designations of assigned positions. Examples of personnel screening include background investigations and agency checks. Organizations may define different rescreening conditions and frequencies for personnel accessing systems based on types of information processed, stored, or transmitted by the systems.

=== References
https://www.archives.gov/isoo/policy-documents/cnsi-eo.html[EO 13526], https://obamawhitehouse.archives.gov/the-press-office/2011/10/07/executive-order-13587-structural-reforms-improve-security-classified-net[EO 13587], https://doi.org/10.6028/NIST.FIPS.199[FIPS 199], https://doi.org/10.6028/NIST.FIPS.201-2[FIPS 201-2], https://doi.org/10.6028/NIST.SP.800-60v1r1[SP 800-60-1], https://doi.org/10.6028/NIST.SP.800-60v2r1[SP 800-60-2], https://doi.org/10.6028/NIST.SP.800-73-4[SP 800-73-4], https://doi.org/10.6028/NIST.SP.800-76-2[SP 800-76-2], https://doi.org/10.6028/NIST.SP.800-78-4[SP 800-78-4]

=== Control Enhancements
==== PS-3(1) Classified Information[[ps-3-1]]

===== Control
Verify that individuals accessing a system processing, storing, or transmitting classified information are cleared and indoctrinated to the highest classification level of the information to which they have access on the system.

===== Supplemental Guidance
Classified information is the most sensitive information that the Federal Government processes, stores, or transmits. It is imperative that individuals have the requisite security clearances and system access authorizations prior to gaining access to such information. Access authorizations are enforced by system access controls (see 

==== PS-3(2) Formal Indoctrination[[ps-3-2]]

===== Control
Verify that individuals accessing a system processing, storing, or transmitting types of classified information that require formal indoctrination, are formally indoctrinated for all the relevant types of information to which they have access on the system.

===== Supplemental Guidance
Types of classified information that require formal indoctrination include Special Access Program (SAP), Restricted Data (RD), and Sensitive Compartmented Information (SCI).

==== PS-3(3) Information Requiring Special Protective Measures[[ps-3-3]]

===== Control
Verify that individuals accessing a system processing, storing, or transmitting information requiring special protection:
(a) Have valid access authorizations that are demonstrated by assigned official government duties; and
(b) Satisfy _[Assignment: {ps-3-3_prm_1}]_.

===== Supplemental Guidance
Organizational information that requires special protection includes controlled unclassified information. Personnel security criteria include position sensitivity background screening requirements.

==== PS-3(4) Citizenship Requirements[[ps-3-4]]

===== Control
Verify that individuals accessing a system processing, storing, or transmitting _[Assignment: {ps-3-4_prm_1}]_ meet _[Assignment: {ps-3-4_prm_2}]_.

===== Supplemental Guidance
None.

== PS-4 Personnel Termination[[ps-4]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
Upon termination of individual employment:
a. Disable system access within _[Assignment: {ps-4_prm_1}]_;
b. Terminate or revoke any authenticators and credentials associated with the individual;
c. Conduct exit interviews that include a discussion of _[Assignment: {ps-4_prm_2}]_;
d. Retrieve all security-related organizational system-related property; and
e. Retain access to organizational information and systems formerly controlled by terminated individual.

=== Supplemental Guidance
System property includes hardware authentication tokens, system administration technical manuals, keys, identification cards, and building passes. Exit interviews ensure that terminated individuals understand the security constraints imposed by being former employees and that proper accountability is achieved for system-related property. Security topics at exit interviews include reminding individuals of nondisclosure agreements and potential limitations on future employment. Exit interviews may not always be possible for some individuals, including in cases related to the unavailability of supervisors, illnesses, or job abandonment. Exit interviews are important for individuals with security clearances. The timely execution of termination actions is essential for individuals who have been terminated for cause. In certain situations, organizations consider disabling the system accounts of individuals who are being terminated prior to the individuals being notified.


=== Control Enhancements
==== PS-4(1) Post-employment Requirements[[ps-4-1]]

===== Control
(a) Notify terminated individuals of applicable, legally binding post-employment requirements for the protection of organizational information; and
(b) Require terminated individuals to sign an acknowledgment of post-employment requirements as part of the organizational termination process.

===== Supplemental Guidance
Organizations consult with the Office of the General Counsel regarding matters of post-employment requirements on terminated individuals.

==== PS-4(2) Automated Actions[[ps-4-2]]

===== Control
Use _[Assignment: {ps-4-2_prm_1}]_ to _[Assignment: {ps-4-2_prm_2}]_.

===== Supplemental Guidance
In organizations with many employees, not all personnel who need to know about termination actions receive the appropriate notifications, or if such notifications are received, they may not occur in a timely manner. Automated mechanisms can be used to send automatic alerts or notifications to organizational personnel or roles when individuals are terminated. Such automatic alerts or notifications can be conveyed in a variety of ways, including via telephone, electronic mail, text message, or websites. Automated mechanisms can also be employed to quickly and thoroughly disable access to system resources after an employee is terminated.

== PS-5 Personnel Transfer[[ps-5]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2022-11-01

|===

=== Control
a. Review and confirm ongoing operational need for current logical and physical access authorizations to systems and facilities when individuals are reassigned or transferred to other positions within the organization;
b. Initiate _[Assignment: {ps-5_prm_1}]_ within _[Assignment: {ps-5_prm_2}]_;
c. Modify access authorization as needed to correspond with any changes in operational need due to reassignment or transfer; and
d. Notify _[Assignment: {ps-5_prm_3}]_ within _[Assignment: {ps-5_prm_4}]_.

=== Supplemental Guidance
Personnel transfer applies when reassignments or transfers of individuals are permanent or of such extended duration as to make the actions warranted. Organizations define actions appropriate for the types of reassignments or transfers, whether permanent or extended. Actions that may be required for personnel transfers or reassignments to other positions within organizations include returning old and issuing new keys, identification cards, and building passes; closing system accounts and establishing new accounts; changing system access authorizations (i.e., privileges); and providing for access to official records to which individuals had access at previous work locations and in previous system accounts.


== PS-6 Access Agreements[[ps-6]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2022-11-01

|===

=== Control
a. Develop and document access agreements for organizational systems;
b. Review and update the access agreements _[Assignment: {ps-6_prm_1}]_; and
c. Verify that individuals requiring access to organizational information and systems:
1. Sign appropriate access agreements prior to being granted access; and
2. Re-sign access agreements to maintain access to organizational systems when access agreements have been updated or _[Assignment: {ps-6_prm_2}]_.

=== Supplemental Guidance
Access agreements include nondisclosure agreements, acceptable use agreements, rules of behavior, and conflict-of-interest agreements. Signed access agreements include an acknowledgement that individuals have read, understand, and agree to abide by the constraints associated with organizational systems to which access is authorized. Organizations can use electronic signatures to acknowledge access agreements unless specifically prohibited by organizational policy.


=== Control Enhancements
==== PS-6(1) Information Requiring Special Protection[[ps-6-1]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ps.adoc#ps-3[PS-3]

==== PS-6(2) Classified Information Requiring Special Protection[[ps-6-2]]

===== Control
Verify that access to classified information requiring special protection is granted only to individuals who:
(a) Have a valid access authorization that is demonstrated by assigned official government duties;
(b) Satisfy associated personnel security criteria; and
(c) Have read, understood, and signed a nondisclosure agreement.

===== Supplemental Guidance
Classified information that requires special protection includes collateral information, Special Access Program (SAP) information, and Sensitive Compartmented Information (SCI). Personnel security criteria reflect applicable laws, executive orders, directives, regulations, policies, standards, and guidelines.

==== PS-6(3) Post-employment Requirements[[ps-6-3]]

===== Control
(a) Notify individuals of applicable, legally binding post-employment requirements for protection of organizational information; and
(b) Require individuals to sign an acknowledgment of these requirements, if applicable, as part of granting initial access to covered information.

===== Supplemental Guidance
Organizations consult with the Office of the General Counsel regarding matters of post-employment requirements on terminated individuals.

== PS-7 External Personnel Security[[ps-7]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2022-11-01

|===

=== Control
a. Establish personnel security requirements, including security roles and responsibilities for external providers;
b. Require external providers to comply with personnel security policies and procedures established by the organization;
c. Document personnel security requirements;
d. Require external providers to notify _[Assignment: {ps-7_prm_1}]_ of any personnel transfers or terminations of external personnel who possess organizational credentials and/or badges, or who have system privileges within _[Assignment: {ps-7_prm_2}]_; and
e. Monitor provider compliance with personnel security requirements.

=== Supplemental Guidance
External provider refers to organizations other than the organization operating or acquiring the system. External providers include service bureaus, contractors, and other organizations that provide system development, information technology services, testing or assessment services, outsourced applications, and network/security management. Organizations explicitly include personnel security requirements in acquisition-related documents. External providers may have personnel working at organizational facilities with credentials, badges, or system privileges issued by organizations. Notifications of external personnel changes ensure the appropriate termination of privileges and credentials. Organizations define the transfers and terminations deemed reportable by security-related characteristics that include functions, roles, and the nature of credentials or privileges associated with transferred or terminated individuals.

=== References
https://doi.org/10.6028/NIST.SP.800-35[SP 800-35], https://doi.org/10.6028/NIST.SP.800-63-3[SP 800-63-3]

== PS-8 Personnel Sanctions[[ps-8]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2022-11-01

|===

=== Control
a. Employ a formal sanctions process for individuals failing to comply with established information security and privacy policies and procedures; and
b. Notify _[Assignment: {ps-8_prm_1}]_ within _[Assignment: {ps-8_prm_2}]_ when a formal employee sanctions process is initiated, identifying the individual sanctioned and the reason for the sanction.

=== Supplemental Guidance
Organizational sanctions reflect applicable laws, executive orders, directives, regulations, policies, standards, and guidelines. Sanctions processes are described in access agreements and can be included as part of general personnel policies for organizations and/or specified in security and privacy policies. Organizations consult with the Office of the General Counsel regarding matters of employee sanctions.


== PS-9 Position Descriptions[[ps-9]]

=== Control
Incorporate security and privacy roles and responsibilities into organizational position descriptions.

=== Supplemental Guidance
Specification of security and privacy roles in individual organizational position descriptions facilitates clarity in understanding the security or privacy responsibilities associated with the roles and the role-based security and privacy training requirements for the roles.

=== References
https://doi.org/10.6028/NIST.SP.800-181r1[SP 800-181]

