= Risk Assessment
:toc:
:toclevels: 1
:ra-1_prm_1: organization-defined personnel or roles
:ra-1_prm_2: one-or-more: Organization-level, Mission/business process-level, System-level
:ra-1_prm_3: organization-defined official
:ra-1_prm_4: organization-defined frequency
:ra-1_prm_5: organization-defined events
:ra-1_prm_6: organization-defined frequency
:ra-1_prm_7: organization-defined events
:ra-3_prm_1: security and privacy plans, risk assessment report, _[Assignment: organization-defined document]_
:ra-3_prm_2: organization-defined document
:ra-3_prm_3: organization-defined frequency
:ra-3_prm_4: organization-defined personnel or roles
:ra-3_prm_5: organization-defined frequency
:ra-3-1_prm_1: organization-defined systems, system components, and system services
:ra-3-1_prm_2: organization-defined frequency
:ra-3-3_prm_1: organization-defined means
:ra-3-4_prm_1: organization-defined systems or system components
:ra-3-4_prm_2: organization-defined advanced automation and analytics capabilities
:ra-5_prm_1: organization-defined frequency and/or randomly in accordance with organization-defined process
:ra-5_prm_2: organization-defined response times
:ra-5_prm_3: organization-defined personnel or roles
:ra-5-2_prm_1: one-or-more: _[Assignment: organization-defined frequency]_, prior to a new scan, when new vulnerabilities are identified and reported
:ra-5-2_prm_2: organization-defined frequency
:ra-5-4_prm_1: organization-defined corrective actions
:ra-5-5_prm_1: organization-defined system components
:ra-5-5_prm_2: organization-defined vulnerability scanning activities
:ra-5-6_prm_1: organization-defined automated mechanisms
:ra-5-8_prm_1: organization-defined system
:ra-5-8_prm_2: organization-defined time period
:ra-6_prm_1: organization-defined locations
:ra-6_prm_2: one-or-more: _[Assignment: organization-defined frequency]_, when the following events or indicators occur: _[Assignment: organization-defined events or indicators]_
:ra-6_prm_3: organization-defined frequency
:ra-6_prm_4: organization-defined events or indicators
:ra-9_prm_1: organization-defined systems, system components, or system services
:ra-9_prm_2: organization-defined decision points in the system development life cycle
:ra-10_prm_1: organization-defined frequency

== RA-1 Policy and Procedures[[ra-1]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Develop, document, and disseminate to _[Assignment: {ra-1_prm_1}]_:
1. _[Assignment: {ra-1_prm_2}]_ risk assessment policy that:
(a) Addresses purpose, scope, roles, responsibilities, management commitment, coordination among organizational entities, and compliance; and
(b) Is consistent with applicable laws, executive orders, directives, regulations, policies, standards, and guidelines; and
2. Procedures to facilitate the implementation of the risk assessment policy and the associated risk assessment controls;
b. Designate an _[Assignment: {ra-1_prm_3}]_ to manage the development, documentation, and dissemination of the risk assessment policy and procedures; and
c. Review and update the current risk assessment:
1. Policy _[Assignment: {ra-1_prm_4}]_ and following _[Assignment: {ra-1_prm_5}]_; and
2. Procedures _[Assignment: {ra-1_prm_6}]_ and following _[Assignment: {ra-1_prm_7}]_.

=== Supplemental Guidance
Risk assessment policy and procedures address the controls in the RA family that are implemented within systems and organizations. The risk management strategy is an important factor in establishing such policies and procedures. Policies and procedures contribute to security and privacy assurance. Therefore, it is important that security and privacy programs collaborate on the development of risk assessment policy and procedures. Security and privacy program policies and procedures at the organization level are preferable, in general, and may obviate the need for mission- or system-specific policies and procedures. The policy can be included as part of the general security and privacy policy or be represented by multiple policies reflecting the complex nature of organizations. Procedures can be established for security and privacy programs, for mission or business processes, and for systems, if needed. Procedures describe how the policies or controls are implemented and can be directed at the individual or role that is the object of the procedure. Procedures can be documented in system security and privacy plans or in one or more separate documents. Events that may precipitate an update to risk assessment policy and procedures include assessment or audit findings, security incidents or breaches, or changes in laws, executive orders, directives, regulations, policies, standards, and guidelines. Simply restating controls does not constitute an organizational policy or procedure.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-12r1[SP 800-12], https://doi.org/10.6028/NIST.SP.800-30r1[SP 800-30], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-100[SP 800-100]

== RA-2 Security Categorization[[ra-2]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Categorize the system and information it processes, stores, and transmits;
b. Document the security categorization results, including supporting rationale, in the security plan for the system; and
c. Verify that the authorizing official or authorizing official designated representative reviews and approves the security categorization decision.

=== State Implementation Details
State organizations are responsible for defining all information classification categories except the Confidential Information category, which is defined in Subchapter A of this chapter, and establishing the appropriate controls for each.

=== TAMUS Implementation Details
The System member:
a. categorizes information and information systems owned or managed by the member using a data categorization structure that incorporates the guidance provided in Appendix D: Data Categorization, at a minimum, and
b. reduces, and eliminates where possible, the collection and/or use of sensitive personal information [TxBCC 521.002](#5b23f2c5-4c42-4b0e-a75b-34af3bcafb10) in information resources under the control of the member.

=== Supplemental Guidance
Security categories describe the potential adverse impacts or negative consequences to organizational operations, organizational assets, and individuals if organizational information and systems are compromised through a loss of confidentiality, integrity, or availability. Security categorization is also a type of asset loss characterization in systems security engineering processes that is carried out throughout the system development life cycle. Organizations can use privacy risk assessments or privacy impact assessments to better understand the potential adverse effects on individuals. 
Organizations conduct the security categorization process as an organization-wide activity with the direct involvement of chief information officers, senior agency information security officers, senior agency officials for privacy, system owners, mission and business owners, and information owners or stewards. Organizations consider the potential adverse impacts to other organizations and, in accordance with 
Security categorization processes facilitate the development of inventories of information assets and, along with 

=== References
https://statutes.capitol.texas.gov/Docs/BC/htm/BC.521.htm[Texas Business and Commerce Code SS521.002], https://doi.org/10.6028/NIST.FIPS.199[FIPS 199], https://doi.org/10.6028/NIST.FIPS.200[FIPS 200], https://doi.org/10.6028/NIST.SP.800-30r1[SP 800-30], https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-60v1r1[SP 800-60-1], https://doi.org/10.6028/NIST.SP.800-60v2r1[SP 800-60-2], https://doi.org/10.6028/NIST.SP.800-160v1[SP 800-160-1], https://www.cnss.gov/CNSS/issuances/Instructions.cfm[CNSSI 1253], https://www.archives.gov/cui[NARA CUI]

=== Control Enhancements
==== RA-2(1) Impact-level Prioritization[[ra-2-1]]

===== Control
Conduct an impact-level prioritization of organizational systems to obtain additional granularity on system impact levels.

===== Supplemental Guidance
Organizations apply the 

== RA-3 Risk Assessment[[ra-3]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Conduct a risk assessment, including:
1. Identifying threats to and vulnerabilities in the system;
2. Determining the likelihood and magnitude of harm from unauthorized access, use, disclosure, disruption, modification, or destruction of the system, the information it processes, stores, or transmits, and any related information; and
3. Determining the likelihood and impact of adverse effects on individuals arising from the processing of personally identifiable information;
b. Integrate risk assessment results and risk management decisions from the organization and mission or business process perspectives with system-level risk assessments;
c. Document risk assessment results in _[Assignment: {ra-3_prm_1}]_;
d. Review risk assessment results _[Assignment: {ra-3_prm_3}]_;
e. Disseminate risk assessment results to _[Assignment: {ra-3_prm_4}]_; and
f. Update the risk assessment _[Assignment: {ra-3_prm_5}]_ or when there are significant changes to the system, its environment of operation, or other conditions that may impact the security or privacy state of the system.

=== State Implementation Details
1. A risk assessment of information resources shall be performed and documented. The risk assessment shall be updated based on the inherent risk. The inherent risk and frequency of the risk assessment will be ranked, at a minimum, as either "High,"
              "Moderate," or "Low."
2. Risk assessment results, vulnerability reports, and similar information shall be documented and presented to the state organization head or his or her designated representative(s). The state organization head or his or her designated
              representative(s) shall make the final risk management decisions to either accept exposures or protect the data according to its value/sensitivity. The state organization head or his or her designated representative(s) shall approve the security risk
              management plan. This information may be exempt from disclosure under SS2054.077(c), Government Code.

=== Supplemental Guidance
Risk assessments consider threats, vulnerabilities, likelihood, and impact to organizational operations and assets, individuals, other organizations, and the Nation. Risk assessments also consider risk from external parties, including contractors who operate systems on behalf of the organization, individuals who access organizational systems, service providers, and outsourcing entities.
Organizations can conduct risk assessments at all three levels in the risk management hierarchy (i.e., organization level, mission/business process level, or information system level) and at any stage in the system development life cycle. Risk assessments can also be conducted at various steps in the Risk Management Framework, including preparation, categorization, control selection, control implementation, control assessment, authorization, and control monitoring. Risk assessment is an ongoing activity carried out throughout the system development life cycle.
Risk assessments can also address information related to the system, including system design, the intended use of the system, testing results, and supply chain-related information or artifacts. Risk assessments can play an important role in control selection processes, particularly during the application of tailoring guidance and in the earliest phases of capability determination.

=== References
https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://doi.org/10.6028/NIST.SP.800-30r1[SP 800-30], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-161[SP 800-161], https://doi.org/10.6028/NIST.IR.8023[IR 8023], https://doi.org/10.6028/NIST.IR.8062[IR 8062], https://doi.org/10.6028/NIST.IR.8272[IR 8272]

=== Control Enhancements
==== RA-3(1) Supply Chain Risk Assessment[[ra-3-1]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

===== Control
(a) Assess supply chain risks associated with _[Assignment: {ra-3-1_prm_1}]_; and
(b) Update the supply chain risk assessment _[Assignment: {ra-3-1_prm_2}]_, when there are significant changes to the relevant supply chain, or when changes to the system, environments of operation, or other conditions may necessitate a change in the supply chain.

===== Supplemental Guidance
Supply chain-related events include disruption, use of defective components, insertion of counterfeits, theft, malicious development practices, improper delivery practices, and insertion of malicious code. These events can have a significant impact on the confidentiality, integrity, or availability of a system and its information and, therefore, can also adversely impact organizational operations (including mission, functions, image, or reputation), organizational assets, individuals, other organizations, and the Nation. The supply chain-related events may be unintentional or malicious and can occur at any point during the system life cycle. An analysis of supply chain risk can help an organization identify systems or components for which additional supply chain risk mitigations are required.

==== RA-3(2) Use of All-source Intelligence[[ra-3-2]]

===== Control
Use all-source intelligence to assist in the analysis of risk.

===== Supplemental Guidance
Organizations employ all-source intelligence to inform engineering, acquisition, and risk management decisions. All-source intelligence consists of information derived from all available sources, including publicly available or open-source information, measurement and signature intelligence, human intelligence, signals intelligence, and imagery intelligence. All-source intelligence is used to analyze the risk of vulnerabilities (both intentional and unintentional) from development, manufacturing, and delivery processes, people, and the environment. The risk analysis may be performed on suppliers at multiple tiers in the supply chain sufficient to manage risks. Organizations may develop agreements to share all-source intelligence information or resulting decisions with other organizations, as appropriate.

==== RA-3(3) Dynamic Threat Awareness[[ra-3-3]]

===== Control
Determine the current cyber threat environment on an ongoing basis using _[Assignment: {ra-3-3_prm_1}]_.

===== Supplemental Guidance
The threat awareness information that is gathered feeds into the organization's information security operations to ensure that procedures are updated in response to the changing threat environment. For example, at higher threat levels, organizations may change the privilege or authentication thresholds required to perform certain operations.

==== RA-3(4) Predictive Cyber Analytics[[ra-3-4]]

===== Control
Employ the following advanced automation and analytics capabilities to predict and identify risks to _[Assignment: {ra-3-4_prm_1}]_: _[Assignment: {ra-3-4_prm_2}]_.

===== Supplemental Guidance
A properly resourced Security Operations Center (SOC) or Computer Incident Response Team (CIRT) may be overwhelmed by the volume of information generated by the proliferation of security tools and appliances unless it employs advanced automation and analytics to analyze the data. Advanced automation and analytics capabilities are typically supported by artificial intelligence concepts, including machine learning. Examples include Automated Threat Discovery and Response (which includes broad-based collection, context-based analysis, and adaptive response capabilities), automated workflow operations, and machine assisted decision tools. Note, however, that sophisticated adversaries may be able to extract information related to analytic parameters and retrain the machine learning to classify malicious activity as benign. Accordingly, machine learning is augmented by human monitoring to ensure that sophisticated adversaries are not able to conceal their activities.

== RA-4 Risk Assessment Update[[ra-4]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ra.adoc#ra-3[RA-3]


== RA-5 Vulnerability Monitoring and Scanning[[ra-5]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
a. Monitor and scan for vulnerabilities in the system and hosted applications _[Assignment: {ra-5_prm_1}]_ and when new vulnerabilities potentially affecting the system are identified and reported;
b. Employ vulnerability monitoring tools and techniques that facilitate interoperability among tools and automate parts of the vulnerability management process by using standards for:
1. Enumerating platforms, software flaws, and improper configurations;
2. Formatting checklists and test procedures; and
3. Measuring vulnerability impact;
c. Analyze vulnerability scan reports and results from vulnerability monitoring;
d. Remediate legitimate vulnerabilities _[Assignment: {ra-5_prm_2}]_ in accordance with an organizational assessment of risk;
e. Share information obtained from the vulnerability monitoring process and control assessments with _[Assignment: {ra-5_prm_3}]_ to help eliminate similar vulnerabilities in other systems; and
f. Employ vulnerability monitoring tools that include the capability to readily update the vulnerabilities to be scanned.

=== State Implementation Details
The state organization scans for vulnerabilities in the information system at least annually or when significant new vulnerabilities potentially affecting the system are identified and reported.

=== Supplemental Guidance
Security categorization of information and systems guides the frequency and comprehensiveness of vulnerability monitoring (including scans). Organizations determine the required vulnerability monitoring for system components, ensuring that the potential sources of vulnerabilities-such as infrastructure components (e.g., switches, routers, guards, sensors), networked printers, scanners, and copiers-are not overlooked. The capability to readily update vulnerability monitoring tools as new vulnerabilities are discovered and announced and as new scanning methods are developed helps to ensure that new vulnerabilities are not missed by employed vulnerability monitoring tools. The vulnerability monitoring tool update process helps to ensure that potential vulnerabilities in the system are identified and addressed as quickly as possible. Vulnerability monitoring and analyses for custom software may require additional approaches, such as static analysis, dynamic analysis, binary analysis, or a hybrid of the three approaches. Organizations can use these analysis approaches in source code reviews and in a variety of tools, including web-based application scanners, static analysis tools, and binary analyzers.
Vulnerability monitoring includes scanning for patch levels; scanning for functions, ports, protocols, and services that should not be accessible to users or devices; and scanning for flow control mechanisms that are improperly configured or operating incorrectly. Vulnerability monitoring may also include continuous vulnerability monitoring tools that use instrumentation to continuously analyze components. Instrumentation-based tools may improve accuracy and may be run throughout an organization without scanning. Vulnerability monitoring tools that facilitate interoperability include tools that are Security Content Automated Protocol (SCAP)-validated. Thus, organizations consider using scanning tools that express vulnerabilities in the Common Vulnerabilities and Exposures (CVE) naming convention and that employ the Open Vulnerability Assessment Language (OVAL) to determine the presence of vulnerabilities. Sources for vulnerability information include the Common Weakness Enumeration (CWE) listing and the National Vulnerability Database (NVD). Control assessments, such as red team exercises, provide additional sources of potential vulnerabilities for which to scan. Organizations also consider using scanning tools that express vulnerability impact by the Common Vulnerability Scoring System (CVSS).
Vulnerability monitoring includes a channel and process for receiving reports of security vulnerabilities from the public at-large. Vulnerability disclosure programs can be as simple as publishing a monitored email address or web form that can receive reports, including notification authorizing good-faith research and disclosure of security vulnerabilities. Organizations generally expect that such research is happening with or without their authorization and can use public vulnerability disclosure channels to increase the likelihood that discovered vulnerabilities are reported directly to the organization for remediation.
Organizations may also employ the use of financial incentives (also known as 

=== References
https://www.iso.org/standard/72311.html[ISO 29147], https://doi.org/10.6028/NIST.SP.800-40r3[SP 800-40], https://doi.org/10.6028/NIST.SP.800-53Ar4[SP 800-53A], https://doi.org/10.6028/NIST.SP.800-70r4[SP 800-70], https://doi.org/10.6028/NIST.SP.800-115[SP 800-115], https://doi.org/10.6028/NIST.SP.800-126r3[SP 800-126], https://doi.org/10.6028/NIST.IR.7788[IR 7788], https://doi.org/10.6028/NIST.IR.8011-4[IR 8011-4], https://doi.org/10.6028/NIST.IR.8023[IR 8023]

=== Control Enhancements
==== RA-5(1) Update Tool Capability[[ra-5-1]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ra.adoc#ra-5[RA-5]

==== RA-5(2) Update Vulnerabilities to Be Scanned[[ra-5-2]]

===== Control
Update the system vulnerabilities to be scanned _[Assignment: {ra-5-2_prm_1}]_.

===== Supplemental Guidance
Due to the complexity of modern software, systems, and other factors, new vulnerabilities are discovered on a regular basis. It is important that newly discovered vulnerabilities are added to the list of vulnerabilities to be scanned to ensure that the organization can take steps to mitigate those vulnerabilities in a timely manner.

==== RA-5(3) Breadth and Depth of Coverage[[ra-5-3]]

===== Control
Define the breadth and depth of vulnerability scanning coverage.

===== Supplemental Guidance
The breadth of vulnerability scanning coverage can be expressed as a percentage of components within the system, by the particular types of systems, by the criticality of systems, or by the number of vulnerabilities to be checked. Conversely, the depth of vulnerability scanning coverage can be expressed as the level of the system design that the organization intends to monitor (e.g., component, module, subsystem, element). Organizations can determine the sufficiency of vulnerability scanning coverage with regard to its risk tolerance and other factors. Scanning tools and how the tools are configured may affect the depth and coverage. Multiple scanning tools may be needed to achieve the desired depth and coverage. 

==== RA-5(4) Discoverable Information[[ra-5-4]]

===== Control
Determine information about the system that is discoverable and take _[Assignment: {ra-5-4_prm_1}]_.

===== Supplemental Guidance
Discoverable information includes information that adversaries could obtain without compromising or breaching the system, such as by collecting information that the system is exposing or by conducting extensive web searches. Corrective actions include notifying appropriate organizational personnel, removing designated information, or changing the system to make the designated information less relevant or attractive to adversaries. This enhancement excludes intentionally discoverable information that may be part of a decoy capability (e.g., honeypots, honeynets, or deception nets) deployed by the organization.

==== RA-5(5) Privileged Access[[ra-5-5]]

===== Control
Implement privileged access authorization to _[Assignment: {ra-5-5_prm_1}]_ for _[Assignment: {ra-5-5_prm_2}]_.

===== Supplemental Guidance
In certain situations, the nature of the vulnerability scanning may be more intrusive, or the system component that is the subject of the scanning may contain classified or controlled unclassified information, such as personally identifiable information. Privileged access authorization to selected system components facilitates more thorough vulnerability scanning and protects the sensitive nature of such scanning.

==== RA-5(6) Automated Trend Analyses[[ra-5-6]]

===== Control
Compare the results of multiple vulnerability scans using _[Assignment: {ra-5-6_prm_1}]_.

===== Supplemental Guidance
Using automated mechanisms to analyze multiple vulnerability scans over time can help determine trends in system vulnerabilities and identify patterns of attack.

==== RA-5(7) Automated Detection and Notification of Unauthorized Components[[ra-5-7]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:cm.adoc#cm-8[CM-8]

==== RA-5(8) Review Historic Audit Logs[[ra-5-8]]

===== Control
Review historic audit logs to determine if a vulnerability identified in a _[Assignment: {ra-5-8_prm_1}]_ has been previously exploited within an _[Assignment: {ra-5-8_prm_2}]_.

===== Supplemental Guidance
Reviewing historic audit logs to determine if a recently detected vulnerability in a system has been previously exploited by an adversary can provide important information for forensic analyses. Such analyses can help identify, for example, the extent of a previous intrusion, the trade craft employed during the attack, organizational information exfiltrated or modified, mission or business capabilities affected, and the duration of the attack.

==== RA-5(9) Penetration Testing and Analyses[[ra-5-9]]

[width=50\%]
|===



|===

Status:: Withdrawn

Incorporated Into:: xref:ca.adoc#ca-8[CA-8]

==== RA-5(10) Correlate Scanning Information[[ra-5-10]]

===== Control
Correlate the output from vulnerability scanning tools to determine the presence of multi-vulnerability and multi-hop attack vectors.

===== Supplemental Guidance
An attack vector is a path or means by which an adversary can gain access to a system in order to deliver malicious code or exfiltrate information. Organizations can use attack trees to show how hostile activities by adversaries interact and combine to produce adverse impacts or negative consequences to systems and organizations. Such information, together with correlated data from vulnerability scanning tools, can provide greater clarity regarding multi-vulnerability and multi-hop attack vectors. The correlation of vulnerability scanning information is especially important when organizations are transitioning from older technologies to newer technologies (e.g., transitioning from IPv4 to IPv6 network protocols). During such transitions, some system components may inadvertently be unmanaged and create opportunities for adversary exploitation.

==== RA-5(11) Public Disclosure Program[[ra-5-11]]

===== Control
Establish a public reporting channel for receiving reports of vulnerabilities in organizational systems and system components.

===== Supplemental Guidance
The reporting channel is publicly discoverable and contains clear language authorizing good-faith research and the disclosure of vulnerabilities to the organization. The organization does not condition its authorization on an expectation of indefinite non-disclosure to the public by the reporting entity but may request a specific time period to properly remediate the vulnerability.

== RA-6 Technical Surveillance Countermeasures Survey[[ra-6]]

=== Control
Employ a technical surveillance countermeasures survey at _[Assignment: {ra-6_prm_1}]_
               _[Assignment: {ra-6_prm_2}]_.

=== Supplemental Guidance
A technical surveillance countermeasures survey is a service provided by qualified personnel to detect the presence of technical surveillance devices and hazards and to identify technical security weaknesses that could be used in the conduct of a technical penetration of the surveyed facility. Technical surveillance countermeasures surveys also provide evaluations of the technical security posture of organizations and facilities and include visual, electronic, and physical examinations of surveyed facilities, internally and externally. The surveys also provide useful input for risk assessments and information regarding organizational exposure to potential adversaries.


== RA-7 Risk Response[[ra-7]]

[width=50\%]
|===
|NIST Baseline |Required By 

|LOW
|2023-05-01

|===

=== Control
Respond to findings from security and privacy assessments, monitoring, and audits in accordance with organizational risk tolerance.

=== Supplemental Guidance
Organizations have many options for responding to risk including mitigating risk by implementing new controls or strengthening existing controls, accepting risk with appropriate justification or rationale, sharing or transferring risk, or avoiding risk. The risk tolerance of the organization influences risk response decisions and actions. Risk response addresses the need to determine an appropriate response to risk before generating a plan of action and milestones entry. For example, the response may be to accept risk or reject risk, or it may be possible to mitigate the risk immediately so that a plan of action and milestones entry is not needed. However, if the risk response is to mitigate the risk, and the mitigation cannot be completed immediately, a plan of action and milestones entry is generated.

=== References
https://doi.org/10.6028/NIST.FIPS.199[FIPS 199], https://doi.org/10.6028/NIST.FIPS.200[FIPS 200], https://doi.org/10.6028/NIST.SP.800-30r1[SP 800-30], https://doi.org/10.6028/NIST.SP.800-37r2[SP 800-37], https://doi.org/10.6028/NIST.SP.800-39[SP 800-39], https://doi.org/10.6028/NIST.SP.800-160v1[SP 800-160-1]

== RA-8 Privacy Impact Assessments[[ra-8]]

=== Control
Conduct privacy impact assessments for systems, programs, or other activities before:
a. Developing or procuring information technology that processes personally identifiable information; and
b. Initiating a new collection of personally identifiable information that:
1. Will be processed using information technology; and
2. Includes personally identifiable information permitting the physical or virtual (online) contacting of a specific individual, if identical questions have been posed to, or identical reporting requirements imposed on, ten or more individuals, other than agencies, instrumentalities, or employees of the federal government.

=== Supplemental Guidance
A privacy impact assessment is an analysis of how personally identifiable information is handled to ensure that handling conforms to applicable privacy requirements, determine the privacy risks associated with an information system or activity, and evaluate ways to mitigate privacy risks. A privacy impact assessment is both an analysis and a formal document that details the process and the outcome of the analysis.
Organizations conduct and develop a privacy impact assessment with sufficient clarity and specificity to demonstrate that the organization fully considered privacy and incorporated appropriate privacy protections from the earliest stages of the organization's activity and throughout the information life cycle. In order to conduct a meaningful privacy impact assessment, the organization's senior agency official for privacy works closely with program managers, system owners, information technology experts, security officials, counsel, and other relevant organization personnel. Moreover, a privacy impact assessment is not a time-restricted activity that is limited to a particular milestone or stage of the information system or personally identifiable information life cycles. Rather, the privacy analysis continues throughout the system and personally identifiable information life cycles. Accordingly, a privacy impact assessment is a living document that organizations update whenever changes to the information technology, changes to the organization's practices, or other factors alter the privacy risks associated with the use of such information technology.
To conduct the privacy impact assessment, organizations can use security and privacy risk assessments. Organizations may also use other related processes that may have different names, including privacy threshold analyses. A privacy impact assessment can also serve as notice to the public regarding the organization's practices with respect to privacy. Although conducting and publishing privacy impact assessments may be required by law, organizations may develop such policies in the absence of applicable laws. For federal agencies, privacy impact assessments may be required by 

=== References
https://www.congress.gov/107/plaws/publ347/PLAW-107publ347.pdf[EGOV], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf[OMB A-130], https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2003/m03_22.pdf[OMB M-03-22]

== RA-9 Criticality Analysis[[ra-9]]

=== Control
Identify critical system components and functions by performing a criticality analysis for _[Assignment: {ra-9_prm_1}]_ at _[Assignment: {ra-9_prm_2}]_.

=== Supplemental Guidance
Not all system components, functions, or services necessarily require significant protections. For example, criticality analysis is a key tenet of supply chain risk management and informs the prioritization of protection activities. The identification of critical system components and functions considers applicable laws, executive orders, regulations, directives, policies, standards, system functionality requirements, system and component interfaces, and system and component dependencies. Systems engineers conduct a functional decomposition of a system to identify mission-critical functions and components. The functional decomposition includes the identification of organizational missions supported by the system, decomposition into the specific functions to perform those missions, and traceability to the hardware, software, and firmware components that implement those functions, including when the functions are shared by many components within and  external to the system.
The operational environment of a system or a system component may impact the criticality, including the connections to and dependencies on cyber-physical systems, devices, system-of-systems, and outsourced IT services. System components that allow unmediated access to critical system components or functions are considered critical due to the inherent vulnerabilities that such components create. Component and function criticality are assessed in terms of the impact of a component or function failure on the organizational missions that are supported by the system that contains the components and functions.
Criticality analysis is performed when an architecture or design is being developed, modified, or upgraded. If such analysis is performed early in the system development life cycle, organizations may be able to modify the system design to reduce the critical nature of these components and functions, such as by adding redundancy or alternate paths into the system design. Criticality analysis can also influence the protection measures required by development contractors. In addition to criticality analysis for systems, system components, and system services, criticality analysis of information is an important consideration. Such analysis is conducted as part of security categorization in 

=== References
https://doi.org/10.6028/NIST.IR.8179[IR 8179]

== RA-10 Threat Hunting[[ra-10]]

=== Control
a. Establish and maintain a cyber threat hunting capability to:
1. Search for indicators of compromise in organizational systems; and
2. Detect, track, and disrupt threats that evade existing controls; and
b. Employ the threat hunting capability _[Assignment: {ra-10_prm_1}]_.

=== Supplemental Guidance
Threat hunting is an active means of cyber defense in contrast to traditional protection measures, such as firewalls, intrusion detection and prevention systems, quarantining malicious code in sandboxes, and Security Information and Event Management technologies and systems. Cyber threat hunting involves proactively searching organizational systems, networks, and infrastructure for advanced threats. The objective is to track and disrupt cyber adversaries as early as possible in the attack sequence and to measurably improve the speed and accuracy of organizational responses. Indications of compromise include unusual network traffic, unusual file changes, and the presence of malicious code. Threat hunting teams leverage existing threat intelligence and may create new threat intelligence, which is shared with peer organizations, Information Sharing and Analysis Organizations (ISAO), Information Sharing and Analysis Centers (ISAC), and relevant government departments and agencies.

=== References
https://doi.org/10.6028/NIST.SP.800-30r1[SP 800-30]

