# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cybersecurity Standards
email: contact@cyber.tamus.edu
description: >- # this means to ignore newlines until "baseurl:"
  Texas A&M System Cybersecurity Standards provide system members with additional 
  guidance that enhances State-level requirements for implementing security controls.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cyber-standards.tamus.edu" # the base hostname & protocol for your site, e.g. http://example.com
logolinkurl: "https://cyber.tamus.edu" # the a link for the logo image
search: true

# Build settings
# theme: tamus-cyber-theme
remote_theme: tamus-cyber/tamus-cyber-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

permalink: pretty

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Don't clobber these files in the destination folder
keep_files:
  - css
  - js

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed
